/*
 * This file is generated by jOOQ.
 */
package com.hm.achievement.db;

import com.hm.achievement.db.tables.Achievements;
import com.hm.achievement.db.tables.Connections;
import com.hm.achievement.db.tables.NormalAchievement;

import com.hm.achievement.db.tables.records.AchievementsRecord;
import com.hm.achievement.db.tables.records.ConnectionsRecord;
import com.hm.achievement.db.tables.records.NormalAchievementRecord;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.Internal;

/**
 * A class modelling foreign key relationships and constraints of tables of the <code></code> schema.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

	// -------------------------------------------------------------------------
	// IDENTITY definitions
	// -------------------------------------------------------------------------

	// -------------------------------------------------------------------------
	// UNIQUE and PRIMARY KEY definitions
	// -------------------------------------------------------------------------

	public static final UniqueKey<AchievementsRecord> PK_ACHIEVEMENTS = UniqueKeys0.PK_ACHIEVEMENTS;
	public static final UniqueKey<ConnectionsRecord> PK_CONNECTIONS = UniqueKeys0.PK_CONNECTIONS;
	public static final UniqueKey<NormalAchievementRecord> PK_NORMALACHIEVEMENT = UniqueKeys0.PK_NORMALACHIEVEMENT;

	// -------------------------------------------------------------------------
	// FOREIGN KEY definitions
	// -------------------------------------------------------------------------

	// -------------------------------------------------------------------------
	// [#1459] distribute members to avoid static initialisers > 64kb
	// -------------------------------------------------------------------------

	private static class UniqueKeys0 {

		public static final UniqueKey<AchievementsRecord> PK_ACHIEVEMENTS = Internal.createUniqueKey(
				Achievements.ACHIEVEMENTS, "pk_achievements",
				new TableField[] { Achievements.ACHIEVEMENTS.PLAYERNAME, Achievements.ACHIEVEMENTS.ACHIEVEMENT }, true);
		public static final UniqueKey<ConnectionsRecord> PK_CONNECTIONS = Internal.createUniqueKey(Connections.CONNECTIONS,
				"pk_connections", new TableField[] { Connections.CONNECTIONS.PLAYERNAME }, true);
		public static final UniqueKey<NormalAchievementRecord> PK_NORMALACHIEVEMENT = Internal.createUniqueKey(
				NormalAchievement.NORMALACHIEVEMENT, "pk_normalachievement",
				new TableField[] { NormalAchievement.NORMALACHIEVEMENT.PLAYERNAME }, true);
	}
}
