/*
 * This file is generated by jOOQ.
 */
package com.hm.achievement.db;

import com.hm.achievement.db.tables.Achievements;
import com.hm.achievement.db.tables.Connections;
import com.hm.achievement.db.tables.NormalAchievement;

/**
 * Convenience access to all tables in
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

	/**
	 * The table <code>achievements</code>.
	 */
	public static final Achievements ACHIEVEMENTS = Achievements.ACHIEVEMENTS;

	/**
	 * The table <code>connections</code>.
	 */
	public static final Connections CONNECTIONS = Connections.CONNECTIONS;

	/**
	 * The table <code>consumedpotions</code>.
	 */
	public static final NormalAchievement NORMALACHIEVEMENT = NormalAchievement.NORMALACHIEVEMENT;
}
