/*
 * This file is generated by jOOQ.
 */
package com.hm.achievement.db;

import com.hm.achievement.db.tables.Achievements;
import com.hm.achievement.db.tables.Anvils;
import com.hm.achievement.db.tables.Arrows;
import com.hm.achievement.db.tables.Beds;
import com.hm.achievement.db.tables.Breaks;
import com.hm.achievement.db.tables.Breeding;
import com.hm.achievement.db.tables.Brewing;
import com.hm.achievement.db.tables.Connections;
import com.hm.achievement.db.tables.Consumedpotions;
import com.hm.achievement.db.tables.Crafts;
import com.hm.achievement.db.tables.Custom;
import com.hm.achievement.db.tables.Deaths;
import com.hm.achievement.db.tables.Distanceboat;
import com.hm.achievement.db.tables.Distancefoot;
import com.hm.achievement.db.tables.Distancegliding;
import com.hm.achievement.db.tables.Distancehorse;
import com.hm.achievement.db.tables.Distancellama;
import com.hm.achievement.db.tables.Distanceminecart;
import com.hm.achievement.db.tables.Distancepig;
import com.hm.achievement.db.tables.Drops;
import com.hm.achievement.db.tables.Eatenitems;
import com.hm.achievement.db.tables.Eggs;
import com.hm.achievement.db.tables.Enchantments;
import com.hm.achievement.db.tables.Enderpearls;
import com.hm.achievement.db.tables.Fertilising;
import com.hm.achievement.db.tables.Fireworks;
import com.hm.achievement.db.tables.Fish;
import com.hm.achievement.db.tables.Hoeplowing;
import com.hm.achievement.db.tables.Itembreaks;
import com.hm.achievement.db.tables.Kills;
import com.hm.achievement.db.tables.Lavabuckets;
import com.hm.achievement.db.tables.Levels;
import com.hm.achievement.db.tables.Milks;
import com.hm.achievement.db.tables.Musicdiscs;
import com.hm.achievement.db.tables.Petmastergive;
import com.hm.achievement.db.tables.Petmasterreceive;
import com.hm.achievement.db.tables.Pickups;
import com.hm.achievement.db.tables.Places;
import com.hm.achievement.db.tables.Playedtime;
import com.hm.achievement.db.tables.Playercommands;
import com.hm.achievement.db.tables.Shears;
import com.hm.achievement.db.tables.Smelting;
import com.hm.achievement.db.tables.Snowballs;
import com.hm.achievement.db.tables.Tames;
import com.hm.achievement.db.tables.Targetsshot;
import com.hm.achievement.db.tables.Trades;
import com.hm.achievement.db.tables.Treasures;
import com.hm.achievement.db.tables.Waterbuckets;

/**
 * Convenience access to all tables in
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

	/**
	 * The table <code>achievements</code>.
	 */
	public static final Achievements ACHIEVEMENTS = Achievements.ACHIEVEMENTS;

	/**
	 * The table <code>anvils</code>.
	 */
	public static final Anvils ANVILS = Anvils.ANVILS;

	/**
	 * The table <code>arrows</code>.
	 */
	public static final Arrows ARROWS = Arrows.ARROWS;

	/**
	 * The table <code>beds</code>.
	 */
	public static final Beds BEDS = Beds.BEDS;

	/**
	 * The table <code>breaks</code>.
	 */
	public static final Breaks BREAKS = Breaks.BREAKS;

	/**
	 * The table <code>breeding</code>.
	 */
	public static final Breeding BREEDING = Breeding.BREEDING;

	/**
	 * The table <code>brewing</code>.
	 */
	public static final Brewing BREWING = Brewing.BREWING;

	/**
	 * The table <code>connections</code>.
	 */
	public static final Connections CONNECTIONS = Connections.CONNECTIONS;

	/**
	 * The table <code>consumedpotions</code>.
	 */
	public static final Consumedpotions CONSUMEDPOTIONS = Consumedpotions.CONSUMEDPOTIONS;

	/**
	 * The table <code>crafts</code>.
	 */
	public static final Crafts CRAFTS = Crafts.CRAFTS;

	/**
	 * The table <code>custom</code>.
	 */
	public static final Custom CUSTOM = Custom.CUSTOM;

	/**
	 * The table <code>deaths</code>.
	 */
	public static final Deaths DEATHS = Deaths.DEATHS;

	/**
	 * The table <code>distanceboat</code>.
	 */
	public static final Distanceboat DISTANCEBOAT = Distanceboat.DISTANCEBOAT;

	/**
	 * The table <code>distancefoot</code>.
	 */
	public static final Distancefoot DISTANCEFOOT = Distancefoot.DISTANCEFOOT;

	/**
	 * The table <code>distancegliding</code>.
	 */
	public static final Distancegliding DISTANCEGLIDING = Distancegliding.DISTANCEGLIDING;

	/**
	 * The table <code>distancehorse</code>.
	 */
	public static final Distancehorse DISTANCEHORSE = Distancehorse.DISTANCEHORSE;

	/**
	 * The table <code>distancellama</code>.
	 */
	public static final Distancellama DISTANCELLAMA = Distancellama.DISTANCELLAMA;

	/**
	 * The table <code>distanceminecart</code>.
	 */
	public static final Distanceminecart DISTANCEMINECART = Distanceminecart.DISTANCEMINECART;

	/**
	 * The table <code>distancepig</code>.
	 */
	public static final Distancepig DISTANCEPIG = Distancepig.DISTANCEPIG;

	/**
	 * The table <code>drops</code>.
	 */
	public static final Drops DROPS = Drops.DROPS;

	/**
	 * The table <code>eatenitems</code>.
	 */
	public static final Eatenitems EATENITEMS = Eatenitems.EATENITEMS;

	/**
	 * The table <code>eggs</code>.
	 */
	public static final Eggs EGGS = Eggs.EGGS;

	/**
	 * The table <code>enchantments</code>.
	 */
	public static final Enchantments ENCHANTMENTS = Enchantments.ENCHANTMENTS;

	/**
	 * The table <code>enderpearls</code>.
	 */
	public static final Enderpearls ENDERPEARLS = Enderpearls.ENDERPEARLS;

	/**
	 * The table <code>fertilising</code>.
	 */
	public static final Fertilising FERTILISING = Fertilising.FERTILISING;

	/**
	 * The table <code>fireworks</code>.
	 */
	public static final Fireworks FIREWORKS = Fireworks.FIREWORKS;

	/**
	 * The table <code>fish</code>.
	 */
	public static final Fish FISH = Fish.FISH;

	/**
	 * The table <code>hoeplowing</code>.
	 */
	public static final Hoeplowing HOEPLOWING = Hoeplowing.HOEPLOWING;

	/**
	 * The table <code>itembreaks</code>.
	 */
	public static final Itembreaks ITEMBREAKS = Itembreaks.ITEMBREAKS;

	/**
	 * The table <code>kills</code>.
	 */
	public static final Kills KILLS = Kills.KILLS;

	/**
	 * The table <code>lavabuckets</code>.
	 */
	public static final Lavabuckets LAVABUCKETS = Lavabuckets.LAVABUCKETS;

	/**
	 * The table <code>levels</code>.
	 */
	public static final Levels LEVELS = Levels.LEVELS;

	/**
	 * The table <code>milks</code>.
	 */
	public static final Milks MILKS = Milks.MILKS;

	/**
	 * The table <code>musicdiscs</code>.
	 */
	public static final Musicdiscs MUSICDISCS = Musicdiscs.MUSICDISCS;

	/**
	 * The table <code>petmastergive</code>.
	 */
	public static final Petmastergive PETMASTERGIVE = Petmastergive.PETMASTERGIVE;

	/**
	 * The table <code>petmasterreceive</code>.
	 */
	public static final Petmasterreceive PETMASTERRECEIVE = Petmasterreceive.PETMASTERRECEIVE;

	/**
	 * The table <code>pickups</code>.
	 */
	public static final Pickups PICKUPS = Pickups.PICKUPS;

	/**
	 * The table <code>places</code>.
	 */
	public static final Places PLACES = Places.PLACES;

	/**
	 * The table <code>playedtime</code>.
	 */
	public static final Playedtime PLAYEDTIME = Playedtime.PLAYEDTIME;

	/**
	 * The table <code>playercommands</code>.
	 */
	public static final Playercommands PLAYERCOMMANDS = Playercommands.PLAYERCOMMANDS;

	/**
	 * The table <code>shears</code>.
	 */
	public static final Shears SHEARS = Shears.SHEARS;

	/**
	 * The table <code>smelting</code>.
	 */
	public static final Smelting SMELTING = Smelting.SMELTING;

	/**
	 * The table <code>snowballs</code>.
	 */
	public static final Snowballs SNOWBALLS = Snowballs.SNOWBALLS;

	/**
	 * The table <code>tames</code>.
	 */
	public static final Tames TAMES = Tames.TAMES;

	/**
	 * The table <code>targetsshot</code>.
	 */
	public static final Targetsshot TARGETSSHOT = Targetsshot.TARGETSSHOT;

	/**
	 * The table <code>trades</code>.
	 */
	public static final Trades TRADES = Trades.TRADES;

	/**
	 * The table <code>treasures</code>.
	 */
	public static final Treasures TREASURES = Treasures.TREASURES;

	/**
	 * The table <code>waterbuckets</code>.
	 */
	public static final Waterbuckets WATERBUCKETS = Waterbuckets.WATERBUCKETS;
}
