/*
 * This file is generated by jOOQ.
 */
package com.hm.achievement.db.tables;

import com.hm.achievement.db.DefaultSchema;
import com.hm.achievement.db.Keys;
import com.hm.achievement.db.tables.records.AnvilsRecord;

import java.util.Arrays;
import java.util.List;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Row2;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;

/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Anvils extends TableImpl<AnvilsRecord> {

	private static final long serialVersionUID = 262696474;

	/**
	 * The reference instance of <code>anvils</code>
	 */
	public static final Anvils ANVILS = new Anvils();

	/**
	 * The class holding records for this type
	 */
	@Override
	public Class<AnvilsRecord> getRecordType() {
		return AnvilsRecord.class;
	}

	/**
	 * The column <code>anvils.playername</code>.
	 */
	public final TableField<AnvilsRecord, String> PLAYERNAME = createField(DSL.name("playername"),
			org.jooq.impl.SQLDataType.CHAR(36), this, "");

	/**
	 * The column <code>anvils.anvils</code>.
	 */
	public final TableField<AnvilsRecord, Long> ANVILS_ = createField(DSL.name("anvils"), org.jooq.impl.SQLDataType.BIGINT,
			this, "");

	/**
	 * Create a <code>anvils</code> table reference
	 */
	public Anvils() {
		this(DSL.name("anvils"), null);
	}

	/**
	 * Create an aliased <code>anvils</code> table reference
	 */
	public Anvils(String alias) {
		this(DSL.name(alias), ANVILS);
	}

	/**
	 * Create an aliased <code>anvils</code> table reference
	 */
	public Anvils(Name alias) {
		this(alias, ANVILS);
	}

	private Anvils(Name alias, Table<AnvilsRecord> aliased) {
		this(alias, aliased, null);
	}

	private Anvils(Name alias, Table<AnvilsRecord> aliased, Field<?>[] parameters) {
		super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
	}

	public <O extends Record> Anvils(Table<O> child, ForeignKey<O, AnvilsRecord> key) {
		super(child, key, ANVILS);
	}

	@Override
	public Schema getSchema() {
		return DefaultSchema.DEFAULT_SCHEMA;
	}

	@Override
	public UniqueKey<AnvilsRecord> getPrimaryKey() {
		return Keys.PK_ANVILS;
	}

	@Override
	public List<UniqueKey<AnvilsRecord>> getKeys() {
		return Arrays.<UniqueKey<AnvilsRecord>> asList(Keys.PK_ANVILS);
	}

	@Override
	public Anvils as(String alias) {
		return new Anvils(DSL.name(alias), this);
	}

	@Override
	public Anvils as(Name alias) {
		return new Anvils(alias, this);
	}

	/**
	 * Rename this table
	 */
	@Override
	public Anvils rename(String name) {
		return new Anvils(DSL.name(name), null);
	}

	/**
	 * Rename this table
	 */
	@Override
	public Anvils rename(Name name) {
		return new Anvils(name, null);
	}

	// -------------------------------------------------------------------------
	// Row2 type methods
	// -------------------------------------------------------------------------

	@Override
	public Row2<String, Long> fieldsRow() {
		return (Row2) super.fieldsRow();
	}
}
