/*
 * This file is generated by jOOQ.
 */
package com.hm.achievement.db.tables;

import com.hm.achievement.db.DefaultSchema;
import com.hm.achievement.db.Keys;
import com.hm.achievement.db.tables.records.ArrowsRecord;

import java.util.Arrays;
import java.util.List;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Row2;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;

/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Arrows extends TableImpl<ArrowsRecord> {

	private static final long serialVersionUID = -984540521;

	/**
	 * The reference instance of <code>arrows</code>
	 */
	public static final Arrows ARROWS = new Arrows();

	/**
	 * The class holding records for this type
	 */
	@Override
	public Class<ArrowsRecord> getRecordType() {
		return ArrowsRecord.class;
	}

	/**
	 * The column <code>arrows.playername</code>.
	 */
	public final TableField<ArrowsRecord, String> PLAYERNAME = createField(DSL.name("playername"),
			org.jooq.impl.SQLDataType.CHAR(36), this, "");

	/**
	 * The column <code>arrows.arrows</code>.
	 */
	public final TableField<ArrowsRecord, Long> ARROWS_ = createField(DSL.name("arrows"), org.jooq.impl.SQLDataType.BIGINT,
			this, "");

	/**
	 * Create a <code>arrows</code> table reference
	 */
	public Arrows() {
		this(DSL.name("arrows"), null);
	}

	/**
	 * Create an aliased <code>arrows</code> table reference
	 */
	public Arrows(String alias) {
		this(DSL.name(alias), ARROWS);
	}

	/**
	 * Create an aliased <code>arrows</code> table reference
	 */
	public Arrows(Name alias) {
		this(alias, ARROWS);
	}

	private Arrows(Name alias, Table<ArrowsRecord> aliased) {
		this(alias, aliased, null);
	}

	private Arrows(Name alias, Table<ArrowsRecord> aliased, Field<?>[] parameters) {
		super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
	}

	public <O extends Record> Arrows(Table<O> child, ForeignKey<O, ArrowsRecord> key) {
		super(child, key, ARROWS);
	}

	@Override
	public Schema getSchema() {
		return DefaultSchema.DEFAULT_SCHEMA;
	}

	@Override
	public UniqueKey<ArrowsRecord> getPrimaryKey() {
		return Keys.PK_ARROWS;
	}

	@Override
	public List<UniqueKey<ArrowsRecord>> getKeys() {
		return Arrays.<UniqueKey<ArrowsRecord>> asList(Keys.PK_ARROWS);
	}

	@Override
	public Arrows as(String alias) {
		return new Arrows(DSL.name(alias), this);
	}

	@Override
	public Arrows as(Name alias) {
		return new Arrows(alias, this);
	}

	/**
	 * Rename this table
	 */
	@Override
	public Arrows rename(String name) {
		return new Arrows(DSL.name(name), null);
	}

	/**
	 * Rename this table
	 */
	@Override
	public Arrows rename(Name name) {
		return new Arrows(name, null);
	}

	// -------------------------------------------------------------------------
	// Row2 type methods
	// -------------------------------------------------------------------------

	@Override
	public Row2<String, Long> fieldsRow() {
		return (Row2) super.fieldsRow();
	}
}
