/*
 * This file is generated by jOOQ.
 */
package com.hm.achievement.db.tables;

import com.hm.achievement.db.DefaultSchema;
import com.hm.achievement.db.Keys;
import com.hm.achievement.db.tables.records.BedsRecord;

import java.util.Arrays;
import java.util.List;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Row2;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;

/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Beds extends TableImpl<BedsRecord> {

	private static final long serialVersionUID = 767629455;

	/**
	 * The reference instance of <code>beds</code>
	 */
	public static final Beds BEDS = new Beds();

	/**
	 * The class holding records for this type
	 */
	@Override
	public Class<BedsRecord> getRecordType() {
		return BedsRecord.class;
	}

	/**
	 * The column <code>beds.playername</code>.
	 */
	public final TableField<BedsRecord, String> PLAYERNAME = createField(DSL.name("playername"),
			org.jooq.impl.SQLDataType.CHAR(36), this, "");

	/**
	 * The column <code>beds.beds</code>.
	 */
	public final TableField<BedsRecord, Long> BEDS_ = createField(DSL.name("beds"), org.jooq.impl.SQLDataType.BIGINT, this,
			"");

	/**
	 * Create a <code>beds</code> table reference
	 */
	public Beds() {
		this(DSL.name("beds"), null);
	}

	/**
	 * Create an aliased <code>beds</code> table reference
	 */
	public Beds(String alias) {
		this(DSL.name(alias), BEDS);
	}

	/**
	 * Create an aliased <code>beds</code> table reference
	 */
	public Beds(Name alias) {
		this(alias, BEDS);
	}

	private Beds(Name alias, Table<BedsRecord> aliased) {
		this(alias, aliased, null);
	}

	private Beds(Name alias, Table<BedsRecord> aliased, Field<?>[] parameters) {
		super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
	}

	public <O extends Record> Beds(Table<O> child, ForeignKey<O, BedsRecord> key) {
		super(child, key, BEDS);
	}

	@Override
	public Schema getSchema() {
		return DefaultSchema.DEFAULT_SCHEMA;
	}

	@Override
	public UniqueKey<BedsRecord> getPrimaryKey() {
		return Keys.PK_BEDS;
	}

	@Override
	public List<UniqueKey<BedsRecord>> getKeys() {
		return Arrays.<UniqueKey<BedsRecord>> asList(Keys.PK_BEDS);
	}

	@Override
	public Beds as(String alias) {
		return new Beds(DSL.name(alias), this);
	}

	@Override
	public Beds as(Name alias) {
		return new Beds(alias, this);
	}

	/**
	 * Rename this table
	 */
	@Override
	public Beds rename(String name) {
		return new Beds(DSL.name(name), null);
	}

	/**
	 * Rename this table
	 */
	@Override
	public Beds rename(Name name) {
		return new Beds(name, null);
	}

	// -------------------------------------------------------------------------
	// Row2 type methods
	// -------------------------------------------------------------------------

	@Override
	public Row2<String, Long> fieldsRow() {
		return (Row2) super.fieldsRow();
	}
}
