/*
 * This file is generated by jOOQ.
 */
package com.hm.achievement.db.tables;

import com.hm.achievement.db.DefaultSchema;
import com.hm.achievement.db.Keys;
import com.hm.achievement.db.tables.records.BreaksRecord;

import java.util.Arrays;
import java.util.List;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Row3;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;

/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Breaks extends TableImpl<BreaksRecord> {

	private static final long serialVersionUID = -1937676276;

	/**
	 * The reference instance of <code>breaks</code>
	 */
	public static final Breaks BREAKS = new Breaks();

	/**
	 * The class holding records for this type
	 */
	@Override
	public Class<BreaksRecord> getRecordType() {
		return BreaksRecord.class;
	}

	/**
	 * The column <code>breaks.playername</code>.
	 */
	public final TableField<BreaksRecord, String> PLAYERNAME = createField(DSL.name("playername"),
			org.jooq.impl.SQLDataType.CHAR(36), this, "");

	/**
	 * The column <code>breaks.blockid</code>.
	 */
	public final TableField<BreaksRecord, String> BLOCKID = createField(DSL.name("blockid"),
			org.jooq.impl.SQLDataType.VARCHAR(191), this, "");

	/**
	 * The column <code>breaks.breaks</code>.
	 */
	public final TableField<BreaksRecord, Integer> BREAKS_ = createField(DSL.name("breaks"),
			org.jooq.impl.SQLDataType.INTEGER, this, "");

	/**
	 * Create a <code>breaks</code> table reference
	 */
	public Breaks() {
		this(DSL.name("breaks"), null);
	}

	/**
	 * Create an aliased <code>breaks</code> table reference
	 */
	public Breaks(String alias) {
		this(DSL.name(alias), BREAKS);
	}

	/**
	 * Create an aliased <code>breaks</code> table reference
	 */
	public Breaks(Name alias) {
		this(alias, BREAKS);
	}

	private Breaks(Name alias, Table<BreaksRecord> aliased) {
		this(alias, aliased, null);
	}

	private Breaks(Name alias, Table<BreaksRecord> aliased, Field<?>[] parameters) {
		super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
	}

	public <O extends Record> Breaks(Table<O> child, ForeignKey<O, BreaksRecord> key) {
		super(child, key, BREAKS);
	}

	@Override
	public Schema getSchema() {
		return DefaultSchema.DEFAULT_SCHEMA;
	}

	@Override
	public UniqueKey<BreaksRecord> getPrimaryKey() {
		return Keys.PK_BREAKS;
	}

	@Override
	public List<UniqueKey<BreaksRecord>> getKeys() {
		return Arrays.<UniqueKey<BreaksRecord>> asList(Keys.PK_BREAKS);
	}

	@Override
	public Breaks as(String alias) {
		return new Breaks(DSL.name(alias), this);
	}

	@Override
	public Breaks as(Name alias) {
		return new Breaks(alias, this);
	}

	/**
	 * Rename this table
	 */
	@Override
	public Breaks rename(String name) {
		return new Breaks(DSL.name(name), null);
	}

	/**
	 * Rename this table
	 */
	@Override
	public Breaks rename(Name name) {
		return new Breaks(name, null);
	}

	// -------------------------------------------------------------------------
	// Row3 type methods
	// -------------------------------------------------------------------------

	@Override
	public Row3<String, String, Integer> fieldsRow() {
		return (Row3) super.fieldsRow();
	}
}
