/*
 * This file is generated by jOOQ.
 */
package com.hm.achievement.db.tables;

import com.hm.achievement.db.DefaultSchema;
import com.hm.achievement.db.Keys;
import com.hm.achievement.db.tables.records.BreedingRecord;

import java.util.Arrays;
import java.util.List;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Row3;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;

/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Breeding extends TableImpl<BreedingRecord> {

	private static final long serialVersionUID = -522343769;

	/**
	 * The reference instance of <code>breeding</code>
	 */
	public static final Breeding BREEDING = new Breeding();

	/**
	 * The class holding records for this type
	 */
	@Override
	public Class<BreedingRecord> getRecordType() {
		return BreedingRecord.class;
	}

	/**
	 * The column <code>breeding.playername</code>.
	 */
	public final TableField<BreedingRecord, String> PLAYERNAME = createField(DSL.name("playername"),
			org.jooq.impl.SQLDataType.CHAR(36), this, "");

	/**
	 * The column <code>breeding.mobname</code>.
	 */
	public final TableField<BreedingRecord, String> MOBNAME = createField(DSL.name("mobname"),
			org.jooq.impl.SQLDataType.VARCHAR(191), this, "");

	/**
	 * The column <code>breeding.breeding</code>.
	 */
	public final TableField<BreedingRecord, Integer> BREEDING_ = createField(DSL.name("breeding"),
			org.jooq.impl.SQLDataType.INTEGER, this, "");

	/**
	 * Create a <code>breeding</code> table reference
	 */
	public Breeding() {
		this(DSL.name("breeding"), null);
	}

	/**
	 * Create an aliased <code>breeding</code> table reference
	 */
	public Breeding(String alias) {
		this(DSL.name(alias), BREEDING);
	}

	/**
	 * Create an aliased <code>breeding</code> table reference
	 */
	public Breeding(Name alias) {
		this(alias, BREEDING);
	}

	private Breeding(Name alias, Table<BreedingRecord> aliased) {
		this(alias, aliased, null);
	}

	private Breeding(Name alias, Table<BreedingRecord> aliased, Field<?>[] parameters) {
		super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
	}

	public <O extends Record> Breeding(Table<O> child, ForeignKey<O, BreedingRecord> key) {
		super(child, key, BREEDING);
	}

	@Override
	public Schema getSchema() {
		return DefaultSchema.DEFAULT_SCHEMA;
	}

	@Override
	public UniqueKey<BreedingRecord> getPrimaryKey() {
		return Keys.PK_BREEDING;
	}

	@Override
	public List<UniqueKey<BreedingRecord>> getKeys() {
		return Arrays.<UniqueKey<BreedingRecord>> asList(Keys.PK_BREEDING);
	}

	@Override
	public Breeding as(String alias) {
		return new Breeding(DSL.name(alias), this);
	}

	@Override
	public Breeding as(Name alias) {
		return new Breeding(alias, this);
	}

	/**
	 * Rename this table
	 */
	@Override
	public Breeding rename(String name) {
		return new Breeding(DSL.name(name), null);
	}

	/**
	 * Rename this table
	 */
	@Override
	public Breeding rename(Name name) {
		return new Breeding(name, null);
	}

	// -------------------------------------------------------------------------
	// Row3 type methods
	// -------------------------------------------------------------------------

	@Override
	public Row3<String, String, Integer> fieldsRow() {
		return (Row3) super.fieldsRow();
	}
}
