/*
 * This file is generated by jOOQ.
 */
package com.hm.achievement.db.tables;

import com.hm.achievement.db.DefaultSchema;
import com.hm.achievement.db.Keys;
import com.hm.achievement.db.tables.records.BrewingRecord;

import java.util.Arrays;
import java.util.List;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Row2;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;

/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Brewing extends TableImpl<BrewingRecord> {

	private static final long serialVersionUID = 961352133;

	/**
	 * The reference instance of <code>brewing</code>
	 */
	public static final Brewing BREWING = new Brewing();

	/**
	 * The class holding records for this type
	 */
	@Override
	public Class<BrewingRecord> getRecordType() {
		return BrewingRecord.class;
	}

	/**
	 * The column <code>brewing.playername</code>.
	 */
	public final TableField<BrewingRecord, String> PLAYERNAME = createField(DSL.name("playername"),
			org.jooq.impl.SQLDataType.CHAR(36), this, "");

	/**
	 * The column <code>brewing.brewing</code>.
	 */
	public final TableField<BrewingRecord, Long> BREWING_ = createField(DSL.name("brewing"),
			org.jooq.impl.SQLDataType.BIGINT, this, "");

	/**
	 * Create a <code>brewing</code> table reference
	 */
	public Brewing() {
		this(DSL.name("brewing"), null);
	}

	/**
	 * Create an aliased <code>brewing</code> table reference
	 */
	public Brewing(String alias) {
		this(DSL.name(alias), BREWING);
	}

	/**
	 * Create an aliased <code>brewing</code> table reference
	 */
	public Brewing(Name alias) {
		this(alias, BREWING);
	}

	private Brewing(Name alias, Table<BrewingRecord> aliased) {
		this(alias, aliased, null);
	}

	private Brewing(Name alias, Table<BrewingRecord> aliased, Field<?>[] parameters) {
		super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
	}

	public <O extends Record> Brewing(Table<O> child, ForeignKey<O, BrewingRecord> key) {
		super(child, key, BREWING);
	}

	@Override
	public Schema getSchema() {
		return DefaultSchema.DEFAULT_SCHEMA;
	}

	@Override
	public UniqueKey<BrewingRecord> getPrimaryKey() {
		return Keys.PK_BREWING;
	}

	@Override
	public List<UniqueKey<BrewingRecord>> getKeys() {
		return Arrays.<UniqueKey<BrewingRecord>> asList(Keys.PK_BREWING);
	}

	@Override
	public Brewing as(String alias) {
		return new Brewing(DSL.name(alias), this);
	}

	@Override
	public Brewing as(Name alias) {
		return new Brewing(alias, this);
	}

	/**
	 * Rename this table
	 */
	@Override
	public Brewing rename(String name) {
		return new Brewing(DSL.name(name), null);
	}

	/**
	 * Rename this table
	 */
	@Override
	public Brewing rename(Name name) {
		return new Brewing(name, null);
	}

	// -------------------------------------------------------------------------
	// Row2 type methods
	// -------------------------------------------------------------------------

	@Override
	public Row2<String, Long> fieldsRow() {
		return (Row2) super.fieldsRow();
	}
}
