/*
 * This file is generated by jOOQ.
 */
package com.hm.achievement.db.tables;

import com.hm.achievement.db.DefaultSchema;
import com.hm.achievement.db.Keys;
import com.hm.achievement.db.tables.records.ConsumedpotionsRecord;

import java.util.Arrays;
import java.util.List;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Row2;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;

/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Consumedpotions extends TableImpl<ConsumedpotionsRecord> {

	private static final long serialVersionUID = -383753491;

	/**
	 * The reference instance of <code>consumedpotions</code>
	 */
	public static final Consumedpotions CONSUMEDPOTIONS = new Consumedpotions();

	/**
	 * The class holding records for this type
	 */
	@Override
	public Class<ConsumedpotionsRecord> getRecordType() {
		return ConsumedpotionsRecord.class;
	}

	/**
	 * The column <code>consumedpotions.playername</code>.
	 */
	public final TableField<ConsumedpotionsRecord, String> PLAYERNAME = createField(DSL.name("playername"),
			org.jooq.impl.SQLDataType.CHAR(36), this, "");

	/**
	 * The column <code>consumedpotions.consumedpotions</code>.
	 */
	public final TableField<ConsumedpotionsRecord, Long> CONSUMEDPOTIONS_ = createField(DSL.name("consumedpotions"),
			org.jooq.impl.SQLDataType.BIGINT, this, "");

	/**
	 * Create a <code>consumedpotions</code> table reference
	 */
	public Consumedpotions() {
		this(DSL.name("consumedpotions"), null);
	}

	/**
	 * Create an aliased <code>consumedpotions</code> table reference
	 */
	public Consumedpotions(String alias) {
		this(DSL.name(alias), CONSUMEDPOTIONS);
	}

	/**
	 * Create an aliased <code>consumedpotions</code> table reference
	 */
	public Consumedpotions(Name alias) {
		this(alias, CONSUMEDPOTIONS);
	}

	private Consumedpotions(Name alias, Table<ConsumedpotionsRecord> aliased) {
		this(alias, aliased, null);
	}

	private Consumedpotions(Name alias, Table<ConsumedpotionsRecord> aliased, Field<?>[] parameters) {
		super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
	}

	public <O extends Record> Consumedpotions(Table<O> child, ForeignKey<O, ConsumedpotionsRecord> key) {
		super(child, key, CONSUMEDPOTIONS);
	}

	@Override
	public Schema getSchema() {
		return DefaultSchema.DEFAULT_SCHEMA;
	}

	@Override
	public UniqueKey<ConsumedpotionsRecord> getPrimaryKey() {
		return Keys.PK_CONSUMEDPOTIONS;
	}

	@Override
	public List<UniqueKey<ConsumedpotionsRecord>> getKeys() {
		return Arrays.<UniqueKey<ConsumedpotionsRecord>> asList(Keys.PK_CONSUMEDPOTIONS);
	}

	@Override
	public Consumedpotions as(String alias) {
		return new Consumedpotions(DSL.name(alias), this);
	}

	@Override
	public Consumedpotions as(Name alias) {
		return new Consumedpotions(alias, this);
	}

	/**
	 * Rename this table
	 */
	@Override
	public Consumedpotions rename(String name) {
		return new Consumedpotions(DSL.name(name), null);
	}

	/**
	 * Rename this table
	 */
	@Override
	public Consumedpotions rename(Name name) {
		return new Consumedpotions(name, null);
	}

	// -------------------------------------------------------------------------
	// Row2 type methods
	// -------------------------------------------------------------------------

	@Override
	public Row2<String, Long> fieldsRow() {
		return (Row2) super.fieldsRow();
	}
}
