/*
 * This file is generated by jOOQ.
 */
package com.hm.achievement.db.tables;

import com.hm.achievement.db.DefaultSchema;
import com.hm.achievement.db.Keys;
import com.hm.achievement.db.tables.records.CraftsRecord;

import java.util.Arrays;
import java.util.List;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Row3;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;

/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Crafts extends TableImpl<CraftsRecord> {

	private static final long serialVersionUID = -1449350818;

	/**
	 * The reference instance of <code>crafts</code>
	 */
	public static final Crafts CRAFTS = new Crafts();

	/**
	 * The class holding records for this type
	 */
	@Override
	public Class<CraftsRecord> getRecordType() {
		return CraftsRecord.class;
	}

	/**
	 * The column <code>crafts.playername</code>.
	 */
	public final TableField<CraftsRecord, String> PLAYERNAME = createField(DSL.name("playername"),
			org.jooq.impl.SQLDataType.CHAR(36), this, "");

	/**
	 * The column <code>crafts.item</code>.
	 */
	public final TableField<CraftsRecord, String> ITEM = createField(DSL.name("item"),
			org.jooq.impl.SQLDataType.VARCHAR(191), this, "");

	/**
	 * The column <code>crafts.crafts</code>.
	 */
	public final TableField<CraftsRecord, Integer> CRAFTS_ = createField(DSL.name("crafts"),
			org.jooq.impl.SQLDataType.INTEGER, this, "");

	/**
	 * Create a <code>crafts</code> table reference
	 */
	public Crafts() {
		this(DSL.name("crafts"), null);
	}

	/**
	 * Create an aliased <code>crafts</code> table reference
	 */
	public Crafts(String alias) {
		this(DSL.name(alias), CRAFTS);
	}

	/**
	 * Create an aliased <code>crafts</code> table reference
	 */
	public Crafts(Name alias) {
		this(alias, CRAFTS);
	}

	private Crafts(Name alias, Table<CraftsRecord> aliased) {
		this(alias, aliased, null);
	}

	private Crafts(Name alias, Table<CraftsRecord> aliased, Field<?>[] parameters) {
		super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
	}

	public <O extends Record> Crafts(Table<O> child, ForeignKey<O, CraftsRecord> key) {
		super(child, key, CRAFTS);
	}

	@Override
	public Schema getSchema() {
		return DefaultSchema.DEFAULT_SCHEMA;
	}

	@Override
	public UniqueKey<CraftsRecord> getPrimaryKey() {
		return Keys.PK_CRAFTS;
	}

	@Override
	public List<UniqueKey<CraftsRecord>> getKeys() {
		return Arrays.<UniqueKey<CraftsRecord>> asList(Keys.PK_CRAFTS);
	}

	@Override
	public Crafts as(String alias) {
		return new Crafts(DSL.name(alias), this);
	}

	@Override
	public Crafts as(Name alias) {
		return new Crafts(alias, this);
	}

	/**
	 * Rename this table
	 */
	@Override
	public Crafts rename(String name) {
		return new Crafts(DSL.name(name), null);
	}

	/**
	 * Rename this table
	 */
	@Override
	public Crafts rename(Name name) {
		return new Crafts(name, null);
	}

	// -------------------------------------------------------------------------
	// Row3 type methods
	// -------------------------------------------------------------------------

	@Override
	public Row3<String, String, Integer> fieldsRow() {
		return (Row3) super.fieldsRow();
	}
}
