/*
 * This file is generated by jOOQ.
 */
package com.hm.achievement.db.tables;

import com.hm.achievement.db.DefaultSchema;
import com.hm.achievement.db.Keys;
import com.hm.achievement.db.tables.records.CustomRecord;

import java.util.Arrays;
import java.util.List;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Row3;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;

/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Custom extends TableImpl<CustomRecord> {

	private static final long serialVersionUID = -1504877235;

	/**
	 * The reference instance of <code>custom</code>
	 */
	public static final Custom CUSTOM = new Custom();

	/**
	 * The class holding records for this type
	 */
	@Override
	public Class<CustomRecord> getRecordType() {
		return CustomRecord.class;
	}

	/**
	 * The column <code>custom.playername</code>.
	 */
	public final TableField<CustomRecord, String> PLAYERNAME = createField(DSL.name("playername"),
			org.jooq.impl.SQLDataType.CHAR(36), this, "");

	/**
	 * The column <code>custom.customname</code>.
	 */
	public final TableField<CustomRecord, String> CUSTOMNAME = createField(DSL.name("customname"),
			org.jooq.impl.SQLDataType.VARCHAR(191), this, "");

	/**
	 * The column <code>custom.custom</code>.
	 */
	public final TableField<CustomRecord, Integer> CUSTOM_ = createField(DSL.name("custom"),
			org.jooq.impl.SQLDataType.INTEGER, this, "");

	/**
	 * Create a <code>custom</code> table reference
	 */
	public Custom() {
		this(DSL.name("custom"), null);
	}

	/**
	 * Create an aliased <code>custom</code> table reference
	 */
	public Custom(String alias) {
		this(DSL.name(alias), CUSTOM);
	}

	/**
	 * Create an aliased <code>custom</code> table reference
	 */
	public Custom(Name alias) {
		this(alias, CUSTOM);
	}

	private Custom(Name alias, Table<CustomRecord> aliased) {
		this(alias, aliased, null);
	}

	private Custom(Name alias, Table<CustomRecord> aliased, Field<?>[] parameters) {
		super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
	}

	public <O extends Record> Custom(Table<O> child, ForeignKey<O, CustomRecord> key) {
		super(child, key, CUSTOM);
	}

	@Override
	public Schema getSchema() {
		return DefaultSchema.DEFAULT_SCHEMA;
	}

	@Override
	public UniqueKey<CustomRecord> getPrimaryKey() {
		return Keys.PK_CUSTOM;
	}

	@Override
	public List<UniqueKey<CustomRecord>> getKeys() {
		return Arrays.<UniqueKey<CustomRecord>> asList(Keys.PK_CUSTOM);
	}

	@Override
	public Custom as(String alias) {
		return new Custom(DSL.name(alias), this);
	}

	@Override
	public Custom as(Name alias) {
		return new Custom(alias, this);
	}

	/**
	 * Rename this table
	 */
	@Override
	public Custom rename(String name) {
		return new Custom(DSL.name(name), null);
	}

	/**
	 * Rename this table
	 */
	@Override
	public Custom rename(Name name) {
		return new Custom(name, null);
	}

	// -------------------------------------------------------------------------
	// Row3 type methods
	// -------------------------------------------------------------------------

	@Override
	public Row3<String, String, Integer> fieldsRow() {
		return (Row3) super.fieldsRow();
	}
}
