/*
 * This file is generated by jOOQ.
 */
package com.hm.achievement.db.tables;

import com.hm.achievement.db.DefaultSchema;
import com.hm.achievement.db.Keys;
import com.hm.achievement.db.tables.records.DeathsRecord;

import java.util.Arrays;
import java.util.List;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Row2;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;

/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Deaths extends TableImpl<DeathsRecord> {

	private static final long serialVersionUID = 1904150978;

	/**
	 * The reference instance of <code>deaths</code>
	 */
	public static final Deaths DEATHS = new Deaths();

	/**
	 * The class holding records for this type
	 */
	@Override
	public Class<DeathsRecord> getRecordType() {
		return DeathsRecord.class;
	}

	/**
	 * The column <code>deaths.playername</code>.
	 */
	public final TableField<DeathsRecord, String> PLAYERNAME = createField(DSL.name("playername"),
			org.jooq.impl.SQLDataType.CHAR(36), this, "");

	/**
	 * The column <code>deaths.deaths</code>.
	 */
	public final TableField<DeathsRecord, Long> DEATHS_ = createField(DSL.name("deaths"), org.jooq.impl.SQLDataType.BIGINT,
			this, "");

	/**
	 * Create a <code>deaths</code> table reference
	 */
	public Deaths() {
		this(DSL.name("deaths"), null);
	}

	/**
	 * Create an aliased <code>deaths</code> table reference
	 */
	public Deaths(String alias) {
		this(DSL.name(alias), DEATHS);
	}

	/**
	 * Create an aliased <code>deaths</code> table reference
	 */
	public Deaths(Name alias) {
		this(alias, DEATHS);
	}

	private Deaths(Name alias, Table<DeathsRecord> aliased) {
		this(alias, aliased, null);
	}

	private Deaths(Name alias, Table<DeathsRecord> aliased, Field<?>[] parameters) {
		super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
	}

	public <O extends Record> Deaths(Table<O> child, ForeignKey<O, DeathsRecord> key) {
		super(child, key, DEATHS);
	}

	@Override
	public Schema getSchema() {
		return DefaultSchema.DEFAULT_SCHEMA;
	}

	@Override
	public UniqueKey<DeathsRecord> getPrimaryKey() {
		return Keys.PK_DEATHS;
	}

	@Override
	public List<UniqueKey<DeathsRecord>> getKeys() {
		return Arrays.<UniqueKey<DeathsRecord>> asList(Keys.PK_DEATHS);
	}

	@Override
	public Deaths as(String alias) {
		return new Deaths(DSL.name(alias), this);
	}

	@Override
	public Deaths as(Name alias) {
		return new Deaths(alias, this);
	}

	/**
	 * Rename this table
	 */
	@Override
	public Deaths rename(String name) {
		return new Deaths(DSL.name(name), null);
	}

	/**
	 * Rename this table
	 */
	@Override
	public Deaths rename(Name name) {
		return new Deaths(name, null);
	}

	// -------------------------------------------------------------------------
	// Row2 type methods
	// -------------------------------------------------------------------------

	@Override
	public Row2<String, Long> fieldsRow() {
		return (Row2) super.fieldsRow();
	}
}
