/*
 * This file is generated by jOOQ.
 */
package com.hm.achievement.db.tables;

import com.hm.achievement.db.DefaultSchema;
import com.hm.achievement.db.Keys;
import com.hm.achievement.db.tables.records.DistanceglidingRecord;

import java.util.Arrays;
import java.util.List;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Row2;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;

/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Distancegliding extends TableImpl<DistanceglidingRecord> {

	private static final long serialVersionUID = 1846095084;

	/**
	 * The reference instance of <code>distancegliding</code>
	 */
	public static final Distancegliding DISTANCEGLIDING = new Distancegliding();

	/**
	 * The class holding records for this type
	 */
	@Override
	public Class<DistanceglidingRecord> getRecordType() {
		return DistanceglidingRecord.class;
	}

	/**
	 * The column <code>distancegliding.playername</code>.
	 */
	public final TableField<DistanceglidingRecord, String> PLAYERNAME = createField(DSL.name("playername"),
			org.jooq.impl.SQLDataType.CHAR(36), this, "");

	/**
	 * The column <code>distancegliding.distancegliding</code>.
	 */
	public final TableField<DistanceglidingRecord, Long> DISTANCEGLIDING_ = createField(DSL.name("distancegliding"),
			org.jooq.impl.SQLDataType.BIGINT, this, "");

	/**
	 * Create a <code>distancegliding</code> table reference
	 */
	public Distancegliding() {
		this(DSL.name("distancegliding"), null);
	}

	/**
	 * Create an aliased <code>distancegliding</code> table reference
	 */
	public Distancegliding(String alias) {
		this(DSL.name(alias), DISTANCEGLIDING);
	}

	/**
	 * Create an aliased <code>distancegliding</code> table reference
	 */
	public Distancegliding(Name alias) {
		this(alias, DISTANCEGLIDING);
	}

	private Distancegliding(Name alias, Table<DistanceglidingRecord> aliased) {
		this(alias, aliased, null);
	}

	private Distancegliding(Name alias, Table<DistanceglidingRecord> aliased, Field<?>[] parameters) {
		super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
	}

	public <O extends Record> Distancegliding(Table<O> child, ForeignKey<O, DistanceglidingRecord> key) {
		super(child, key, DISTANCEGLIDING);
	}

	@Override
	public Schema getSchema() {
		return DefaultSchema.DEFAULT_SCHEMA;
	}

	@Override
	public UniqueKey<DistanceglidingRecord> getPrimaryKey() {
		return Keys.PK_DISTANCEGLIDING;
	}

	@Override
	public List<UniqueKey<DistanceglidingRecord>> getKeys() {
		return Arrays.<UniqueKey<DistanceglidingRecord>> asList(Keys.PK_DISTANCEGLIDING);
	}

	@Override
	public Distancegliding as(String alias) {
		return new Distancegliding(DSL.name(alias), this);
	}

	@Override
	public Distancegliding as(Name alias) {
		return new Distancegliding(alias, this);
	}

	/**
	 * Rename this table
	 */
	@Override
	public Distancegliding rename(String name) {
		return new Distancegliding(DSL.name(name), null);
	}

	/**
	 * Rename this table
	 */
	@Override
	public Distancegliding rename(Name name) {
		return new Distancegliding(name, null);
	}

	// -------------------------------------------------------------------------
	// Row2 type methods
	// -------------------------------------------------------------------------

	@Override
	public Row2<String, Long> fieldsRow() {
		return (Row2) super.fieldsRow();
	}
}
