/*
 * This file is generated by jOOQ.
 */
package com.hm.achievement.db.tables;

import com.hm.achievement.db.DefaultSchema;
import com.hm.achievement.db.Keys;
import com.hm.achievement.db.tables.records.DistanceboatRecord;

import java.util.Arrays;
import java.util.List;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Row2;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;

/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Distanceboat extends TableImpl<DistanceboatRecord> {

	private static final long serialVersionUID = -1546268084;

	/**
	 * The reference instance of <code>distanceboat</code>
	 */
	public static final Distanceboat DISTANCEBOAT = new Distanceboat();

	/**
	 * The class holding records for this type
	 */
	@Override
	public Class<DistanceboatRecord> getRecordType() {
		return DistanceboatRecord.class;
	}

	/**
	 * The column <code>distanceboat.playername</code>.
	 */
	public final TableField<DistanceboatRecord, String> PLAYERNAME = createField(DSL.name("playername"),
			org.jooq.impl.SQLDataType.CHAR(36), this, "");

	/**
	 * The column <code>distanceboat.distanceboat</code>.
	 */
	public final TableField<DistanceboatRecord, Long> DISTANCEBOAT_ = createField(DSL.name("distanceboat"),
			org.jooq.impl.SQLDataType.BIGINT, this, "");

	/**
	 * Create a <code>distanceboat</code> table reference
	 */
	public Distanceboat() {
		this(DSL.name("distanceboat"), null);
	}

	/**
	 * Create an aliased <code>distanceboat</code> table reference
	 */
	public Distanceboat(String alias) {
		this(DSL.name(alias), DISTANCEBOAT);
	}

	/**
	 * Create an aliased <code>distanceboat</code> table reference
	 */
	public Distanceboat(Name alias) {
		this(alias, DISTANCEBOAT);
	}

	private Distanceboat(Name alias, Table<DistanceboatRecord> aliased) {
		this(alias, aliased, null);
	}

	private Distanceboat(Name alias, Table<DistanceboatRecord> aliased, Field<?>[] parameters) {
		super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
	}

	public <O extends Record> Distanceboat(Table<O> child, ForeignKey<O, DistanceboatRecord> key) {
		super(child, key, DISTANCEBOAT);
	}

	@Override
	public Schema getSchema() {
		return DefaultSchema.DEFAULT_SCHEMA;
	}

	@Override
	public UniqueKey<DistanceboatRecord> getPrimaryKey() {
		return Keys.PK_DISTANCEBOAT;
	}

	@Override
	public List<UniqueKey<DistanceboatRecord>> getKeys() {
		return Arrays.<UniqueKey<DistanceboatRecord>> asList(Keys.PK_DISTANCEBOAT);
	}

	@Override
	public Distanceboat as(String alias) {
		return new Distanceboat(DSL.name(alias), this);
	}

	@Override
	public Distanceboat as(Name alias) {
		return new Distanceboat(alias, this);
	}

	/**
	 * Rename this table
	 */
	@Override
	public Distanceboat rename(String name) {
		return new Distanceboat(DSL.name(name), null);
	}

	/**
	 * Rename this table
	 */
	@Override
	public Distanceboat rename(Name name) {
		return new Distanceboat(name, null);
	}

	// -------------------------------------------------------------------------
	// Row2 type methods
	// -------------------------------------------------------------------------

	@Override
	public Row2<String, Long> fieldsRow() {
		return (Row2) super.fieldsRow();
	}
}
