/*
 * This file is generated by jOOQ.
 */
package com.hm.achievement.db.tables;

import com.hm.achievement.db.DefaultSchema;
import com.hm.achievement.db.Keys;
import com.hm.achievement.db.tables.records.DistancehorseRecord;

import java.util.Arrays;
import java.util.List;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Row2;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;

/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Distancehorse extends TableImpl<DistancehorseRecord> {

	private static final long serialVersionUID = 424564349;

	/**
	 * The reference instance of <code>distancehorse</code>
	 */
	public static final Distancehorse DISTANCEHORSE = new Distancehorse();

	/**
	 * The class holding records for this type
	 */
	@Override
	public Class<DistancehorseRecord> getRecordType() {
		return DistancehorseRecord.class;
	}

	/**
	 * The column <code>distancehorse.playername</code>.
	 */
	public final TableField<DistancehorseRecord, String> PLAYERNAME = createField(DSL.name("playername"),
			org.jooq.impl.SQLDataType.CHAR(36), this, "");

	/**
	 * The column <code>distancehorse.distancehorse</code>.
	 */
	public final TableField<DistancehorseRecord, Long> DISTANCEHORSE_ = createField(DSL.name("distancehorse"),
			org.jooq.impl.SQLDataType.BIGINT, this, "");

	/**
	 * Create a <code>distancehorse</code> table reference
	 */
	public Distancehorse() {
		this(DSL.name("distancehorse"), null);
	}

	/**
	 * Create an aliased <code>distancehorse</code> table reference
	 */
	public Distancehorse(String alias) {
		this(DSL.name(alias), DISTANCEHORSE);
	}

	/**
	 * Create an aliased <code>distancehorse</code> table reference
	 */
	public Distancehorse(Name alias) {
		this(alias, DISTANCEHORSE);
	}

	private Distancehorse(Name alias, Table<DistancehorseRecord> aliased) {
		this(alias, aliased, null);
	}

	private Distancehorse(Name alias, Table<DistancehorseRecord> aliased, Field<?>[] parameters) {
		super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
	}

	public <O extends Record> Distancehorse(Table<O> child, ForeignKey<O, DistancehorseRecord> key) {
		super(child, key, DISTANCEHORSE);
	}

	@Override
	public Schema getSchema() {
		return DefaultSchema.DEFAULT_SCHEMA;
	}

	@Override
	public UniqueKey<DistancehorseRecord> getPrimaryKey() {
		return Keys.PK_DISTANCEHORSE;
	}

	@Override
	public List<UniqueKey<DistancehorseRecord>> getKeys() {
		return Arrays.<UniqueKey<DistancehorseRecord>> asList(Keys.PK_DISTANCEHORSE);
	}

	@Override
	public Distancehorse as(String alias) {
		return new Distancehorse(DSL.name(alias), this);
	}

	@Override
	public Distancehorse as(Name alias) {
		return new Distancehorse(alias, this);
	}

	/**
	 * Rename this table
	 */
	@Override
	public Distancehorse rename(String name) {
		return new Distancehorse(DSL.name(name), null);
	}

	/**
	 * Rename this table
	 */
	@Override
	public Distancehorse rename(Name name) {
		return new Distancehorse(name, null);
	}

	// -------------------------------------------------------------------------
	// Row2 type methods
	// -------------------------------------------------------------------------

	@Override
	public Row2<String, Long> fieldsRow() {
		return (Row2) super.fieldsRow();
	}
}
