/*
 * This file is generated by jOOQ.
 */
package com.hm.achievement.db.tables;

import com.hm.achievement.db.DefaultSchema;
import com.hm.achievement.db.Keys;
import com.hm.achievement.db.tables.records.DistanceminecartRecord;

import java.util.Arrays;
import java.util.List;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Row2;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;

/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Distanceminecart extends TableImpl<DistanceminecartRecord> {

	private static final long serialVersionUID = -1414628487;

	/**
	 * The reference instance of <code>distanceminecart</code>
	 */
	public static final Distanceminecart DISTANCEMINECART = new Distanceminecart();

	/**
	 * The class holding records for this type
	 */
	@Override
	public Class<DistanceminecartRecord> getRecordType() {
		return DistanceminecartRecord.class;
	}

	/**
	 * The column <code>distanceminecart.playername</code>.
	 */
	public final TableField<DistanceminecartRecord, String> PLAYERNAME = createField(DSL.name("playername"),
			org.jooq.impl.SQLDataType.CHAR(36), this, "");

	/**
	 * The column <code>distanceminecart.distanceminecart</code>.
	 */
	public final TableField<DistanceminecartRecord, Long> DISTANCEMINECART_ = createField(DSL.name("distanceminecart"),
			org.jooq.impl.SQLDataType.BIGINT, this, "");

	/**
	 * Create a <code>distanceminecart</code> table reference
	 */
	public Distanceminecart() {
		this(DSL.name("distanceminecart"), null);
	}

	/**
	 * Create an aliased <code>distanceminecart</code> table reference
	 */
	public Distanceminecart(String alias) {
		this(DSL.name(alias), DISTANCEMINECART);
	}

	/**
	 * Create an aliased <code>distanceminecart</code> table reference
	 */
	public Distanceminecart(Name alias) {
		this(alias, DISTANCEMINECART);
	}

	private Distanceminecart(Name alias, Table<DistanceminecartRecord> aliased) {
		this(alias, aliased, null);
	}

	private Distanceminecart(Name alias, Table<DistanceminecartRecord> aliased, Field<?>[] parameters) {
		super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
	}

	public <O extends Record> Distanceminecart(Table<O> child, ForeignKey<O, DistanceminecartRecord> key) {
		super(child, key, DISTANCEMINECART);
	}

	@Override
	public Schema getSchema() {
		return DefaultSchema.DEFAULT_SCHEMA;
	}

	@Override
	public UniqueKey<DistanceminecartRecord> getPrimaryKey() {
		return Keys.PK_DISTANCEMINECART;
	}

	@Override
	public List<UniqueKey<DistanceminecartRecord>> getKeys() {
		return Arrays.<UniqueKey<DistanceminecartRecord>> asList(Keys.PK_DISTANCEMINECART);
	}

	@Override
	public Distanceminecart as(String alias) {
		return new Distanceminecart(DSL.name(alias), this);
	}

	@Override
	public Distanceminecart as(Name alias) {
		return new Distanceminecart(alias, this);
	}

	/**
	 * Rename this table
	 */
	@Override
	public Distanceminecart rename(String name) {
		return new Distanceminecart(DSL.name(name), null);
	}

	/**
	 * Rename this table
	 */
	@Override
	public Distanceminecart rename(Name name) {
		return new Distanceminecart(name, null);
	}

	// -------------------------------------------------------------------------
	// Row2 type methods
	// -------------------------------------------------------------------------

	@Override
	public Row2<String, Long> fieldsRow() {
		return (Row2) super.fieldsRow();
	}
}
