/*
 * This file is generated by jOOQ.
 */
package com.hm.achievement.db.tables;

import com.hm.achievement.db.DefaultSchema;
import com.hm.achievement.db.Keys;
import com.hm.achievement.db.tables.records.DropsRecord;

import java.util.Arrays;
import java.util.List;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Row2;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;

/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Drops extends TableImpl<DropsRecord> {

	private static final long serialVersionUID = -738652655;

	/**
	 * The reference instance of <code>drops</code>
	 */
	public static final Drops DROPS = new Drops();

	/**
	 * The class holding records for this type
	 */
	@Override
	public Class<DropsRecord> getRecordType() {
		return DropsRecord.class;
	}

	/**
	 * The column <code>drops.playername</code>.
	 */
	public final TableField<DropsRecord, String> PLAYERNAME = createField(DSL.name("playername"),
			org.jooq.impl.SQLDataType.CHAR(36), this, "");

	/**
	 * The column <code>drops.drops</code>.
	 */
	public final TableField<DropsRecord, Long> DROPS_ = createField(DSL.name("drops"), org.jooq.impl.SQLDataType.BIGINT,
			this, "");

	/**
	 * Create a <code>drops</code> table reference
	 */
	public Drops() {
		this(DSL.name("drops"), null);
	}

	/**
	 * Create an aliased <code>drops</code> table reference
	 */
	public Drops(String alias) {
		this(DSL.name(alias), DROPS);
	}

	/**
	 * Create an aliased <code>drops</code> table reference
	 */
	public Drops(Name alias) {
		this(alias, DROPS);
	}

	private Drops(Name alias, Table<DropsRecord> aliased) {
		this(alias, aliased, null);
	}

	private Drops(Name alias, Table<DropsRecord> aliased, Field<?>[] parameters) {
		super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
	}

	public <O extends Record> Drops(Table<O> child, ForeignKey<O, DropsRecord> key) {
		super(child, key, DROPS);
	}

	@Override
	public Schema getSchema() {
		return DefaultSchema.DEFAULT_SCHEMA;
	}

	@Override
	public UniqueKey<DropsRecord> getPrimaryKey() {
		return Keys.PK_DROPS;
	}

	@Override
	public List<UniqueKey<DropsRecord>> getKeys() {
		return Arrays.<UniqueKey<DropsRecord>> asList(Keys.PK_DROPS);
	}

	@Override
	public Drops as(String alias) {
		return new Drops(DSL.name(alias), this);
	}

	@Override
	public Drops as(Name alias) {
		return new Drops(alias, this);
	}

	/**
	 * Rename this table
	 */
	@Override
	public Drops rename(String name) {
		return new Drops(DSL.name(name), null);
	}

	/**
	 * Rename this table
	 */
	@Override
	public Drops rename(Name name) {
		return new Drops(name, null);
	}

	// -------------------------------------------------------------------------
	// Row2 type methods
	// -------------------------------------------------------------------------

	@Override
	public Row2<String, Long> fieldsRow() {
		return (Row2) super.fieldsRow();
	}
}
