/*
 * This file is generated by jOOQ.
 */
package com.hm.achievement.db.tables;

import com.hm.achievement.db.DefaultSchema;
import com.hm.achievement.db.Keys;
import com.hm.achievement.db.tables.records.EatenitemsRecord;

import java.util.Arrays;
import java.util.List;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Row2;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;

/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Eatenitems extends TableImpl<EatenitemsRecord> {

	private static final long serialVersionUID = -1883297822;

	/**
	 * The reference instance of <code>eatenitems</code>
	 */
	public static final Eatenitems EATENITEMS = new Eatenitems();

	/**
	 * The class holding records for this type
	 */
	@Override
	public Class<EatenitemsRecord> getRecordType() {
		return EatenitemsRecord.class;
	}

	/**
	 * The column <code>eatenitems.playername</code>.
	 */
	public final TableField<EatenitemsRecord, String> PLAYERNAME = createField(DSL.name("playername"),
			org.jooq.impl.SQLDataType.CHAR(36), this, "");

	/**
	 * The column <code>eatenitems.eatenitems</code>.
	 */
	public final TableField<EatenitemsRecord, Long> EATENITEMS_ = createField(DSL.name("eatenitems"),
			org.jooq.impl.SQLDataType.BIGINT, this, "");

	/**
	 * Create a <code>eatenitems</code> table reference
	 */
	public Eatenitems() {
		this(DSL.name("eatenitems"), null);
	}

	/**
	 * Create an aliased <code>eatenitems</code> table reference
	 */
	public Eatenitems(String alias) {
		this(DSL.name(alias), EATENITEMS);
	}

	/**
	 * Create an aliased <code>eatenitems</code> table reference
	 */
	public Eatenitems(Name alias) {
		this(alias, EATENITEMS);
	}

	private Eatenitems(Name alias, Table<EatenitemsRecord> aliased) {
		this(alias, aliased, null);
	}

	private Eatenitems(Name alias, Table<EatenitemsRecord> aliased, Field<?>[] parameters) {
		super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
	}

	public <O extends Record> Eatenitems(Table<O> child, ForeignKey<O, EatenitemsRecord> key) {
		super(child, key, EATENITEMS);
	}

	@Override
	public Schema getSchema() {
		return DefaultSchema.DEFAULT_SCHEMA;
	}

	@Override
	public UniqueKey<EatenitemsRecord> getPrimaryKey() {
		return Keys.PK_EATENITEMS;
	}

	@Override
	public List<UniqueKey<EatenitemsRecord>> getKeys() {
		return Arrays.<UniqueKey<EatenitemsRecord>> asList(Keys.PK_EATENITEMS);
	}

	@Override
	public Eatenitems as(String alias) {
		return new Eatenitems(DSL.name(alias), this);
	}

	@Override
	public Eatenitems as(Name alias) {
		return new Eatenitems(alias, this);
	}

	/**
	 * Rename this table
	 */
	@Override
	public Eatenitems rename(String name) {
		return new Eatenitems(DSL.name(name), null);
	}

	/**
	 * Rename this table
	 */
	@Override
	public Eatenitems rename(Name name) {
		return new Eatenitems(name, null);
	}

	// -------------------------------------------------------------------------
	// Row2 type methods
	// -------------------------------------------------------------------------

	@Override
	public Row2<String, Long> fieldsRow() {
		return (Row2) super.fieldsRow();
	}
}
