/*
 * This file is generated by jOOQ.
 */
package com.hm.achievement.db.tables;

import com.hm.achievement.db.DefaultSchema;
import com.hm.achievement.db.Keys;
import com.hm.achievement.db.tables.records.EggsRecord;

import java.util.Arrays;
import java.util.List;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Row2;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;

/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Eggs extends TableImpl<EggsRecord> {

	private static final long serialVersionUID = 397333267;

	/**
	 * The reference instance of <code>eggs</code>
	 */
	public static final Eggs EGGS = new Eggs();

	/**
	 * The class holding records for this type
	 */
	@Override
	public Class<EggsRecord> getRecordType() {
		return EggsRecord.class;
	}

	/**
	 * The column <code>eggs.playername</code>.
	 */
	public final TableField<EggsRecord, String> PLAYERNAME = createField(DSL.name("playername"),
			org.jooq.impl.SQLDataType.CHAR(36), this, "");

	/**
	 * The column <code>eggs.eggs</code>.
	 */
	public final TableField<EggsRecord, Long> EGGS_ = createField(DSL.name("eggs"), org.jooq.impl.SQLDataType.BIGINT, this,
			"");

	/**
	 * Create a <code>eggs</code> table reference
	 */
	public Eggs() {
		this(DSL.name("eggs"), null);
	}

	/**
	 * Create an aliased <code>eggs</code> table reference
	 */
	public Eggs(String alias) {
		this(DSL.name(alias), EGGS);
	}

	/**
	 * Create an aliased <code>eggs</code> table reference
	 */
	public Eggs(Name alias) {
		this(alias, EGGS);
	}

	private Eggs(Name alias, Table<EggsRecord> aliased) {
		this(alias, aliased, null);
	}

	private Eggs(Name alias, Table<EggsRecord> aliased, Field<?>[] parameters) {
		super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
	}

	public <O extends Record> Eggs(Table<O> child, ForeignKey<O, EggsRecord> key) {
		super(child, key, EGGS);
	}

	@Override
	public Schema getSchema() {
		return DefaultSchema.DEFAULT_SCHEMA;
	}

	@Override
	public UniqueKey<EggsRecord> getPrimaryKey() {
		return Keys.PK_EGGS;
	}

	@Override
	public List<UniqueKey<EggsRecord>> getKeys() {
		return Arrays.<UniqueKey<EggsRecord>> asList(Keys.PK_EGGS);
	}

	@Override
	public Eggs as(String alias) {
		return new Eggs(DSL.name(alias), this);
	}

	@Override
	public Eggs as(Name alias) {
		return new Eggs(alias, this);
	}

	/**
	 * Rename this table
	 */
	@Override
	public Eggs rename(String name) {
		return new Eggs(DSL.name(name), null);
	}

	/**
	 * Rename this table
	 */
	@Override
	public Eggs rename(Name name) {
		return new Eggs(name, null);
	}

	// -------------------------------------------------------------------------
	// Row2 type methods
	// -------------------------------------------------------------------------

	@Override
	public Row2<String, Long> fieldsRow() {
		return (Row2) super.fieldsRow();
	}
}
