/*
 * This file is generated by jOOQ.
 */
package com.hm.achievement.db.tables;

import com.hm.achievement.db.DefaultSchema;
import com.hm.achievement.db.Keys;
import com.hm.achievement.db.tables.records.EnderpearlsRecord;

import java.util.Arrays;
import java.util.List;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Row2;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;

/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Enderpearls extends TableImpl<EnderpearlsRecord> {

	private static final long serialVersionUID = -73097116;

	/**
	 * The reference instance of <code>enderpearls</code>
	 */
	public static final Enderpearls ENDERPEARLS = new Enderpearls();

	/**
	 * The class holding records for this type
	 */
	@Override
	public Class<EnderpearlsRecord> getRecordType() {
		return EnderpearlsRecord.class;
	}

	/**
	 * The column <code>enderpearls.playername</code>.
	 */
	public final TableField<EnderpearlsRecord, String> PLAYERNAME = createField(DSL.name("playername"),
			org.jooq.impl.SQLDataType.CHAR(36), this, "");

	/**
	 * The column <code>enderpearls.enderpearls</code>.
	 */
	public final TableField<EnderpearlsRecord, Long> ENDERPEARLS_ = createField(DSL.name("enderpearls"),
			org.jooq.impl.SQLDataType.BIGINT, this, "");

	/**
	 * Create a <code>enderpearls</code> table reference
	 */
	public Enderpearls() {
		this(DSL.name("enderpearls"), null);
	}

	/**
	 * Create an aliased <code>enderpearls</code> table reference
	 */
	public Enderpearls(String alias) {
		this(DSL.name(alias), ENDERPEARLS);
	}

	/**
	 * Create an aliased <code>enderpearls</code> table reference
	 */
	public Enderpearls(Name alias) {
		this(alias, ENDERPEARLS);
	}

	private Enderpearls(Name alias, Table<EnderpearlsRecord> aliased) {
		this(alias, aliased, null);
	}

	private Enderpearls(Name alias, Table<EnderpearlsRecord> aliased, Field<?>[] parameters) {
		super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
	}

	public <O extends Record> Enderpearls(Table<O> child, ForeignKey<O, EnderpearlsRecord> key) {
		super(child, key, ENDERPEARLS);
	}

	@Override
	public Schema getSchema() {
		return DefaultSchema.DEFAULT_SCHEMA;
	}

	@Override
	public UniqueKey<EnderpearlsRecord> getPrimaryKey() {
		return Keys.PK_ENDERPEARLS;
	}

	@Override
	public List<UniqueKey<EnderpearlsRecord>> getKeys() {
		return Arrays.<UniqueKey<EnderpearlsRecord>> asList(Keys.PK_ENDERPEARLS);
	}

	@Override
	public Enderpearls as(String alias) {
		return new Enderpearls(DSL.name(alias), this);
	}

	@Override
	public Enderpearls as(Name alias) {
		return new Enderpearls(alias, this);
	}

	/**
	 * Rename this table
	 */
	@Override
	public Enderpearls rename(String name) {
		return new Enderpearls(DSL.name(name), null);
	}

	/**
	 * Rename this table
	 */
	@Override
	public Enderpearls rename(Name name) {
		return new Enderpearls(name, null);
	}

	// -------------------------------------------------------------------------
	// Row2 type methods
	// -------------------------------------------------------------------------

	@Override
	public Row2<String, Long> fieldsRow() {
		return (Row2) super.fieldsRow();
	}
}
