/*
 * This file is generated by jOOQ.
 */
package com.hm.achievement.db.tables;

import com.hm.achievement.db.DefaultSchema;
import com.hm.achievement.db.Keys;
import com.hm.achievement.db.tables.records.FertilisingRecord;

import java.util.Arrays;
import java.util.List;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Row2;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;

/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Fertilising extends TableImpl<FertilisingRecord> {

	private static final long serialVersionUID = 2119728097;

	/**
	 * The reference instance of <code>fertilising</code>
	 */
	public static final Fertilising FERTILISING = new Fertilising();

	/**
	 * The class holding records for this type
	 */
	@Override
	public Class<FertilisingRecord> getRecordType() {
		return FertilisingRecord.class;
	}

	/**
	 * The column <code>fertilising.playername</code>.
	 */
	public final TableField<FertilisingRecord, String> PLAYERNAME = createField(DSL.name("playername"),
			org.jooq.impl.SQLDataType.CHAR(36), this, "");

	/**
	 * The column <code>fertilising.fertilising</code>.
	 */
	public final TableField<FertilisingRecord, Long> FERTILISING_ = createField(DSL.name("fertilising"),
			org.jooq.impl.SQLDataType.BIGINT, this, "");

	/**
	 * Create a <code>fertilising</code> table reference
	 */
	public Fertilising() {
		this(DSL.name("fertilising"), null);
	}

	/**
	 * Create an aliased <code>fertilising</code> table reference
	 */
	public Fertilising(String alias) {
		this(DSL.name(alias), FERTILISING);
	}

	/**
	 * Create an aliased <code>fertilising</code> table reference
	 */
	public Fertilising(Name alias) {
		this(alias, FERTILISING);
	}

	private Fertilising(Name alias, Table<FertilisingRecord> aliased) {
		this(alias, aliased, null);
	}

	private Fertilising(Name alias, Table<FertilisingRecord> aliased, Field<?>[] parameters) {
		super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
	}

	public <O extends Record> Fertilising(Table<O> child, ForeignKey<O, FertilisingRecord> key) {
		super(child, key, FERTILISING);
	}

	@Override
	public Schema getSchema() {
		return DefaultSchema.DEFAULT_SCHEMA;
	}

	@Override
	public UniqueKey<FertilisingRecord> getPrimaryKey() {
		return Keys.PK_FERTILISING;
	}

	@Override
	public List<UniqueKey<FertilisingRecord>> getKeys() {
		return Arrays.<UniqueKey<FertilisingRecord>> asList(Keys.PK_FERTILISING);
	}

	@Override
	public Fertilising as(String alias) {
		return new Fertilising(DSL.name(alias), this);
	}

	@Override
	public Fertilising as(Name alias) {
		return new Fertilising(alias, this);
	}

	/**
	 * Rename this table
	 */
	@Override
	public Fertilising rename(String name) {
		return new Fertilising(DSL.name(name), null);
	}

	/**
	 * Rename this table
	 */
	@Override
	public Fertilising rename(Name name) {
		return new Fertilising(name, null);
	}

	// -------------------------------------------------------------------------
	// Row2 type methods
	// -------------------------------------------------------------------------

	@Override
	public Row2<String, Long> fieldsRow() {
		return (Row2) super.fieldsRow();
	}
}
