/*
 * This file is generated by jOOQ.
 */
package com.hm.achievement.db.tables;

import com.hm.achievement.db.DefaultSchema;
import com.hm.achievement.db.Keys;
import com.hm.achievement.db.tables.records.FireworksRecord;

import java.util.Arrays;
import java.util.List;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Row2;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;

/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Fireworks extends TableImpl<FireworksRecord> {

	private static final long serialVersionUID = -804656887;

	/**
	 * The reference instance of <code>fireworks</code>
	 */
	public static final Fireworks FIREWORKS = new Fireworks();

	/**
	 * The class holding records for this type
	 */
	@Override
	public Class<FireworksRecord> getRecordType() {
		return FireworksRecord.class;
	}

	/**
	 * The column <code>fireworks.playername</code>.
	 */
	public final TableField<FireworksRecord, String> PLAYERNAME = createField(DSL.name("playername"),
			org.jooq.impl.SQLDataType.CHAR(36), this, "");

	/**
	 * The column <code>fireworks.fireworks</code>.
	 */
	public final TableField<FireworksRecord, Long> FIREWORKS_ = createField(DSL.name("fireworks"),
			org.jooq.impl.SQLDataType.BIGINT, this, "");

	/**
	 * Create a <code>fireworks</code> table reference
	 */
	public Fireworks() {
		this(DSL.name("fireworks"), null);
	}

	/**
	 * Create an aliased <code>fireworks</code> table reference
	 */
	public Fireworks(String alias) {
		this(DSL.name(alias), FIREWORKS);
	}

	/**
	 * Create an aliased <code>fireworks</code> table reference
	 */
	public Fireworks(Name alias) {
		this(alias, FIREWORKS);
	}

	private Fireworks(Name alias, Table<FireworksRecord> aliased) {
		this(alias, aliased, null);
	}

	private Fireworks(Name alias, Table<FireworksRecord> aliased, Field<?>[] parameters) {
		super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
	}

	public <O extends Record> Fireworks(Table<O> child, ForeignKey<O, FireworksRecord> key) {
		super(child, key, FIREWORKS);
	}

	@Override
	public Schema getSchema() {
		return DefaultSchema.DEFAULT_SCHEMA;
	}

	@Override
	public UniqueKey<FireworksRecord> getPrimaryKey() {
		return Keys.PK_FIREWORKS;
	}

	@Override
	public List<UniqueKey<FireworksRecord>> getKeys() {
		return Arrays.<UniqueKey<FireworksRecord>> asList(Keys.PK_FIREWORKS);
	}

	@Override
	public Fireworks as(String alias) {
		return new Fireworks(DSL.name(alias), this);
	}

	@Override
	public Fireworks as(Name alias) {
		return new Fireworks(alias, this);
	}

	/**
	 * Rename this table
	 */
	@Override
	public Fireworks rename(String name) {
		return new Fireworks(DSL.name(name), null);
	}

	/**
	 * Rename this table
	 */
	@Override
	public Fireworks rename(Name name) {
		return new Fireworks(name, null);
	}

	// -------------------------------------------------------------------------
	// Row2 type methods
	// -------------------------------------------------------------------------

	@Override
	public Row2<String, Long> fieldsRow() {
		return (Row2) super.fieldsRow();
	}
}
