/*
 * This file is generated by jOOQ.
 */
package com.hm.achievement.db.tables;

import com.hm.achievement.db.DefaultSchema;
import com.hm.achievement.db.Keys;
import com.hm.achievement.db.tables.records.FishRecord;

import java.util.Arrays;
import java.util.List;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Row2;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;

/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Fish extends TableImpl<FishRecord> {

	private static final long serialVersionUID = 826261257;

	/**
	 * The reference instance of <code>fish</code>
	 */
	public static final Fish FISH = new Fish();

	/**
	 * The class holding records for this type
	 */
	@Override
	public Class<FishRecord> getRecordType() {
		return FishRecord.class;
	}

	/**
	 * The column <code>fish.playername</code>.
	 */
	public final TableField<FishRecord, String> PLAYERNAME = createField(DSL.name("playername"),
			org.jooq.impl.SQLDataType.CHAR(36), this, "");

	/**
	 * The column <code>fish.fish</code>.
	 */
	public final TableField<FishRecord, Long> FISH_ = createField(DSL.name("fish"), org.jooq.impl.SQLDataType.BIGINT, this,
			"");

	/**
	 * Create a <code>fish</code> table reference
	 */
	public Fish() {
		this(DSL.name("fish"), null);
	}

	/**
	 * Create an aliased <code>fish</code> table reference
	 */
	public Fish(String alias) {
		this(DSL.name(alias), FISH);
	}

	/**
	 * Create an aliased <code>fish</code> table reference
	 */
	public Fish(Name alias) {
		this(alias, FISH);
	}

	private Fish(Name alias, Table<FishRecord> aliased) {
		this(alias, aliased, null);
	}

	private Fish(Name alias, Table<FishRecord> aliased, Field<?>[] parameters) {
		super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
	}

	public <O extends Record> Fish(Table<O> child, ForeignKey<O, FishRecord> key) {
		super(child, key, FISH);
	}

	@Override
	public Schema getSchema() {
		return DefaultSchema.DEFAULT_SCHEMA;
	}

	@Override
	public UniqueKey<FishRecord> getPrimaryKey() {
		return Keys.PK_FISH;
	}

	@Override
	public List<UniqueKey<FishRecord>> getKeys() {
		return Arrays.<UniqueKey<FishRecord>> asList(Keys.PK_FISH);
	}

	@Override
	public Fish as(String alias) {
		return new Fish(DSL.name(alias), this);
	}

	@Override
	public Fish as(Name alias) {
		return new Fish(alias, this);
	}

	/**
	 * Rename this table
	 */
	@Override
	public Fish rename(String name) {
		return new Fish(DSL.name(name), null);
	}

	/**
	 * Rename this table
	 */
	@Override
	public Fish rename(Name name) {
		return new Fish(name, null);
	}

	// -------------------------------------------------------------------------
	// Row2 type methods
	// -------------------------------------------------------------------------

	@Override
	public Row2<String, Long> fieldsRow() {
		return (Row2) super.fieldsRow();
	}
}
