/*
 * This file is generated by jOOQ.
 */
package com.hm.achievement.db.tables;

import com.hm.achievement.db.DefaultSchema;
import com.hm.achievement.db.Keys;
import com.hm.achievement.db.tables.records.HoeplowingRecord;

import java.util.Arrays;
import java.util.List;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Row2;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;

/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Hoeplowing extends TableImpl<HoeplowingRecord> {

	private static final long serialVersionUID = 1188624481;

	/**
	 * The reference instance of <code>hoeplowing</code>
	 */
	public static final Hoeplowing HOEPLOWING = new Hoeplowing();

	/**
	 * The class holding records for this type
	 */
	@Override
	public Class<HoeplowingRecord> getRecordType() {
		return HoeplowingRecord.class;
	}

	/**
	 * The column <code>hoeplowing.playername</code>.
	 */
	public final TableField<HoeplowingRecord, String> PLAYERNAME = createField(DSL.name("playername"),
			org.jooq.impl.SQLDataType.CHAR(36), this, "");

	/**
	 * The column <code>hoeplowing.hoeplowing</code>.
	 */
	public final TableField<HoeplowingRecord, Long> HOEPLOWING_ = createField(DSL.name("hoeplowing"),
			org.jooq.impl.SQLDataType.BIGINT, this, "");

	/**
	 * Create a <code>hoeplowing</code> table reference
	 */
	public Hoeplowing() {
		this(DSL.name("hoeplowing"), null);
	}

	/**
	 * Create an aliased <code>hoeplowing</code> table reference
	 */
	public Hoeplowing(String alias) {
		this(DSL.name(alias), HOEPLOWING);
	}

	/**
	 * Create an aliased <code>hoeplowing</code> table reference
	 */
	public Hoeplowing(Name alias) {
		this(alias, HOEPLOWING);
	}

	private Hoeplowing(Name alias, Table<HoeplowingRecord> aliased) {
		this(alias, aliased, null);
	}

	private Hoeplowing(Name alias, Table<HoeplowingRecord> aliased, Field<?>[] parameters) {
		super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
	}

	public <O extends Record> Hoeplowing(Table<O> child, ForeignKey<O, HoeplowingRecord> key) {
		super(child, key, HOEPLOWING);
	}

	@Override
	public Schema getSchema() {
		return DefaultSchema.DEFAULT_SCHEMA;
	}

	@Override
	public UniqueKey<HoeplowingRecord> getPrimaryKey() {
		return Keys.PK_HOEPLOWING;
	}

	@Override
	public List<UniqueKey<HoeplowingRecord>> getKeys() {
		return Arrays.<UniqueKey<HoeplowingRecord>> asList(Keys.PK_HOEPLOWING);
	}

	@Override
	public Hoeplowing as(String alias) {
		return new Hoeplowing(DSL.name(alias), this);
	}

	@Override
	public Hoeplowing as(Name alias) {
		return new Hoeplowing(alias, this);
	}

	/**
	 * Rename this table
	 */
	@Override
	public Hoeplowing rename(String name) {
		return new Hoeplowing(DSL.name(name), null);
	}

	/**
	 * Rename this table
	 */
	@Override
	public Hoeplowing rename(Name name) {
		return new Hoeplowing(name, null);
	}

	// -------------------------------------------------------------------------
	// Row2 type methods
	// -------------------------------------------------------------------------

	@Override
	public Row2<String, Long> fieldsRow() {
		return (Row2) super.fieldsRow();
	}
}
