/*
 * This file is generated by jOOQ.
 */
package com.hm.achievement.db.tables;

import com.hm.achievement.db.DefaultSchema;
import com.hm.achievement.db.Keys;
import com.hm.achievement.db.tables.records.ItembreaksRecord;

import java.util.Arrays;
import java.util.List;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Row2;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;

/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Itembreaks extends TableImpl<ItembreaksRecord> {

	private static final long serialVersionUID = -371433702;

	/**
	 * The reference instance of <code>itembreaks</code>
	 */
	public static final Itembreaks ITEMBREAKS = new Itembreaks();

	/**
	 * The class holding records for this type
	 */
	@Override
	public Class<ItembreaksRecord> getRecordType() {
		return ItembreaksRecord.class;
	}

	/**
	 * The column <code>itembreaks.playername</code>.
	 */
	public final TableField<ItembreaksRecord, String> PLAYERNAME = createField(DSL.name("playername"),
			org.jooq.impl.SQLDataType.CHAR(36), this, "");

	/**
	 * The column <code>itembreaks.itembreaks</code>.
	 */
	public final TableField<ItembreaksRecord, Long> ITEMBREAKS_ = createField(DSL.name("itembreaks"),
			org.jooq.impl.SQLDataType.BIGINT, this, "");

	/**
	 * Create a <code>itembreaks</code> table reference
	 */
	public Itembreaks() {
		this(DSL.name("itembreaks"), null);
	}

	/**
	 * Create an aliased <code>itembreaks</code> table reference
	 */
	public Itembreaks(String alias) {
		this(DSL.name(alias), ITEMBREAKS);
	}

	/**
	 * Create an aliased <code>itembreaks</code> table reference
	 */
	public Itembreaks(Name alias) {
		this(alias, ITEMBREAKS);
	}

	private Itembreaks(Name alias, Table<ItembreaksRecord> aliased) {
		this(alias, aliased, null);
	}

	private Itembreaks(Name alias, Table<ItembreaksRecord> aliased, Field<?>[] parameters) {
		super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
	}

	public <O extends Record> Itembreaks(Table<O> child, ForeignKey<O, ItembreaksRecord> key) {
		super(child, key, ITEMBREAKS);
	}

	@Override
	public Schema getSchema() {
		return DefaultSchema.DEFAULT_SCHEMA;
	}

	@Override
	public UniqueKey<ItembreaksRecord> getPrimaryKey() {
		return Keys.PK_ITEMBREAKS;
	}

	@Override
	public List<UniqueKey<ItembreaksRecord>> getKeys() {
		return Arrays.<UniqueKey<ItembreaksRecord>> asList(Keys.PK_ITEMBREAKS);
	}

	@Override
	public Itembreaks as(String alias) {
		return new Itembreaks(DSL.name(alias), this);
	}

	@Override
	public Itembreaks as(Name alias) {
		return new Itembreaks(alias, this);
	}

	/**
	 * Rename this table
	 */
	@Override
	public Itembreaks rename(String name) {
		return new Itembreaks(DSL.name(name), null);
	}

	/**
	 * Rename this table
	 */
	@Override
	public Itembreaks rename(Name name) {
		return new Itembreaks(name, null);
	}

	// -------------------------------------------------------------------------
	// Row2 type methods
	// -------------------------------------------------------------------------

	@Override
	public Row2<String, Long> fieldsRow() {
		return (Row2) super.fieldsRow();
	}
}
