/*
 * This file is generated by jOOQ.
 */
package com.hm.achievement.db.tables;

import com.hm.achievement.db.DefaultSchema;
import com.hm.achievement.db.Keys;
import com.hm.achievement.db.tables.records.LavabucketsRecord;

import java.util.Arrays;
import java.util.List;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Row2;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;

/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Lavabuckets extends TableImpl<LavabucketsRecord> {

	private static final long serialVersionUID = -1046729856;

	/**
	 * The reference instance of <code>lavabuckets</code>
	 */
	public static final Lavabuckets LAVABUCKETS = new Lavabuckets();

	/**
	 * The class holding records for this type
	 */
	@Override
	public Class<LavabucketsRecord> getRecordType() {
		return LavabucketsRecord.class;
	}

	/**
	 * The column <code>lavabuckets.playername</code>.
	 */
	public final TableField<LavabucketsRecord, String> PLAYERNAME = createField(DSL.name("playername"),
			org.jooq.impl.SQLDataType.CHAR(36), this, "");

	/**
	 * The column <code>lavabuckets.lavabuckets</code>.
	 */
	public final TableField<LavabucketsRecord, Long> LAVABUCKETS_ = createField(DSL.name("lavabuckets"),
			org.jooq.impl.SQLDataType.BIGINT, this, "");

	/**
	 * Create a <code>lavabuckets</code> table reference
	 */
	public Lavabuckets() {
		this(DSL.name("lavabuckets"), null);
	}

	/**
	 * Create an aliased <code>lavabuckets</code> table reference
	 */
	public Lavabuckets(String alias) {
		this(DSL.name(alias), LAVABUCKETS);
	}

	/**
	 * Create an aliased <code>lavabuckets</code> table reference
	 */
	public Lavabuckets(Name alias) {
		this(alias, LAVABUCKETS);
	}

	private Lavabuckets(Name alias, Table<LavabucketsRecord> aliased) {
		this(alias, aliased, null);
	}

	private Lavabuckets(Name alias, Table<LavabucketsRecord> aliased, Field<?>[] parameters) {
		super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
	}

	public <O extends Record> Lavabuckets(Table<O> child, ForeignKey<O, LavabucketsRecord> key) {
		super(child, key, LAVABUCKETS);
	}

	@Override
	public Schema getSchema() {
		return DefaultSchema.DEFAULT_SCHEMA;
	}

	@Override
	public UniqueKey<LavabucketsRecord> getPrimaryKey() {
		return Keys.PK_LAVABUCKETS;
	}

	@Override
	public List<UniqueKey<LavabucketsRecord>> getKeys() {
		return Arrays.<UniqueKey<LavabucketsRecord>> asList(Keys.PK_LAVABUCKETS);
	}

	@Override
	public Lavabuckets as(String alias) {
		return new Lavabuckets(DSL.name(alias), this);
	}

	@Override
	public Lavabuckets as(Name alias) {
		return new Lavabuckets(alias, this);
	}

	/**
	 * Rename this table
	 */
	@Override
	public Lavabuckets rename(String name) {
		return new Lavabuckets(DSL.name(name), null);
	}

	/**
	 * Rename this table
	 */
	@Override
	public Lavabuckets rename(Name name) {
		return new Lavabuckets(name, null);
	}

	// -------------------------------------------------------------------------
	// Row2 type methods
	// -------------------------------------------------------------------------

	@Override
	public Row2<String, Long> fieldsRow() {
		return (Row2) super.fieldsRow();
	}
}
