/*
 * This file is generated by jOOQ.
 */
package com.hm.achievement.db.tables;

import com.hm.achievement.db.DefaultSchema;
import com.hm.achievement.db.Keys;
import com.hm.achievement.db.tables.records.LevelsRecord;

import java.util.Arrays;
import java.util.List;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Row2;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;

/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Levels extends TableImpl<LevelsRecord> {

	private static final long serialVersionUID = -404326702;

	/**
	 * The reference instance of <code>levels</code>
	 */
	public static final Levels LEVELS = new Levels();

	/**
	 * The class holding records for this type
	 */
	@Override
	public Class<LevelsRecord> getRecordType() {
		return LevelsRecord.class;
	}

	/**
	 * The column <code>levels.playername</code>.
	 */
	public final TableField<LevelsRecord, String> PLAYERNAME = createField(DSL.name("playername"),
			org.jooq.impl.SQLDataType.CHAR(36), this, "");

	/**
	 * The column <code>levels.levels</code>.
	 */
	public final TableField<LevelsRecord, Long> LEVELS_ = createField(DSL.name("levels"), org.jooq.impl.SQLDataType.BIGINT,
			this, "");

	/**
	 * Create a <code>levels</code> table reference
	 */
	public Levels() {
		this(DSL.name("levels"), null);
	}

	/**
	 * Create an aliased <code>levels</code> table reference
	 */
	public Levels(String alias) {
		this(DSL.name(alias), LEVELS);
	}

	/**
	 * Create an aliased <code>levels</code> table reference
	 */
	public Levels(Name alias) {
		this(alias, LEVELS);
	}

	private Levels(Name alias, Table<LevelsRecord> aliased) {
		this(alias, aliased, null);
	}

	private Levels(Name alias, Table<LevelsRecord> aliased, Field<?>[] parameters) {
		super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
	}

	public <O extends Record> Levels(Table<O> child, ForeignKey<O, LevelsRecord> key) {
		super(child, key, LEVELS);
	}

	@Override
	public Schema getSchema() {
		return DefaultSchema.DEFAULT_SCHEMA;
	}

	@Override
	public UniqueKey<LevelsRecord> getPrimaryKey() {
		return Keys.PK_LEVELS;
	}

	@Override
	public List<UniqueKey<LevelsRecord>> getKeys() {
		return Arrays.<UniqueKey<LevelsRecord>> asList(Keys.PK_LEVELS);
	}

	@Override
	public Levels as(String alias) {
		return new Levels(DSL.name(alias), this);
	}

	@Override
	public Levels as(Name alias) {
		return new Levels(alias, this);
	}

	/**
	 * Rename this table
	 */
	@Override
	public Levels rename(String name) {
		return new Levels(DSL.name(name), null);
	}

	/**
	 * Rename this table
	 */
	@Override
	public Levels rename(Name name) {
		return new Levels(name, null);
	}

	// -------------------------------------------------------------------------
	// Row2 type methods
	// -------------------------------------------------------------------------

	@Override
	public Row2<String, Long> fieldsRow() {
		return (Row2) super.fieldsRow();
	}
}
