/*
 * This file is generated by jOOQ.
 */
package com.hm.achievement.db.tables;

import com.hm.achievement.db.DefaultSchema;
import com.hm.achievement.db.Keys;
import com.hm.achievement.db.tables.records.MilksRecord;

import java.util.Arrays;
import java.util.List;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Row2;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;

/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Milks extends TableImpl<MilksRecord> {

	private static final long serialVersionUID = -669670771;

	/**
	 * The reference instance of <code>milks</code>
	 */
	public static final Milks MILKS = new Milks();

	/**
	 * The class holding records for this type
	 */
	@Override
	public Class<MilksRecord> getRecordType() {
		return MilksRecord.class;
	}

	/**
	 * The column <code>milks.playername</code>.
	 */
	public final TableField<MilksRecord, String> PLAYERNAME = createField(DSL.name("playername"),
			org.jooq.impl.SQLDataType.CHAR(36), this, "");

	/**
	 * The column <code>milks.milks</code>.
	 */
	public final TableField<MilksRecord, Long> MILKS_ = createField(DSL.name("milks"), org.jooq.impl.SQLDataType.BIGINT,
			this, "");

	/**
	 * Create a <code>milks</code> table reference
	 */
	public Milks() {
		this(DSL.name("milks"), null);
	}

	/**
	 * Create an aliased <code>milks</code> table reference
	 */
	public Milks(String alias) {
		this(DSL.name(alias), MILKS);
	}

	/**
	 * Create an aliased <code>milks</code> table reference
	 */
	public Milks(Name alias) {
		this(alias, MILKS);
	}

	private Milks(Name alias, Table<MilksRecord> aliased) {
		this(alias, aliased, null);
	}

	private Milks(Name alias, Table<MilksRecord> aliased, Field<?>[] parameters) {
		super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
	}

	public <O extends Record> Milks(Table<O> child, ForeignKey<O, MilksRecord> key) {
		super(child, key, MILKS);
	}

	@Override
	public Schema getSchema() {
		return DefaultSchema.DEFAULT_SCHEMA;
	}

	@Override
	public UniqueKey<MilksRecord> getPrimaryKey() {
		return Keys.PK_MILKS;
	}

	@Override
	public List<UniqueKey<MilksRecord>> getKeys() {
		return Arrays.<UniqueKey<MilksRecord>> asList(Keys.PK_MILKS);
	}

	@Override
	public Milks as(String alias) {
		return new Milks(DSL.name(alias), this);
	}

	@Override
	public Milks as(Name alias) {
		return new Milks(alias, this);
	}

	/**
	 * Rename this table
	 */
	@Override
	public Milks rename(String name) {
		return new Milks(DSL.name(name), null);
	}

	/**
	 * Rename this table
	 */
	@Override
	public Milks rename(Name name) {
		return new Milks(name, null);
	}

	// -------------------------------------------------------------------------
	// Row2 type methods
	// -------------------------------------------------------------------------

	@Override
	public Row2<String, Long> fieldsRow() {
		return (Row2) super.fieldsRow();
	}
}
