/*
 * This file is generated by jOOQ.
 */
package com.hm.achievement.db.tables;

import com.hm.achievement.db.DefaultSchema;
import com.hm.achievement.db.Keys;
import com.hm.achievement.db.StringToUUIDConverter;
import com.hm.achievement.db.tables.records.NormalAchievementRecord;

import java.util.Arrays;
import java.util.List;
import java.util.UUID;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Row3;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;

/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class NormalAchievement extends TableImpl<NormalAchievementRecord> {

	private static final long serialVersionUID = 1;

	/**
	 * The reference instance of <code>normalachievement</code>
	 */
	public static final NormalAchievement NORMALACHIEVEMENT = new NormalAchievement();

	/**
	 * The class holding records for this type
	 */
	@Override
	public Class<NormalAchievementRecord> getRecordType() {
		return NormalAchievementRecord.class;
	}

	/**
	 * The column <code>normalachievement.playername</code>.
	 */
	public final TableField<NormalAchievementRecord, String> PLAYERNAME = createField(DSL.name("playername"),
			org.jooq.impl.SQLDataType.CHAR(36), this, "");

	/**
	 * The convenience column <code>achievements.playername</code>.
	 */
	public final TableField<NormalAchievementRecord, UUID> PLAYERUUID = createField(DSL.name("playername"),
			org.jooq.impl.SQLDataType.CHAR(36).asConvertedDataType(new StringToUUIDConverter()), this, "");

	/**
	 * The column <code>normalachievement.normalachievement</code>.
	 */
	public final TableField<NormalAchievementRecord, Integer> NORMALACHIEVEMENT_ = createField(DSL.name("normalachievement"),
			org.jooq.impl.SQLDataType.INTEGER, this, "");

	/**
	 * The column <code>normalachievement.date</code>.
	 */
	public final TableField<NormalAchievementRecord, String> DATE = createField(DSL.name("date"),
			org.jooq.impl.SQLDataType.VARCHAR(10), this, "");

	/**
	 * Create a <code>normalachievement</code> table reference
	 */
	public NormalAchievement() {
		this(DSL.name("normalachievement"), null);
	}

	/**
	 * Create an aliased <code>normalachievement</code> table reference
	 */
	public NormalAchievement(String alias) {
		this(DSL.name(alias), NORMALACHIEVEMENT);
	}

	/**
	 * Create an aliased <code>normalachievement</code> table reference
	 */
	public NormalAchievement(Name alias) {
		this(alias, NORMALACHIEVEMENT);
	}

	private NormalAchievement(Name alias, Table<NormalAchievementRecord> aliased) {
		this(alias, aliased, null);
	}

	private NormalAchievement(Name alias, Table<NormalAchievementRecord> aliased, Field<?>[] parameters) {
		super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
	}

	public <O extends Record> NormalAchievement(Table<O> child, ForeignKey<O, NormalAchievementRecord> key) {
		super(child, key, NORMALACHIEVEMENT);
	}

	@Override
	public Schema getSchema() {
		return DefaultSchema.DEFAULT_SCHEMA;
	}

	@Override
	public UniqueKey<NormalAchievementRecord> getPrimaryKey() {
		return Keys.PK_NORMALACHIEVEMENT;
	}

	@Override
	public List<UniqueKey<NormalAchievementRecord>> getKeys() {
		return Arrays.<UniqueKey<NormalAchievementRecord>> asList(Keys.PK_NORMALACHIEVEMENT);
	}

	@Override
	public NormalAchievement as(String alias) {
		return new NormalAchievement(DSL.name(alias), this);
	}

	@Override
	public NormalAchievement as(Name alias) {
		return new NormalAchievement(alias, this);
	}

	/**
	 * Rename this table
	 */
	@Override
	public NormalAchievement rename(String name) {
		return new NormalAchievement(DSL.name(name), null);
	}

	/**
	 * Rename this table
	 */
	@Override
	public NormalAchievement rename(Name name) {
		return new NormalAchievement(name, null);
	}

	// -------------------------------------------------------------------------
	// Row3 type methods
	// -------------------------------------------------------------------------

	@Override
	public Row3<String, Integer, String> fieldsRow() {
		return (Row3) super.fieldsRow();
	}
}
