/*
 * This file is generated by jOOQ.
 */
package com.hm.achievement.db.tables;

import com.hm.achievement.db.DefaultSchema;
import com.hm.achievement.db.Keys;
import com.hm.achievement.db.tables.records.PetmastergiveRecord;

import java.util.Arrays;
import java.util.List;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Row2;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;

/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Petmastergive extends TableImpl<PetmastergiveRecord> {

	private static final long serialVersionUID = -2052502117;

	/**
	 * The reference instance of <code>petmastergive</code>
	 */
	public static final Petmastergive PETMASTERGIVE = new Petmastergive();

	/**
	 * The class holding records for this type
	 */
	@Override
	public Class<PetmastergiveRecord> getRecordType() {
		return PetmastergiveRecord.class;
	}

	/**
	 * The column <code>petmastergive.playername</code>.
	 */
	public final TableField<PetmastergiveRecord, String> PLAYERNAME = createField(DSL.name("playername"),
			org.jooq.impl.SQLDataType.CHAR(36), this, "");

	/**
	 * The column <code>petmastergive.petmastergive</code>.
	 */
	public final TableField<PetmastergiveRecord, Long> PETMASTERGIVE_ = createField(DSL.name("petmastergive"),
			org.jooq.impl.SQLDataType.BIGINT, this, "");

	/**
	 * Create a <code>petmastergive</code> table reference
	 */
	public Petmastergive() {
		this(DSL.name("petmastergive"), null);
	}

	/**
	 * Create an aliased <code>petmastergive</code> table reference
	 */
	public Petmastergive(String alias) {
		this(DSL.name(alias), PETMASTERGIVE);
	}

	/**
	 * Create an aliased <code>petmastergive</code> table reference
	 */
	public Petmastergive(Name alias) {
		this(alias, PETMASTERGIVE);
	}

	private Petmastergive(Name alias, Table<PetmastergiveRecord> aliased) {
		this(alias, aliased, null);
	}

	private Petmastergive(Name alias, Table<PetmastergiveRecord> aliased, Field<?>[] parameters) {
		super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
	}

	public <O extends Record> Petmastergive(Table<O> child, ForeignKey<O, PetmastergiveRecord> key) {
		super(child, key, PETMASTERGIVE);
	}

	@Override
	public Schema getSchema() {
		return DefaultSchema.DEFAULT_SCHEMA;
	}

	@Override
	public UniqueKey<PetmastergiveRecord> getPrimaryKey() {
		return Keys.PK_PETMASTERGIVE;
	}

	@Override
	public List<UniqueKey<PetmastergiveRecord>> getKeys() {
		return Arrays.<UniqueKey<PetmastergiveRecord>> asList(Keys.PK_PETMASTERGIVE);
	}

	@Override
	public Petmastergive as(String alias) {
		return new Petmastergive(DSL.name(alias), this);
	}

	@Override
	public Petmastergive as(Name alias) {
		return new Petmastergive(alias, this);
	}

	/**
	 * Rename this table
	 */
	@Override
	public Petmastergive rename(String name) {
		return new Petmastergive(DSL.name(name), null);
	}

	/**
	 * Rename this table
	 */
	@Override
	public Petmastergive rename(Name name) {
		return new Petmastergive(name, null);
	}

	// -------------------------------------------------------------------------
	// Row2 type methods
	// -------------------------------------------------------------------------

	@Override
	public Row2<String, Long> fieldsRow() {
		return (Row2) super.fieldsRow();
	}
}
