/*
 * This file is generated by jOOQ.
 */
package com.hm.achievement.db.tables;

import com.hm.achievement.db.DefaultSchema;
import com.hm.achievement.db.Keys;
import com.hm.achievement.db.tables.records.PetmasterreceiveRecord;

import java.util.Arrays;
import java.util.List;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Row2;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;

/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Petmasterreceive extends TableImpl<PetmasterreceiveRecord> {

	private static final long serialVersionUID = 1418096159;

	/**
	 * The reference instance of <code>petmasterreceive</code>
	 */
	public static final Petmasterreceive PETMASTERRECEIVE = new Petmasterreceive();

	/**
	 * The class holding records for this type
	 */
	@Override
	public Class<PetmasterreceiveRecord> getRecordType() {
		return PetmasterreceiveRecord.class;
	}

	/**
	 * The column <code>petmasterreceive.playername</code>.
	 */
	public final TableField<PetmasterreceiveRecord, String> PLAYERNAME = createField(DSL.name("playername"),
			org.jooq.impl.SQLDataType.CHAR(36), this, "");

	/**
	 * The column <code>petmasterreceive.petmasterreceive</code>.
	 */
	public final TableField<PetmasterreceiveRecord, Long> PETMASTERRECEIVE_ = createField(DSL.name("petmasterreceive"),
			org.jooq.impl.SQLDataType.BIGINT, this, "");

	/**
	 * Create a <code>petmasterreceive</code> table reference
	 */
	public Petmasterreceive() {
		this(DSL.name("petmasterreceive"), null);
	}

	/**
	 * Create an aliased <code>petmasterreceive</code> table reference
	 */
	public Petmasterreceive(String alias) {
		this(DSL.name(alias), PETMASTERRECEIVE);
	}

	/**
	 * Create an aliased <code>petmasterreceive</code> table reference
	 */
	public Petmasterreceive(Name alias) {
		this(alias, PETMASTERRECEIVE);
	}

	private Petmasterreceive(Name alias, Table<PetmasterreceiveRecord> aliased) {
		this(alias, aliased, null);
	}

	private Petmasterreceive(Name alias, Table<PetmasterreceiveRecord> aliased, Field<?>[] parameters) {
		super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
	}

	public <O extends Record> Petmasterreceive(Table<O> child, ForeignKey<O, PetmasterreceiveRecord> key) {
		super(child, key, PETMASTERRECEIVE);
	}

	@Override
	public Schema getSchema() {
		return DefaultSchema.DEFAULT_SCHEMA;
	}

	@Override
	public UniqueKey<PetmasterreceiveRecord> getPrimaryKey() {
		return Keys.PK_PETMASTERRECEIVE;
	}

	@Override
	public List<UniqueKey<PetmasterreceiveRecord>> getKeys() {
		return Arrays.<UniqueKey<PetmasterreceiveRecord>> asList(Keys.PK_PETMASTERRECEIVE);
	}

	@Override
	public Petmasterreceive as(String alias) {
		return new Petmasterreceive(DSL.name(alias), this);
	}

	@Override
	public Petmasterreceive as(Name alias) {
		return new Petmasterreceive(alias, this);
	}

	/**
	 * Rename this table
	 */
	@Override
	public Petmasterreceive rename(String name) {
		return new Petmasterreceive(DSL.name(name), null);
	}

	/**
	 * Rename this table
	 */
	@Override
	public Petmasterreceive rename(Name name) {
		return new Petmasterreceive(name, null);
	}

	// -------------------------------------------------------------------------
	// Row2 type methods
	// -------------------------------------------------------------------------

	@Override
	public Row2<String, Long> fieldsRow() {
		return (Row2) super.fieldsRow();
	}
}
