/*
 * This file is generated by jOOQ.
 */
package com.hm.achievement.db.tables;

import com.hm.achievement.db.DefaultSchema;
import com.hm.achievement.db.Keys;
import com.hm.achievement.db.tables.records.PickupsRecord;

import java.util.Arrays;
import java.util.List;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Row2;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;

/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Pickups extends TableImpl<PickupsRecord> {

	private static final long serialVersionUID = -572901014;

	/**
	 * The reference instance of <code>pickups</code>
	 */
	public static final Pickups PICKUPS = new Pickups();

	/**
	 * The class holding records for this type
	 */
	@Override
	public Class<PickupsRecord> getRecordType() {
		return PickupsRecord.class;
	}

	/**
	 * The column <code>pickups.playername</code>.
	 */
	public final TableField<PickupsRecord, String> PLAYERNAME = createField(DSL.name("playername"),
			org.jooq.impl.SQLDataType.CHAR(36), this, "");

	/**
	 * The column <code>pickups.pickups</code>.
	 */
	public final TableField<PickupsRecord, Long> PICKUPS_ = createField(DSL.name("pickups"),
			org.jooq.impl.SQLDataType.BIGINT, this, "");

	/**
	 * Create a <code>pickups</code> table reference
	 */
	public Pickups() {
		this(DSL.name("pickups"), null);
	}

	/**
	 * Create an aliased <code>pickups</code> table reference
	 */
	public Pickups(String alias) {
		this(DSL.name(alias), PICKUPS);
	}

	/**
	 * Create an aliased <code>pickups</code> table reference
	 */
	public Pickups(Name alias) {
		this(alias, PICKUPS);
	}

	private Pickups(Name alias, Table<PickupsRecord> aliased) {
		this(alias, aliased, null);
	}

	private Pickups(Name alias, Table<PickupsRecord> aliased, Field<?>[] parameters) {
		super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
	}

	public <O extends Record> Pickups(Table<O> child, ForeignKey<O, PickupsRecord> key) {
		super(child, key, PICKUPS);
	}

	@Override
	public Schema getSchema() {
		return DefaultSchema.DEFAULT_SCHEMA;
	}

	@Override
	public UniqueKey<PickupsRecord> getPrimaryKey() {
		return Keys.PK_PICKUPS;
	}

	@Override
	public List<UniqueKey<PickupsRecord>> getKeys() {
		return Arrays.<UniqueKey<PickupsRecord>> asList(Keys.PK_PICKUPS);
	}

	@Override
	public Pickups as(String alias) {
		return new Pickups(DSL.name(alias), this);
	}

	@Override
	public Pickups as(Name alias) {
		return new Pickups(alias, this);
	}

	/**
	 * Rename this table
	 */
	@Override
	public Pickups rename(String name) {
		return new Pickups(DSL.name(name), null);
	}

	/**
	 * Rename this table
	 */
	@Override
	public Pickups rename(Name name) {
		return new Pickups(name, null);
	}

	// -------------------------------------------------------------------------
	// Row2 type methods
	// -------------------------------------------------------------------------

	@Override
	public Row2<String, Long> fieldsRow() {
		return (Row2) super.fieldsRow();
	}
}
