/*
 * This file is generated by jOOQ.
 */
package com.hm.achievement.db.tables;

import com.hm.achievement.db.DefaultSchema;
import com.hm.achievement.db.Keys;
import com.hm.achievement.db.tables.records.PlacesRecord;

import java.util.Arrays;
import java.util.List;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Row3;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;

/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Places extends TableImpl<PlacesRecord> {

	private static final long serialVersionUID = 1238971940;

	/**
	 * The reference instance of <code>places</code>
	 */
	public static final Places PLACES = new Places();

	/**
	 * The class holding records for this type
	 */
	@Override
	public Class<PlacesRecord> getRecordType() {
		return PlacesRecord.class;
	}

	/**
	 * The column <code>places.playername</code>.
	 */
	public final TableField<PlacesRecord, String> PLAYERNAME = createField(DSL.name("playername"),
			org.jooq.impl.SQLDataType.CHAR(36), this, "");

	/**
	 * The column <code>places.blockid</code>.
	 */
	public final TableField<PlacesRecord, String> BLOCKID = createField(DSL.name("blockid"),
			org.jooq.impl.SQLDataType.VARCHAR(191), this, "");

	/**
	 * The column <code>places.places</code>.
	 */
	public final TableField<PlacesRecord, Integer> PLACES_ = createField(DSL.name("places"),
			org.jooq.impl.SQLDataType.INTEGER, this, "");

	/**
	 * Create a <code>places</code> table reference
	 */
	public Places() {
		this(DSL.name("places"), null);
	}

	/**
	 * Create an aliased <code>places</code> table reference
	 */
	public Places(String alias) {
		this(DSL.name(alias), PLACES);
	}

	/**
	 * Create an aliased <code>places</code> table reference
	 */
	public Places(Name alias) {
		this(alias, PLACES);
	}

	private Places(Name alias, Table<PlacesRecord> aliased) {
		this(alias, aliased, null);
	}

	private Places(Name alias, Table<PlacesRecord> aliased, Field<?>[] parameters) {
		super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
	}

	public <O extends Record> Places(Table<O> child, ForeignKey<O, PlacesRecord> key) {
		super(child, key, PLACES);
	}

	@Override
	public Schema getSchema() {
		return DefaultSchema.DEFAULT_SCHEMA;
	}

	@Override
	public UniqueKey<PlacesRecord> getPrimaryKey() {
		return Keys.PK_PLACES;
	}

	@Override
	public List<UniqueKey<PlacesRecord>> getKeys() {
		return Arrays.<UniqueKey<PlacesRecord>> asList(Keys.PK_PLACES);
	}

	@Override
	public Places as(String alias) {
		return new Places(DSL.name(alias), this);
	}

	@Override
	public Places as(Name alias) {
		return new Places(alias, this);
	}

	/**
	 * Rename this table
	 */
	@Override
	public Places rename(String name) {
		return new Places(DSL.name(name), null);
	}

	/**
	 * Rename this table
	 */
	@Override
	public Places rename(Name name) {
		return new Places(name, null);
	}

	// -------------------------------------------------------------------------
	// Row3 type methods
	// -------------------------------------------------------------------------

	@Override
	public Row3<String, String, Integer> fieldsRow() {
		return (Row3) super.fieldsRow();
	}
}
