/*
 * This file is generated by jOOQ.
 */
package com.hm.achievement.db.tables;

import com.hm.achievement.db.DefaultSchema;
import com.hm.achievement.db.Keys;
import com.hm.achievement.db.tables.records.PlayedtimeRecord;

import java.util.Arrays;
import java.util.List;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Row2;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;

/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Playedtime extends TableImpl<PlayedtimeRecord> {

	private static final long serialVersionUID = -274650431;

	/**
	 * The reference instance of <code>playedtime</code>
	 */
	public static final Playedtime PLAYEDTIME = new Playedtime();

	/**
	 * The class holding records for this type
	 */
	@Override
	public Class<PlayedtimeRecord> getRecordType() {
		return PlayedtimeRecord.class;
	}

	/**
	 * The column <code>playedtime.playername</code>.
	 */
	public final TableField<PlayedtimeRecord, String> PLAYERNAME = createField(DSL.name("playername"),
			org.jooq.impl.SQLDataType.CHAR(36), this, "");

	/**
	 * The column <code>playedtime.playedtime</code>.
	 */
	public final TableField<PlayedtimeRecord, Long> PLAYEDTIME_ = createField(DSL.name("playedtime"),
			org.jooq.impl.SQLDataType.BIGINT, this, "");

	/**
	 * Create a <code>playedtime</code> table reference
	 */
	public Playedtime() {
		this(DSL.name("playedtime"), null);
	}

	/**
	 * Create an aliased <code>playedtime</code> table reference
	 */
	public Playedtime(String alias) {
		this(DSL.name(alias), PLAYEDTIME);
	}

	/**
	 * Create an aliased <code>playedtime</code> table reference
	 */
	public Playedtime(Name alias) {
		this(alias, PLAYEDTIME);
	}

	private Playedtime(Name alias, Table<PlayedtimeRecord> aliased) {
		this(alias, aliased, null);
	}

	private Playedtime(Name alias, Table<PlayedtimeRecord> aliased, Field<?>[] parameters) {
		super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
	}

	public <O extends Record> Playedtime(Table<O> child, ForeignKey<O, PlayedtimeRecord> key) {
		super(child, key, PLAYEDTIME);
	}

	@Override
	public Schema getSchema() {
		return DefaultSchema.DEFAULT_SCHEMA;
	}

	@Override
	public UniqueKey<PlayedtimeRecord> getPrimaryKey() {
		return Keys.PK_PLAYEDTIME;
	}

	@Override
	public List<UniqueKey<PlayedtimeRecord>> getKeys() {
		return Arrays.<UniqueKey<PlayedtimeRecord>> asList(Keys.PK_PLAYEDTIME);
	}

	@Override
	public Playedtime as(String alias) {
		return new Playedtime(DSL.name(alias), this);
	}

	@Override
	public Playedtime as(Name alias) {
		return new Playedtime(alias, this);
	}

	/**
	 * Rename this table
	 */
	@Override
	public Playedtime rename(String name) {
		return new Playedtime(DSL.name(name), null);
	}

	/**
	 * Rename this table
	 */
	@Override
	public Playedtime rename(Name name) {
		return new Playedtime(name, null);
	}

	// -------------------------------------------------------------------------
	// Row2 type methods
	// -------------------------------------------------------------------------

	@Override
	public Row2<String, Long> fieldsRow() {
		return (Row2) super.fieldsRow();
	}
}
