/*
 * This file is generated by jOOQ.
 */
package com.hm.achievement.db.tables;

import com.hm.achievement.db.DefaultSchema;
import com.hm.achievement.db.Keys;
import com.hm.achievement.db.tables.records.PlayercommandsRecord;

import java.util.Arrays;
import java.util.List;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Row3;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;

/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Playercommands extends TableImpl<PlayercommandsRecord> {

	private static final long serialVersionUID = -1042023018;

	/**
	 * The reference instance of <code>playercommands</code>
	 */
	public static final Playercommands PLAYERCOMMANDS = new Playercommands();

	/**
	 * The class holding records for this type
	 */
	@Override
	public Class<PlayercommandsRecord> getRecordType() {
		return PlayercommandsRecord.class;
	}

	/**
	 * The column <code>playercommands.playername</code>.
	 */
	public final TableField<PlayercommandsRecord, String> PLAYERNAME = createField(DSL.name("playername"),
			org.jooq.impl.SQLDataType.CHAR(36), this, "");

	/**
	 * The column <code>playercommands.command</code>.
	 */
	public final TableField<PlayercommandsRecord, String> COMMAND = createField(DSL.name("command"),
			org.jooq.impl.SQLDataType.VARCHAR(191), this, "");

	/**
	 * The column <code>playercommands.playercommands</code>.
	 */
	public final TableField<PlayercommandsRecord, Integer> PLAYERCOMMANDS_ = createField(DSL.name("playercommands"),
			org.jooq.impl.SQLDataType.INTEGER, this, "");

	/**
	 * Create a <code>playercommands</code> table reference
	 */
	public Playercommands() {
		this(DSL.name("playercommands"), null);
	}

	/**
	 * Create an aliased <code>playercommands</code> table reference
	 */
	public Playercommands(String alias) {
		this(DSL.name(alias), PLAYERCOMMANDS);
	}

	/**
	 * Create an aliased <code>playercommands</code> table reference
	 */
	public Playercommands(Name alias) {
		this(alias, PLAYERCOMMANDS);
	}

	private Playercommands(Name alias, Table<PlayercommandsRecord> aliased) {
		this(alias, aliased, null);
	}

	private Playercommands(Name alias, Table<PlayercommandsRecord> aliased, Field<?>[] parameters) {
		super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
	}

	public <O extends Record> Playercommands(Table<O> child, ForeignKey<O, PlayercommandsRecord> key) {
		super(child, key, PLAYERCOMMANDS);
	}

	@Override
	public Schema getSchema() {
		return DefaultSchema.DEFAULT_SCHEMA;
	}

	@Override
	public UniqueKey<PlayercommandsRecord> getPrimaryKey() {
		return Keys.PK_PLAYERCOMMANDS;
	}

	@Override
	public List<UniqueKey<PlayercommandsRecord>> getKeys() {
		return Arrays.<UniqueKey<PlayercommandsRecord>> asList(Keys.PK_PLAYERCOMMANDS);
	}

	@Override
	public Playercommands as(String alias) {
		return new Playercommands(DSL.name(alias), this);
	}

	@Override
	public Playercommands as(Name alias) {
		return new Playercommands(alias, this);
	}

	/**
	 * Rename this table
	 */
	@Override
	public Playercommands rename(String name) {
		return new Playercommands(DSL.name(name), null);
	}

	/**
	 * Rename this table
	 */
	@Override
	public Playercommands rename(Name name) {
		return new Playercommands(name, null);
	}

	// -------------------------------------------------------------------------
	// Row3 type methods
	// -------------------------------------------------------------------------

	@Override
	public Row3<String, String, Integer> fieldsRow() {
		return (Row3) super.fieldsRow();
	}
}
