/*
 * This file is generated by jOOQ.
 */
package com.hm.achievement.db.tables;

import com.hm.achievement.db.DefaultSchema;
import com.hm.achievement.db.Keys;
import com.hm.achievement.db.tables.records.ShearsRecord;

import java.util.Arrays;
import java.util.List;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Row2;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;

/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Shears extends TableImpl<ShearsRecord> {

	private static final long serialVersionUID = 1194387823;

	/**
	 * The reference instance of <code>shears</code>
	 */
	public static final Shears SHEARS = new Shears();

	/**
	 * The class holding records for this type
	 */
	@Override
	public Class<ShearsRecord> getRecordType() {
		return ShearsRecord.class;
	}

	/**
	 * The column <code>shears.playername</code>.
	 */
	public final TableField<ShearsRecord, String> PLAYERNAME = createField(DSL.name("playername"),
			org.jooq.impl.SQLDataType.CHAR(36), this, "");

	/**
	 * The column <code>shears.shears</code>.
	 */
	public final TableField<ShearsRecord, Long> SHEARS_ = createField(DSL.name("shears"), org.jooq.impl.SQLDataType.BIGINT,
			this, "");

	/**
	 * Create a <code>shears</code> table reference
	 */
	public Shears() {
		this(DSL.name("shears"), null);
	}

	/**
	 * Create an aliased <code>shears</code> table reference
	 */
	public Shears(String alias) {
		this(DSL.name(alias), SHEARS);
	}

	/**
	 * Create an aliased <code>shears</code> table reference
	 */
	public Shears(Name alias) {
		this(alias, SHEARS);
	}

	private Shears(Name alias, Table<ShearsRecord> aliased) {
		this(alias, aliased, null);
	}

	private Shears(Name alias, Table<ShearsRecord> aliased, Field<?>[] parameters) {
		super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
	}

	public <O extends Record> Shears(Table<O> child, ForeignKey<O, ShearsRecord> key) {
		super(child, key, SHEARS);
	}

	@Override
	public Schema getSchema() {
		return DefaultSchema.DEFAULT_SCHEMA;
	}

	@Override
	public UniqueKey<ShearsRecord> getPrimaryKey() {
		return Keys.PK_SHEARS;
	}

	@Override
	public List<UniqueKey<ShearsRecord>> getKeys() {
		return Arrays.<UniqueKey<ShearsRecord>> asList(Keys.PK_SHEARS);
	}

	@Override
	public Shears as(String alias) {
		return new Shears(DSL.name(alias), this);
	}

	@Override
	public Shears as(Name alias) {
		return new Shears(alias, this);
	}

	/**
	 * Rename this table
	 */
	@Override
	public Shears rename(String name) {
		return new Shears(DSL.name(name), null);
	}

	/**
	 * Rename this table
	 */
	@Override
	public Shears rename(Name name) {
		return new Shears(name, null);
	}

	// -------------------------------------------------------------------------
	// Row2 type methods
	// -------------------------------------------------------------------------

	@Override
	public Row2<String, Long> fieldsRow() {
		return (Row2) super.fieldsRow();
	}
}
