/*
 * This file is generated by jOOQ.
 */
package com.hm.achievement.db.tables;

import com.hm.achievement.db.DefaultSchema;
import com.hm.achievement.db.Keys;
import com.hm.achievement.db.tables.records.SmeltingRecord;

import java.util.Arrays;
import java.util.List;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Row2;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;

/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Smelting extends TableImpl<SmeltingRecord> {

	private static final long serialVersionUID = -2078754478;

	/**
	 * The reference instance of <code>smelting</code>
	 */
	public static final Smelting SMELTING = new Smelting();

	/**
	 * The class holding records for this type
	 */
	@Override
	public Class<SmeltingRecord> getRecordType() {
		return SmeltingRecord.class;
	}

	/**
	 * The column <code>smelting.playername</code>.
	 */
	public final TableField<SmeltingRecord, String> PLAYERNAME = createField(DSL.name("playername"),
			org.jooq.impl.SQLDataType.CHAR(36), this, "");

	/**
	 * The column <code>smelting.smelting</code>.
	 */
	public final TableField<SmeltingRecord, Long> SMELTING_ = createField(DSL.name("smelting"),
			org.jooq.impl.SQLDataType.BIGINT, this, "");

	/**
	 * Create a <code>smelting</code> table reference
	 */
	public Smelting() {
		this(DSL.name("smelting"), null);
	}

	/**
	 * Create an aliased <code>smelting</code> table reference
	 */
	public Smelting(String alias) {
		this(DSL.name(alias), SMELTING);
	}

	/**
	 * Create an aliased <code>smelting</code> table reference
	 */
	public Smelting(Name alias) {
		this(alias, SMELTING);
	}

	private Smelting(Name alias, Table<SmeltingRecord> aliased) {
		this(alias, aliased, null);
	}

	private Smelting(Name alias, Table<SmeltingRecord> aliased, Field<?>[] parameters) {
		super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
	}

	public <O extends Record> Smelting(Table<O> child, ForeignKey<O, SmeltingRecord> key) {
		super(child, key, SMELTING);
	}

	@Override
	public Schema getSchema() {
		return DefaultSchema.DEFAULT_SCHEMA;
	}

	@Override
	public UniqueKey<SmeltingRecord> getPrimaryKey() {
		return Keys.PK_SMELTING;
	}

	@Override
	public List<UniqueKey<SmeltingRecord>> getKeys() {
		return Arrays.<UniqueKey<SmeltingRecord>> asList(Keys.PK_SMELTING);
	}

	@Override
	public Smelting as(String alias) {
		return new Smelting(DSL.name(alias), this);
	}

	@Override
	public Smelting as(Name alias) {
		return new Smelting(alias, this);
	}

	/**
	 * Rename this table
	 */
	@Override
	public Smelting rename(String name) {
		return new Smelting(DSL.name(name), null);
	}

	/**
	 * Rename this table
	 */
	@Override
	public Smelting rename(Name name) {
		return new Smelting(name, null);
	}

	// -------------------------------------------------------------------------
	// Row2 type methods
	// -------------------------------------------------------------------------

	@Override
	public Row2<String, Long> fieldsRow() {
		return (Row2) super.fieldsRow();
	}
}
