/*
 * This file is generated by jOOQ.
 */
package com.hm.achievement.db.tables;

import com.hm.achievement.db.DefaultSchema;
import com.hm.achievement.db.Keys;
import com.hm.achievement.db.tables.records.SnowballsRecord;

import java.util.Arrays;
import java.util.List;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Row2;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;

/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Snowballs extends TableImpl<SnowballsRecord> {

	private static final long serialVersionUID = 1288649176;

	/**
	 * The reference instance of <code>snowballs</code>
	 */
	public static final Snowballs SNOWBALLS = new Snowballs();

	/**
	 * The class holding records for this type
	 */
	@Override
	public Class<SnowballsRecord> getRecordType() {
		return SnowballsRecord.class;
	}

	/**
	 * The column <code>snowballs.playername</code>.
	 */
	public final TableField<SnowballsRecord, String> PLAYERNAME = createField(DSL.name("playername"),
			org.jooq.impl.SQLDataType.CHAR(36), this, "");

	/**
	 * The column <code>snowballs.snowballs</code>.
	 */
	public final TableField<SnowballsRecord, Long> SNOWBALLS_ = createField(DSL.name("snowballs"),
			org.jooq.impl.SQLDataType.BIGINT, this, "");

	/**
	 * Create a <code>snowballs</code> table reference
	 */
	public Snowballs() {
		this(DSL.name("snowballs"), null);
	}

	/**
	 * Create an aliased <code>snowballs</code> table reference
	 */
	public Snowballs(String alias) {
		this(DSL.name(alias), SNOWBALLS);
	}

	/**
	 * Create an aliased <code>snowballs</code> table reference
	 */
	public Snowballs(Name alias) {
		this(alias, SNOWBALLS);
	}

	private Snowballs(Name alias, Table<SnowballsRecord> aliased) {
		this(alias, aliased, null);
	}

	private Snowballs(Name alias, Table<SnowballsRecord> aliased, Field<?>[] parameters) {
		super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
	}

	public <O extends Record> Snowballs(Table<O> child, ForeignKey<O, SnowballsRecord> key) {
		super(child, key, SNOWBALLS);
	}

	@Override
	public Schema getSchema() {
		return DefaultSchema.DEFAULT_SCHEMA;
	}

	@Override
	public UniqueKey<SnowballsRecord> getPrimaryKey() {
		return Keys.PK_SNOWBALLS;
	}

	@Override
	public List<UniqueKey<SnowballsRecord>> getKeys() {
		return Arrays.<UniqueKey<SnowballsRecord>> asList(Keys.PK_SNOWBALLS);
	}

	@Override
	public Snowballs as(String alias) {
		return new Snowballs(DSL.name(alias), this);
	}

	@Override
	public Snowballs as(Name alias) {
		return new Snowballs(alias, this);
	}

	/**
	 * Rename this table
	 */
	@Override
	public Snowballs rename(String name) {
		return new Snowballs(DSL.name(name), null);
	}

	/**
	 * Rename this table
	 */
	@Override
	public Snowballs rename(Name name) {
		return new Snowballs(name, null);
	}

	// -------------------------------------------------------------------------
	// Row2 type methods
	// -------------------------------------------------------------------------

	@Override
	public Row2<String, Long> fieldsRow() {
		return (Row2) super.fieldsRow();
	}
}
