/*
 * This file is generated by jOOQ.
 */
package com.hm.achievement.db.tables;

import com.hm.achievement.db.DefaultSchema;
import com.hm.achievement.db.Keys;
import com.hm.achievement.db.tables.records.TamesRecord;

import java.util.Arrays;
import java.util.List;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Row2;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;

/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tames extends TableImpl<TamesRecord> {

	private static final long serialVersionUID = -1448937841;

	/**
	 * The reference instance of <code>tames</code>
	 */
	public static final Tames TAMES = new Tames();

	/**
	 * The class holding records for this type
	 */
	@Override
	public Class<TamesRecord> getRecordType() {
		return TamesRecord.class;
	}

	/**
	 * The column <code>tames.playername</code>.
	 */
	public final TableField<TamesRecord, String> PLAYERNAME = createField(DSL.name("playername"),
			org.jooq.impl.SQLDataType.CHAR(36), this, "");

	/**
	 * The column <code>tames.tames</code>.
	 */
	public final TableField<TamesRecord, Long> TAMES_ = createField(DSL.name("tames"), org.jooq.impl.SQLDataType.BIGINT,
			this, "");

	/**
	 * Create a <code>tames</code> table reference
	 */
	public Tames() {
		this(DSL.name("tames"), null);
	}

	/**
	 * Create an aliased <code>tames</code> table reference
	 */
	public Tames(String alias) {
		this(DSL.name(alias), TAMES);
	}

	/**
	 * Create an aliased <code>tames</code> table reference
	 */
	public Tames(Name alias) {
		this(alias, TAMES);
	}

	private Tames(Name alias, Table<TamesRecord> aliased) {
		this(alias, aliased, null);
	}

	private Tames(Name alias, Table<TamesRecord> aliased, Field<?>[] parameters) {
		super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
	}

	public <O extends Record> Tames(Table<O> child, ForeignKey<O, TamesRecord> key) {
		super(child, key, TAMES);
	}

	@Override
	public Schema getSchema() {
		return DefaultSchema.DEFAULT_SCHEMA;
	}

	@Override
	public UniqueKey<TamesRecord> getPrimaryKey() {
		return Keys.PK_TAMES;
	}

	@Override
	public List<UniqueKey<TamesRecord>> getKeys() {
		return Arrays.<UniqueKey<TamesRecord>> asList(Keys.PK_TAMES);
	}

	@Override
	public Tames as(String alias) {
		return new Tames(DSL.name(alias), this);
	}

	@Override
	public Tames as(Name alias) {
		return new Tames(alias, this);
	}

	/**
	 * Rename this table
	 */
	@Override
	public Tames rename(String name) {
		return new Tames(DSL.name(name), null);
	}

	/**
	 * Rename this table
	 */
	@Override
	public Tames rename(Name name) {
		return new Tames(name, null);
	}

	// -------------------------------------------------------------------------
	// Row2 type methods
	// -------------------------------------------------------------------------

	@Override
	public Row2<String, Long> fieldsRow() {
		return (Row2) super.fieldsRow();
	}
}
