/*
 * This file is generated by jOOQ.
 */
package com.hm.achievement.db.tables;

import com.hm.achievement.db.DefaultSchema;
import com.hm.achievement.db.Keys;
import com.hm.achievement.db.tables.records.TargetsshotRecord;

import java.util.Arrays;
import java.util.List;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Row3;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;

/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Targetsshot extends TableImpl<TargetsshotRecord> {

	private static final long serialVersionUID = 712885586;

	/**
	 * The reference instance of <code>targetsshot</code>
	 */
	public static final Targetsshot TARGETSSHOT = new Targetsshot();

	/**
	 * The class holding records for this type
	 */
	@Override
	public Class<TargetsshotRecord> getRecordType() {
		return TargetsshotRecord.class;
	}

	/**
	 * The column <code>targetsshot.playername</code>.
	 */
	public final TableField<TargetsshotRecord, String> PLAYERNAME = createField(DSL.name("playername"),
			org.jooq.impl.SQLDataType.CHAR(36), this, "");

	/**
	 * The column <code>targetsshot.targetname</code>.
	 */
	public final TableField<TargetsshotRecord, String> TARGETNAME = createField(DSL.name("targetname"),
			org.jooq.impl.SQLDataType.VARCHAR(191), this, "");

	/**
	 * The column <code>targetsshot.targetsshot</code>.
	 */
	public final TableField<TargetsshotRecord, Integer> TARGETSSHOT_ = createField(DSL.name("targetsshot"),
			org.jooq.impl.SQLDataType.INTEGER, this, "");

	/**
	 * Create a <code>targetsshot</code> table reference
	 */
	public Targetsshot() {
		this(DSL.name("targetsshot"), null);
	}

	/**
	 * Create an aliased <code>targetsshot</code> table reference
	 */
	public Targetsshot(String alias) {
		this(DSL.name(alias), TARGETSSHOT);
	}

	/**
	 * Create an aliased <code>targetsshot</code> table reference
	 */
	public Targetsshot(Name alias) {
		this(alias, TARGETSSHOT);
	}

	private Targetsshot(Name alias, Table<TargetsshotRecord> aliased) {
		this(alias, aliased, null);
	}

	private Targetsshot(Name alias, Table<TargetsshotRecord> aliased, Field<?>[] parameters) {
		super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
	}

	public <O extends Record> Targetsshot(Table<O> child, ForeignKey<O, TargetsshotRecord> key) {
		super(child, key, TARGETSSHOT);
	}

	@Override
	public Schema getSchema() {
		return DefaultSchema.DEFAULT_SCHEMA;
	}

	@Override
	public UniqueKey<TargetsshotRecord> getPrimaryKey() {
		return Keys.PK_TARGETSSHOT;
	}

	@Override
	public List<UniqueKey<TargetsshotRecord>> getKeys() {
		return Arrays.<UniqueKey<TargetsshotRecord>> asList(Keys.PK_TARGETSSHOT);
	}

	@Override
	public Targetsshot as(String alias) {
		return new Targetsshot(DSL.name(alias), this);
	}

	@Override
	public Targetsshot as(Name alias) {
		return new Targetsshot(alias, this);
	}

	/**
	 * Rename this table
	 */
	@Override
	public Targetsshot rename(String name) {
		return new Targetsshot(DSL.name(name), null);
	}

	/**
	 * Rename this table
	 */
	@Override
	public Targetsshot rename(Name name) {
		return new Targetsshot(name, null);
	}

	// -------------------------------------------------------------------------
	// Row3 type methods
	// -------------------------------------------------------------------------

	@Override
	public Row3<String, String, Integer> fieldsRow() {
		return (Row3) super.fieldsRow();
	}
}
