/*
 * This file is generated by jOOQ.
 */
package com.hm.achievement.db.tables;

import com.hm.achievement.db.DefaultSchema;
import com.hm.achievement.db.Keys;
import com.hm.achievement.db.tables.records.TradesRecord;

import java.util.Arrays;
import java.util.List;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Row2;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;

/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Trades extends TableImpl<TradesRecord> {

	private static final long serialVersionUID = 1348076722;

	/**
	 * The reference instance of <code>trades</code>
	 */
	public static final Trades TRADES = new Trades();

	/**
	 * The class holding records for this type
	 */
	@Override
	public Class<TradesRecord> getRecordType() {
		return TradesRecord.class;
	}

	/**
	 * The column <code>trades.playername</code>.
	 */
	public final TableField<TradesRecord, String> PLAYERNAME = createField(DSL.name("playername"),
			org.jooq.impl.SQLDataType.CHAR(36), this, "");

	/**
	 * The column <code>trades.trades</code>.
	 */
	public final TableField<TradesRecord, Long> TRADES_ = createField(DSL.name("trades"), org.jooq.impl.SQLDataType.BIGINT,
			this, "");

	/**
	 * Create a <code>trades</code> table reference
	 */
	public Trades() {
		this(DSL.name("trades"), null);
	}

	/**
	 * Create an aliased <code>trades</code> table reference
	 */
	public Trades(String alias) {
		this(DSL.name(alias), TRADES);
	}

	/**
	 * Create an aliased <code>trades</code> table reference
	 */
	public Trades(Name alias) {
		this(alias, TRADES);
	}

	private Trades(Name alias, Table<TradesRecord> aliased) {
		this(alias, aliased, null);
	}

	private Trades(Name alias, Table<TradesRecord> aliased, Field<?>[] parameters) {
		super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
	}

	public <O extends Record> Trades(Table<O> child, ForeignKey<O, TradesRecord> key) {
		super(child, key, TRADES);
	}

	@Override
	public Schema getSchema() {
		return DefaultSchema.DEFAULT_SCHEMA;
	}

	@Override
	public UniqueKey<TradesRecord> getPrimaryKey() {
		return Keys.PK_TRADES;
	}

	@Override
	public List<UniqueKey<TradesRecord>> getKeys() {
		return Arrays.<UniqueKey<TradesRecord>> asList(Keys.PK_TRADES);
	}

	@Override
	public Trades as(String alias) {
		return new Trades(DSL.name(alias), this);
	}

	@Override
	public Trades as(Name alias) {
		return new Trades(alias, this);
	}

	/**
	 * Rename this table
	 */
	@Override
	public Trades rename(String name) {
		return new Trades(DSL.name(name), null);
	}

	/**
	 * Rename this table
	 */
	@Override
	public Trades rename(Name name) {
		return new Trades(name, null);
	}

	// -------------------------------------------------------------------------
	// Row2 type methods
	// -------------------------------------------------------------------------

	@Override
	public Row2<String, Long> fieldsRow() {
		return (Row2) super.fieldsRow();
	}
}
