/*
 * This file is generated by jOOQ.
 */
package com.hm.achievement.db.tables;

import com.hm.achievement.db.DefaultSchema;
import com.hm.achievement.db.Keys;
import com.hm.achievement.db.tables.records.WaterbucketsRecord;

import java.util.Arrays;
import java.util.List;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Row2;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;

/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Waterbuckets extends TableImpl<WaterbucketsRecord> {

	private static final long serialVersionUID = -1017671729;

	/**
	 * The reference instance of <code>waterbuckets</code>
	 */
	public static final Waterbuckets WATERBUCKETS = new Waterbuckets();

	/**
	 * The class holding records for this type
	 */
	@Override
	public Class<WaterbucketsRecord> getRecordType() {
		return WaterbucketsRecord.class;
	}

	/**
	 * The column <code>waterbuckets.playername</code>.
	 */
	public final TableField<WaterbucketsRecord, String> PLAYERNAME = createField(DSL.name("playername"),
			org.jooq.impl.SQLDataType.CHAR(36), this, "");

	/**
	 * The column <code>waterbuckets.waterbuckets</code>.
	 */
	public final TableField<WaterbucketsRecord, Long> WATERBUCKETS_ = createField(DSL.name("waterbuckets"),
			org.jooq.impl.SQLDataType.BIGINT, this, "");

	/**
	 * Create a <code>waterbuckets</code> table reference
	 */
	public Waterbuckets() {
		this(DSL.name("waterbuckets"), null);
	}

	/**
	 * Create an aliased <code>waterbuckets</code> table reference
	 */
	public Waterbuckets(String alias) {
		this(DSL.name(alias), WATERBUCKETS);
	}

	/**
	 * Create an aliased <code>waterbuckets</code> table reference
	 */
	public Waterbuckets(Name alias) {
		this(alias, WATERBUCKETS);
	}

	private Waterbuckets(Name alias, Table<WaterbucketsRecord> aliased) {
		this(alias, aliased, null);
	}

	private Waterbuckets(Name alias, Table<WaterbucketsRecord> aliased, Field<?>[] parameters) {
		super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
	}

	public <O extends Record> Waterbuckets(Table<O> child, ForeignKey<O, WaterbucketsRecord> key) {
		super(child, key, WATERBUCKETS);
	}

	@Override
	public Schema getSchema() {
		return DefaultSchema.DEFAULT_SCHEMA;
	}

	@Override
	public UniqueKey<WaterbucketsRecord> getPrimaryKey() {
		return Keys.PK_WATERBUCKETS;
	}

	@Override
	public List<UniqueKey<WaterbucketsRecord>> getKeys() {
		return Arrays.<UniqueKey<WaterbucketsRecord>> asList(Keys.PK_WATERBUCKETS);
	}

	@Override
	public Waterbuckets as(String alias) {
		return new Waterbuckets(DSL.name(alias), this);
	}

	@Override
	public Waterbuckets as(Name alias) {
		return new Waterbuckets(alias, this);
	}

	/**
	 * Rename this table
	 */
	@Override
	public Waterbuckets rename(String name) {
		return new Waterbuckets(DSL.name(name), null);
	}

	/**
	 * Rename this table
	 */
	@Override
	public Waterbuckets rename(Name name) {
		return new Waterbuckets(name, null);
	}

	// -------------------------------------------------------------------------
	// Row2 type methods
	// -------------------------------------------------------------------------

	@Override
	public Row2<String, Long> fieldsRow() {
		return (Row2) super.fieldsRow();
	}
}
