/*
 * This file is generated by jOOQ.
 */
package com.hm.achievement.db.tables.records;

import com.hm.achievement.db.tables.Beds;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record2;
import org.jooq.Row2;
import org.jooq.impl.UpdatableRecordImpl;

/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class BedsRecord extends UpdatableRecordImpl<BedsRecord> implements Record2<String, Long> {

	private static final long serialVersionUID = -2143089936;

	/**
	 * Setter for <code>beds.playername</code>.
	 */
	public void setPlayername(String value) {
		set(0, value);
	}

	/**
	 * Getter for <code>beds.playername</code>.
	 */
	public String getPlayername() {
		return (String) get(0);
	}

	/**
	 * Setter for <code>beds.beds</code>.
	 */
	public void setBeds(Long value) {
		set(1, value);
	}

	/**
	 * Getter for <code>beds.beds</code>.
	 */
	public Long getBeds() {
		return (Long) get(1);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	@Override
	public Record1<String> key() {
		return (Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record2 type implementation
	// -------------------------------------------------------------------------

	@Override
	public Row2<String, Long> fieldsRow() {
		return (Row2) super.fieldsRow();
	}

	@Override
	public Row2<String, Long> valuesRow() {
		return (Row2) super.valuesRow();
	}

	@Override
	public Field<String> field1() {
		return Beds.BEDS.PLAYERNAME;
	}

	@Override
	public Field<Long> field2() {
		return Beds.BEDS.BEDS_;
	}

	@Override
	public String component1() {
		return getPlayername();
	}

	@Override
	public Long component2() {
		return getBeds();
	}

	@Override
	public String value1() {
		return getPlayername();
	}

	@Override
	public Long value2() {
		return getBeds();
	}

	@Override
	public BedsRecord value1(String value) {
		setPlayername(value);
		return this;
	}

	@Override
	public BedsRecord value2(Long value) {
		setBeds(value);
		return this;
	}

	@Override
	public BedsRecord values(String value1, Long value2) {
		value1(value1);
		value2(value2);
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached BedsRecord
	 */
	public BedsRecord() {
		super(Beds.BEDS);
	}

	/**
	 * Create a detached, initialised BedsRecord
	 */
	public BedsRecord(String playername, Long beds) {
		super(Beds.BEDS);

		set(0, playername);
		set(1, beds);
	}
}
