/*
 * This file is generated by jOOQ.
 */
package com.hm.achievement.db.tables.records;

import com.hm.achievement.db.tables.Breaks;

import org.jooq.Field;
import org.jooq.Record2;
import org.jooq.Record3;
import org.jooq.Row3;
import org.jooq.impl.UpdatableRecordImpl;

/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class BreaksRecord extends UpdatableRecordImpl<BreaksRecord> implements Record3<String, String, Integer> {

	private static final long serialVersionUID = -1925916535;

	/**
	 * Setter for <code>breaks.playername</code>.
	 */
	public void setPlayername(String value) {
		set(0, value);
	}

	/**
	 * Getter for <code>breaks.playername</code>.
	 */
	public String getPlayername() {
		return (String) get(0);
	}

	/**
	 * Setter for <code>breaks.blockid</code>.
	 */
	public void setBlockid(String value) {
		set(1, value);
	}

	/**
	 * Getter for <code>breaks.blockid</code>.
	 */
	public String getBlockid() {
		return (String) get(1);
	}

	/**
	 * Setter for <code>breaks.breaks</code>.
	 */
	public void setBreaks(Integer value) {
		set(2, value);
	}

	/**
	 * Getter for <code>breaks.breaks</code>.
	 */
	public Integer getBreaks() {
		return (Integer) get(2);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	@Override
	public Record2<String, String> key() {
		return (Record2) super.key();
	}

	// -------------------------------------------------------------------------
	// Record3 type implementation
	// -------------------------------------------------------------------------

	@Override
	public Row3<String, String, Integer> fieldsRow() {
		return (Row3) super.fieldsRow();
	}

	@Override
	public Row3<String, String, Integer> valuesRow() {
		return (Row3) super.valuesRow();
	}

	@Override
	public Field<String> field1() {
		return Breaks.BREAKS.PLAYERNAME;
	}

	@Override
	public Field<String> field2() {
		return Breaks.BREAKS.BLOCKID;
	}

	@Override
	public Field<Integer> field3() {
		return Breaks.BREAKS.BREAKS_;
	}

	@Override
	public String component1() {
		return getPlayername();
	}

	@Override
	public String component2() {
		return getBlockid();
	}

	@Override
	public Integer component3() {
		return getBreaks();
	}

	@Override
	public String value1() {
		return getPlayername();
	}

	@Override
	public String value2() {
		return getBlockid();
	}

	@Override
	public Integer value3() {
		return getBreaks();
	}

	@Override
	public BreaksRecord value1(String value) {
		setPlayername(value);
		return this;
	}

	@Override
	public BreaksRecord value2(String value) {
		setBlockid(value);
		return this;
	}

	@Override
	public BreaksRecord value3(Integer value) {
		setBreaks(value);
		return this;
	}

	@Override
	public BreaksRecord values(String value1, String value2, Integer value3) {
		value1(value1);
		value2(value2);
		value3(value3);
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached BreaksRecord
	 */
	public BreaksRecord() {
		super(Breaks.BREAKS);
	}

	/**
	 * Create a detached, initialised BreaksRecord
	 */
	public BreaksRecord(String playername, String blockid, Integer breaks) {
		super(Breaks.BREAKS);

		set(0, playername);
		set(1, blockid);
		set(2, breaks);
	}
}
