/*
 * This file is generated by jOOQ.
 */
package com.hm.achievement.db.tables.records;

import com.hm.achievement.db.tables.Breeding;

import org.jooq.Field;
import org.jooq.Record2;
import org.jooq.Record3;
import org.jooq.Row3;
import org.jooq.impl.UpdatableRecordImpl;

/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class BreedingRecord extends UpdatableRecordImpl<BreedingRecord> implements Record3<String, String, Integer> {

	private static final long serialVersionUID = -310683015;

	/**
	 * Setter for <code>breeding.playername</code>.
	 */
	public void setPlayername(String value) {
		set(0, value);
	}

	/**
	 * Getter for <code>breeding.playername</code>.
	 */
	public String getPlayername() {
		return (String) get(0);
	}

	/**
	 * Setter for <code>breeding.mobname</code>.
	 */
	public void setMobname(String value) {
		set(1, value);
	}

	/**
	 * Getter for <code>breeding.mobname</code>.
	 */
	public String getMobname() {
		return (String) get(1);
	}

	/**
	 * Setter for <code>breeding.breeding</code>.
	 */
	public void setBreeding(Integer value) {
		set(2, value);
	}

	/**
	 * Getter for <code>breeding.breeding</code>.
	 */
	public Integer getBreeding() {
		return (Integer) get(2);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	@Override
	public Record2<String, String> key() {
		return (Record2) super.key();
	}

	// -------------------------------------------------------------------------
	// Record3 type implementation
	// -------------------------------------------------------------------------

	@Override
	public Row3<String, String, Integer> fieldsRow() {
		return (Row3) super.fieldsRow();
	}

	@Override
	public Row3<String, String, Integer> valuesRow() {
		return (Row3) super.valuesRow();
	}

	@Override
	public Field<String> field1() {
		return Breeding.BREEDING.PLAYERNAME;
	}

	@Override
	public Field<String> field2() {
		return Breeding.BREEDING.MOBNAME;
	}

	@Override
	public Field<Integer> field3() {
		return Breeding.BREEDING.BREEDING_;
	}

	@Override
	public String component1() {
		return getPlayername();
	}

	@Override
	public String component2() {
		return getMobname();
	}

	@Override
	public Integer component3() {
		return getBreeding();
	}

	@Override
	public String value1() {
		return getPlayername();
	}

	@Override
	public String value2() {
		return getMobname();
	}

	@Override
	public Integer value3() {
		return getBreeding();
	}

	@Override
	public BreedingRecord value1(String value) {
		setPlayername(value);
		return this;
	}

	@Override
	public BreedingRecord value2(String value) {
		setMobname(value);
		return this;
	}

	@Override
	public BreedingRecord value3(Integer value) {
		setBreeding(value);
		return this;
	}

	@Override
	public BreedingRecord values(String value1, String value2, Integer value3) {
		value1(value1);
		value2(value2);
		value3(value3);
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached BreedingRecord
	 */
	public BreedingRecord() {
		super(Breeding.BREEDING);
	}

	/**
	 * Create a detached, initialised BreedingRecord
	 */
	public BreedingRecord(String playername, String mobname, Integer breeding) {
		super(Breeding.BREEDING);

		set(0, playername);
		set(1, mobname);
		set(2, breeding);
	}
}
