/*
 * This file is generated by jOOQ.
 */
package com.hm.achievement.db.tables.records;

import com.hm.achievement.db.tables.Crafts;

import org.jooq.Field;
import org.jooq.Record2;
import org.jooq.Record3;
import org.jooq.Row3;
import org.jooq.impl.UpdatableRecordImpl;

/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class CraftsRecord extends UpdatableRecordImpl<CraftsRecord> implements Record3<String, String, Integer> {

	private static final long serialVersionUID = -1045554288;

	/**
	 * Setter for <code>crafts.playername</code>.
	 */
	public void setPlayername(String value) {
		set(0, value);
	}

	/**
	 * Getter for <code>crafts.playername</code>.
	 */
	public String getPlayername() {
		return (String) get(0);
	}

	/**
	 * Setter for <code>crafts.item</code>.
	 */
	public void setItem(String value) {
		set(1, value);
	}

	/**
	 * Getter for <code>crafts.item</code>.
	 */
	public String getItem() {
		return (String) get(1);
	}

	/**
	 * Setter for <code>crafts.crafts</code>.
	 */
	public void setCrafts(Integer value) {
		set(2, value);
	}

	/**
	 * Getter for <code>crafts.crafts</code>.
	 */
	public Integer getCrafts() {
		return (Integer) get(2);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	@Override
	public Record2<String, String> key() {
		return (Record2) super.key();
	}

	// -------------------------------------------------------------------------
	// Record3 type implementation
	// -------------------------------------------------------------------------

	@Override
	public Row3<String, String, Integer> fieldsRow() {
		return (Row3) super.fieldsRow();
	}

	@Override
	public Row3<String, String, Integer> valuesRow() {
		return (Row3) super.valuesRow();
	}

	@Override
	public Field<String> field1() {
		return Crafts.CRAFTS.PLAYERNAME;
	}

	@Override
	public Field<String> field2() {
		return Crafts.CRAFTS.ITEM;
	}

	@Override
	public Field<Integer> field3() {
		return Crafts.CRAFTS.CRAFTS_;
	}

	@Override
	public String component1() {
		return getPlayername();
	}

	@Override
	public String component2() {
		return getItem();
	}

	@Override
	public Integer component3() {
		return getCrafts();
	}

	@Override
	public String value1() {
		return getPlayername();
	}

	@Override
	public String value2() {
		return getItem();
	}

	@Override
	public Integer value3() {
		return getCrafts();
	}

	@Override
	public CraftsRecord value1(String value) {
		setPlayername(value);
		return this;
	}

	@Override
	public CraftsRecord value2(String value) {
		setItem(value);
		return this;
	}

	@Override
	public CraftsRecord value3(Integer value) {
		setCrafts(value);
		return this;
	}

	@Override
	public CraftsRecord values(String value1, String value2, Integer value3) {
		value1(value1);
		value2(value2);
		value3(value3);
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached CraftsRecord
	 */
	public CraftsRecord() {
		super(Crafts.CRAFTS);
	}

	/**
	 * Create a detached, initialised CraftsRecord
	 */
	public CraftsRecord(String playername, String item, Integer crafts) {
		super(Crafts.CRAFTS);

		set(0, playername);
		set(1, item);
		set(2, crafts);
	}
}
