/*
 * This file is generated by jOOQ.
 */
package com.hm.achievement.db.tables.records;

import com.hm.achievement.db.tables.Custom;

import org.jooq.Field;
import org.jooq.Record2;
import org.jooq.Record3;
import org.jooq.Row3;
import org.jooq.impl.UpdatableRecordImpl;

/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class CustomRecord extends UpdatableRecordImpl<CustomRecord> implements Record3<String, String, Integer> {

	private static final long serialVersionUID = 1448531038;

	/**
	 * Setter for <code>custom.playername</code>.
	 */
	public void setPlayername(String value) {
		set(0, value);
	}

	/**
	 * Getter for <code>custom.playername</code>.
	 */
	public String getPlayername() {
		return (String) get(0);
	}

	/**
	 * Setter for <code>custom.customname</code>.
	 */
	public void setCustomname(String value) {
		set(1, value);
	}

	/**
	 * Getter for <code>custom.customname</code>.
	 */
	public String getCustomname() {
		return (String) get(1);
	}

	/**
	 * Setter for <code>custom.custom</code>.
	 */
	public void setCustom(Integer value) {
		set(2, value);
	}

	/**
	 * Getter for <code>custom.custom</code>.
	 */
	public Integer getCustom() {
		return (Integer) get(2);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	@Override
	public Record2<String, String> key() {
		return (Record2) super.key();
	}

	// -------------------------------------------------------------------------
	// Record3 type implementation
	// -------------------------------------------------------------------------

	@Override
	public Row3<String, String, Integer> fieldsRow() {
		return (Row3) super.fieldsRow();
	}

	@Override
	public Row3<String, String, Integer> valuesRow() {
		return (Row3) super.valuesRow();
	}

	@Override
	public Field<String> field1() {
		return Custom.CUSTOM.PLAYERNAME;
	}

	@Override
	public Field<String> field2() {
		return Custom.CUSTOM.CUSTOMNAME;
	}

	@Override
	public Field<Integer> field3() {
		return Custom.CUSTOM.CUSTOM_;
	}

	@Override
	public String component1() {
		return getPlayername();
	}

	@Override
	public String component2() {
		return getCustomname();
	}

	@Override
	public Integer component3() {
		return getCustom();
	}

	@Override
	public String value1() {
		return getPlayername();
	}

	@Override
	public String value2() {
		return getCustomname();
	}

	@Override
	public Integer value3() {
		return getCustom();
	}

	@Override
	public CustomRecord value1(String value) {
		setPlayername(value);
		return this;
	}

	@Override
	public CustomRecord value2(String value) {
		setCustomname(value);
		return this;
	}

	@Override
	public CustomRecord value3(Integer value) {
		setCustom(value);
		return this;
	}

	@Override
	public CustomRecord values(String value1, String value2, Integer value3) {
		value1(value1);
		value2(value2);
		value3(value3);
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached CustomRecord
	 */
	public CustomRecord() {
		super(Custom.CUSTOM);
	}

	/**
	 * Create a detached, initialised CustomRecord
	 */
	public CustomRecord(String playername, String customname, Integer custom) {
		super(Custom.CUSTOM);

		set(0, playername);
		set(1, customname);
		set(2, custom);
	}
}
