/*
 * This file is generated by jOOQ.
 */
package com.hm.achievement.db.tables.records;

import com.hm.achievement.db.tables.Distanceboat;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record2;
import org.jooq.Row2;
import org.jooq.impl.UpdatableRecordImpl;

/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class DistanceboatRecord extends UpdatableRecordImpl<DistanceboatRecord> implements Record2<String, Long> {

	private static final long serialVersionUID = 1729619182;

	/**
	 * Setter for <code>distanceboat.playername</code>.
	 */
	public void setPlayername(String value) {
		set(0, value);
	}

	/**
	 * Getter for <code>distanceboat.playername</code>.
	 */
	public String getPlayername() {
		return (String) get(0);
	}

	/**
	 * Setter for <code>distanceboat.distanceboat</code>.
	 */
	public void setDistanceboat(Long value) {
		set(1, value);
	}

	/**
	 * Getter for <code>distanceboat.distanceboat</code>.
	 */
	public Long getDistanceboat() {
		return (Long) get(1);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	@Override
	public Record1<String> key() {
		return (Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record2 type implementation
	// -------------------------------------------------------------------------

	@Override
	public Row2<String, Long> fieldsRow() {
		return (Row2) super.fieldsRow();
	}

	@Override
	public Row2<String, Long> valuesRow() {
		return (Row2) super.valuesRow();
	}

	@Override
	public Field<String> field1() {
		return Distanceboat.DISTANCEBOAT.PLAYERNAME;
	}

	@Override
	public Field<Long> field2() {
		return Distanceboat.DISTANCEBOAT.DISTANCEBOAT_;
	}

	@Override
	public String component1() {
		return getPlayername();
	}

	@Override
	public Long component2() {
		return getDistanceboat();
	}

	@Override
	public String value1() {
		return getPlayername();
	}

	@Override
	public Long value2() {
		return getDistanceboat();
	}

	@Override
	public DistanceboatRecord value1(String value) {
		setPlayername(value);
		return this;
	}

	@Override
	public DistanceboatRecord value2(Long value) {
		setDistanceboat(value);
		return this;
	}

	@Override
	public DistanceboatRecord values(String value1, Long value2) {
		value1(value1);
		value2(value2);
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached DistanceboatRecord
	 */
	public DistanceboatRecord() {
		super(Distanceboat.DISTANCEBOAT);
	}

	/**
	 * Create a detached, initialised DistanceboatRecord
	 */
	public DistanceboatRecord(String playername, Long distanceboat) {
		super(Distanceboat.DISTANCEBOAT);

		set(0, playername);
		set(1, distanceboat);
	}
}
