/*
 * This file is generated by jOOQ.
 */
package com.hm.achievement.db.tables.records;

import com.hm.achievement.db.tables.Distancegliding;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record2;
import org.jooq.Row2;
import org.jooq.impl.UpdatableRecordImpl;

/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class DistanceglidingRecord extends UpdatableRecordImpl<DistanceglidingRecord> implements Record2<String, Long> {

	private static final long serialVersionUID = 709305568;

	/**
	 * Setter for <code>distancegliding.playername</code>.
	 */
	public void setPlayername(String value) {
		set(0, value);
	}

	/**
	 * Getter for <code>distancegliding.playername</code>.
	 */
	public String getPlayername() {
		return (String) get(0);
	}

	/**
	 * Setter for <code>distancegliding.distancegliding</code>.
	 */
	public void setDistancegliding(Long value) {
		set(1, value);
	}

	/**
	 * Getter for <code>distancegliding.distancegliding</code>.
	 */
	public Long getDistancegliding() {
		return (Long) get(1);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	@Override
	public Record1<String> key() {
		return (Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record2 type implementation
	// -------------------------------------------------------------------------

	@Override
	public Row2<String, Long> fieldsRow() {
		return (Row2) super.fieldsRow();
	}

	@Override
	public Row2<String, Long> valuesRow() {
		return (Row2) super.valuesRow();
	}

	@Override
	public Field<String> field1() {
		return Distancegliding.DISTANCEGLIDING.PLAYERNAME;
	}

	@Override
	public Field<Long> field2() {
		return Distancegliding.DISTANCEGLIDING.DISTANCEGLIDING_;
	}

	@Override
	public String component1() {
		return getPlayername();
	}

	@Override
	public Long component2() {
		return getDistancegliding();
	}

	@Override
	public String value1() {
		return getPlayername();
	}

	@Override
	public Long value2() {
		return getDistancegliding();
	}

	@Override
	public DistanceglidingRecord value1(String value) {
		setPlayername(value);
		return this;
	}

	@Override
	public DistanceglidingRecord value2(Long value) {
		setDistancegliding(value);
		return this;
	}

	@Override
	public DistanceglidingRecord values(String value1, Long value2) {
		value1(value1);
		value2(value2);
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached DistanceglidingRecord
	 */
	public DistanceglidingRecord() {
		super(Distancegliding.DISTANCEGLIDING);
	}

	/**
	 * Create a detached, initialised DistanceglidingRecord
	 */
	public DistanceglidingRecord(String playername, Long distancegliding) {
		super(Distancegliding.DISTANCEGLIDING);

		set(0, playername);
		set(1, distancegliding);
	}
}
