/*
 * This file is generated by jOOQ.
 */
package com.hm.achievement.db.tables.records;

import com.hm.achievement.db.tables.Distancellama;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record2;
import org.jooq.Row2;
import org.jooq.impl.UpdatableRecordImpl;

/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class DistancellamaRecord extends UpdatableRecordImpl<DistancellamaRecord> implements Record2<String, Long> {

	private static final long serialVersionUID = 1741829250;

	/**
	 * Setter for <code>distancellama.playername</code>.
	 */
	public void setPlayername(String value) {
		set(0, value);
	}

	/**
	 * Getter for <code>distancellama.playername</code>.
	 */
	public String getPlayername() {
		return (String) get(0);
	}

	/**
	 * Setter for <code>distancellama.distancellama</code>.
	 */
	public void setDistancellama(Long value) {
		set(1, value);
	}

	/**
	 * Getter for <code>distancellama.distancellama</code>.
	 */
	public Long getDistancellama() {
		return (Long) get(1);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	@Override
	public Record1<String> key() {
		return (Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record2 type implementation
	// -------------------------------------------------------------------------

	@Override
	public Row2<String, Long> fieldsRow() {
		return (Row2) super.fieldsRow();
	}

	@Override
	public Row2<String, Long> valuesRow() {
		return (Row2) super.valuesRow();
	}

	@Override
	public Field<String> field1() {
		return Distancellama.DISTANCELLAMA.PLAYERNAME;
	}

	@Override
	public Field<Long> field2() {
		return Distancellama.DISTANCELLAMA.DISTANCELLAMA_;
	}

	@Override
	public String component1() {
		return getPlayername();
	}

	@Override
	public Long component2() {
		return getDistancellama();
	}

	@Override
	public String value1() {
		return getPlayername();
	}

	@Override
	public Long value2() {
		return getDistancellama();
	}

	@Override
	public DistancellamaRecord value1(String value) {
		setPlayername(value);
		return this;
	}

	@Override
	public DistancellamaRecord value2(Long value) {
		setDistancellama(value);
		return this;
	}

	@Override
	public DistancellamaRecord values(String value1, Long value2) {
		value1(value1);
		value2(value2);
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached DistancellamaRecord
	 */
	public DistancellamaRecord() {
		super(Distancellama.DISTANCELLAMA);
	}

	/**
	 * Create a detached, initialised DistancellamaRecord
	 */
	public DistancellamaRecord(String playername, Long distancellama) {
		super(Distancellama.DISTANCELLAMA);

		set(0, playername);
		set(1, distancellama);
	}
}
