/*
 * This file is generated by jOOQ.
 */
package com.hm.achievement.db.tables.records;

import com.hm.achievement.db.tables.Drops;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record2;
import org.jooq.Row2;
import org.jooq.impl.UpdatableRecordImpl;

/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class DropsRecord extends UpdatableRecordImpl<DropsRecord> implements Record2<String, Long> {

	private static final long serialVersionUID = -148300070;

	/**
	 * Setter for <code>drops.playername</code>.
	 */
	public void setPlayername(String value) {
		set(0, value);
	}

	/**
	 * Getter for <code>drops.playername</code>.
	 */
	public String getPlayername() {
		return (String) get(0);
	}

	/**
	 * Setter for <code>drops.drops</code>.
	 */
	public void setDrops(Long value) {
		set(1, value);
	}

	/**
	 * Getter for <code>drops.drops</code>.
	 */
	public Long getDrops() {
		return (Long) get(1);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	@Override
	public Record1<String> key() {
		return (Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record2 type implementation
	// -------------------------------------------------------------------------

	@Override
	public Row2<String, Long> fieldsRow() {
		return (Row2) super.fieldsRow();
	}

	@Override
	public Row2<String, Long> valuesRow() {
		return (Row2) super.valuesRow();
	}

	@Override
	public Field<String> field1() {
		return Drops.DROPS.PLAYERNAME;
	}

	@Override
	public Field<Long> field2() {
		return Drops.DROPS.DROPS_;
	}

	@Override
	public String component1() {
		return getPlayername();
	}

	@Override
	public Long component2() {
		return getDrops();
	}

	@Override
	public String value1() {
		return getPlayername();
	}

	@Override
	public Long value2() {
		return getDrops();
	}

	@Override
	public DropsRecord value1(String value) {
		setPlayername(value);
		return this;
	}

	@Override
	public DropsRecord value2(Long value) {
		setDrops(value);
		return this;
	}

	@Override
	public DropsRecord values(String value1, Long value2) {
		value1(value1);
		value2(value2);
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached DropsRecord
	 */
	public DropsRecord() {
		super(Drops.DROPS);
	}

	/**
	 * Create a detached, initialised DropsRecord
	 */
	public DropsRecord(String playername, Long drops) {
		super(Drops.DROPS);

		set(0, playername);
		set(1, drops);
	}
}
