/*
 * This file is generated by jOOQ.
 */
package com.hm.achievement.db.tables.records;

import com.hm.achievement.db.tables.Eatenitems;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record2;
import org.jooq.Row2;
import org.jooq.impl.UpdatableRecordImpl;

/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class EatenitemsRecord extends UpdatableRecordImpl<EatenitemsRecord> implements Record2<String, Long> {

	private static final long serialVersionUID = -1989664750;

	/**
	 * Setter for <code>eatenitems.playername</code>.
	 */
	public void setPlayername(String value) {
		set(0, value);
	}

	/**
	 * Getter for <code>eatenitems.playername</code>.
	 */
	public String getPlayername() {
		return (String) get(0);
	}

	/**
	 * Setter for <code>eatenitems.eatenitems</code>.
	 */
	public void setEatenitems(Long value) {
		set(1, value);
	}

	/**
	 * Getter for <code>eatenitems.eatenitems</code>.
	 */
	public Long getEatenitems() {
		return (Long) get(1);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	@Override
	public Record1<String> key() {
		return (Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record2 type implementation
	// -------------------------------------------------------------------------

	@Override
	public Row2<String, Long> fieldsRow() {
		return (Row2) super.fieldsRow();
	}

	@Override
	public Row2<String, Long> valuesRow() {
		return (Row2) super.valuesRow();
	}

	@Override
	public Field<String> field1() {
		return Eatenitems.EATENITEMS.PLAYERNAME;
	}

	@Override
	public Field<Long> field2() {
		return Eatenitems.EATENITEMS.EATENITEMS_;
	}

	@Override
	public String component1() {
		return getPlayername();
	}

	@Override
	public Long component2() {
		return getEatenitems();
	}

	@Override
	public String value1() {
		return getPlayername();
	}

	@Override
	public Long value2() {
		return getEatenitems();
	}

	@Override
	public EatenitemsRecord value1(String value) {
		setPlayername(value);
		return this;
	}

	@Override
	public EatenitemsRecord value2(Long value) {
		setEatenitems(value);
		return this;
	}

	@Override
	public EatenitemsRecord values(String value1, Long value2) {
		value1(value1);
		value2(value2);
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached EatenitemsRecord
	 */
	public EatenitemsRecord() {
		super(Eatenitems.EATENITEMS);
	}

	/**
	 * Create a detached, initialised EatenitemsRecord
	 */
	public EatenitemsRecord(String playername, Long eatenitems) {
		super(Eatenitems.EATENITEMS);

		set(0, playername);
		set(1, eatenitems);
	}
}
