/*
 * This file is generated by jOOQ.
 */
package com.hm.achievement.db.tables.records;

import com.hm.achievement.db.tables.Fertilising;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record2;
import org.jooq.Row2;
import org.jooq.impl.UpdatableRecordImpl;

/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class FertilisingRecord extends UpdatableRecordImpl<FertilisingRecord> implements Record2<String, Long> {

	private static final long serialVersionUID = 1410058554;

	/**
	 * Setter for <code>fertilising.playername</code>.
	 */
	public void setPlayername(String value) {
		set(0, value);
	}

	/**
	 * Getter for <code>fertilising.playername</code>.
	 */
	public String getPlayername() {
		return (String) get(0);
	}

	/**
	 * Setter for <code>fertilising.fertilising</code>.
	 */
	public void setFertilising(Long value) {
		set(1, value);
	}

	/**
	 * Getter for <code>fertilising.fertilising</code>.
	 */
	public Long getFertilising() {
		return (Long) get(1);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	@Override
	public Record1<String> key() {
		return (Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record2 type implementation
	// -------------------------------------------------------------------------

	@Override
	public Row2<String, Long> fieldsRow() {
		return (Row2) super.fieldsRow();
	}

	@Override
	public Row2<String, Long> valuesRow() {
		return (Row2) super.valuesRow();
	}

	@Override
	public Field<String> field1() {
		return Fertilising.FERTILISING.PLAYERNAME;
	}

	@Override
	public Field<Long> field2() {
		return Fertilising.FERTILISING.FERTILISING_;
	}

	@Override
	public String component1() {
		return getPlayername();
	}

	@Override
	public Long component2() {
		return getFertilising();
	}

	@Override
	public String value1() {
		return getPlayername();
	}

	@Override
	public Long value2() {
		return getFertilising();
	}

	@Override
	public FertilisingRecord value1(String value) {
		setPlayername(value);
		return this;
	}

	@Override
	public FertilisingRecord value2(Long value) {
		setFertilising(value);
		return this;
	}

	@Override
	public FertilisingRecord values(String value1, Long value2) {
		value1(value1);
		value2(value2);
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached FertilisingRecord
	 */
	public FertilisingRecord() {
		super(Fertilising.FERTILISING);
	}

	/**
	 * Create a detached, initialised FertilisingRecord
	 */
	public FertilisingRecord(String playername, Long fertilising) {
		super(Fertilising.FERTILISING);

		set(0, playername);
		set(1, fertilising);
	}
}
