/*
 * This file is generated by jOOQ.
 */
package com.hm.achievement.db.tables.records;

import com.hm.achievement.db.tables.Fish;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record2;
import org.jooq.Row2;
import org.jooq.impl.UpdatableRecordImpl;

/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class FishRecord extends UpdatableRecordImpl<FishRecord> implements Record2<String, Long> {

	private static final long serialVersionUID = 323372780;

	/**
	 * Setter for <code>fish.playername</code>.
	 */
	public void setPlayername(String value) {
		set(0, value);
	}

	/**
	 * Getter for <code>fish.playername</code>.
	 */
	public String getPlayername() {
		return (String) get(0);
	}

	/**
	 * Setter for <code>fish.fish</code>.
	 */
	public void setFish(Long value) {
		set(1, value);
	}

	/**
	 * Getter for <code>fish.fish</code>.
	 */
	public Long getFish() {
		return (Long) get(1);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	@Override
	public Record1<String> key() {
		return (Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record2 type implementation
	// -------------------------------------------------------------------------

	@Override
	public Row2<String, Long> fieldsRow() {
		return (Row2) super.fieldsRow();
	}

	@Override
	public Row2<String, Long> valuesRow() {
		return (Row2) super.valuesRow();
	}

	@Override
	public Field<String> field1() {
		return Fish.FISH.PLAYERNAME;
	}

	@Override
	public Field<Long> field2() {
		return Fish.FISH.FISH_;
	}

	@Override
	public String component1() {
		return getPlayername();
	}

	@Override
	public Long component2() {
		return getFish();
	}

	@Override
	public String value1() {
		return getPlayername();
	}

	@Override
	public Long value2() {
		return getFish();
	}

	@Override
	public FishRecord value1(String value) {
		setPlayername(value);
		return this;
	}

	@Override
	public FishRecord value2(Long value) {
		setFish(value);
		return this;
	}

	@Override
	public FishRecord values(String value1, Long value2) {
		value1(value1);
		value2(value2);
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached FishRecord
	 */
	public FishRecord() {
		super(Fish.FISH);
	}

	/**
	 * Create a detached, initialised FishRecord
	 */
	public FishRecord(String playername, Long fish) {
		super(Fish.FISH);

		set(0, playername);
		set(1, fish);
	}
}
