/*
 * This file is generated by jOOQ.
 */
package com.hm.achievement.db.tables.records;

import com.hm.achievement.db.tables.Hoeplowing;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record2;
import org.jooq.Row2;
import org.jooq.impl.UpdatableRecordImpl;

/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class HoeplowingRecord extends UpdatableRecordImpl<HoeplowingRecord> implements Record2<String, Long> {

	private static final long serialVersionUID = -1194761796;

	/**
	 * Setter for <code>hoeplowing.playername</code>.
	 */
	public void setPlayername(String value) {
		set(0, value);
	}

	/**
	 * Getter for <code>hoeplowing.playername</code>.
	 */
	public String getPlayername() {
		return (String) get(0);
	}

	/**
	 * Setter for <code>hoeplowing.hoeplowing</code>.
	 */
	public void setHoeplowing(Long value) {
		set(1, value);
	}

	/**
	 * Getter for <code>hoeplowing.hoeplowing</code>.
	 */
	public Long getHoeplowing() {
		return (Long) get(1);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	@Override
	public Record1<String> key() {
		return (Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record2 type implementation
	// -------------------------------------------------------------------------

	@Override
	public Row2<String, Long> fieldsRow() {
		return (Row2) super.fieldsRow();
	}

	@Override
	public Row2<String, Long> valuesRow() {
		return (Row2) super.valuesRow();
	}

	@Override
	public Field<String> field1() {
		return Hoeplowing.HOEPLOWING.PLAYERNAME;
	}

	@Override
	public Field<Long> field2() {
		return Hoeplowing.HOEPLOWING.HOEPLOWING_;
	}

	@Override
	public String component1() {
		return getPlayername();
	}

	@Override
	public Long component2() {
		return getHoeplowing();
	}

	@Override
	public String value1() {
		return getPlayername();
	}

	@Override
	public Long value2() {
		return getHoeplowing();
	}

	@Override
	public HoeplowingRecord value1(String value) {
		setPlayername(value);
		return this;
	}

	@Override
	public HoeplowingRecord value2(Long value) {
		setHoeplowing(value);
		return this;
	}

	@Override
	public HoeplowingRecord values(String value1, Long value2) {
		value1(value1);
		value2(value2);
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached HoeplowingRecord
	 */
	public HoeplowingRecord() {
		super(Hoeplowing.HOEPLOWING);
	}

	/**
	 * Create a detached, initialised HoeplowingRecord
	 */
	public HoeplowingRecord(String playername, Long hoeplowing) {
		super(Hoeplowing.HOEPLOWING);

		set(0, playername);
		set(1, hoeplowing);
	}
}
