/*
 * This file is generated by jOOQ.
 */
package com.hm.achievement.db.tables.records;

import com.hm.achievement.db.tables.Kills;

import org.jooq.Field;
import org.jooq.Record2;
import org.jooq.Record3;
import org.jooq.Row3;
import org.jooq.impl.UpdatableRecordImpl;

/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class KillsRecord extends UpdatableRecordImpl<KillsRecord> implements Record3<String, String, Integer> {

	private static final long serialVersionUID = -642645268;

	/**
	 * Setter for <code>kills.playername</code>.
	 */
	public void setPlayername(String value) {
		set(0, value);
	}

	/**
	 * Getter for <code>kills.playername</code>.
	 */
	public String getPlayername() {
		return (String) get(0);
	}

	/**
	 * Setter for <code>kills.mobname</code>.
	 */
	public void setMobname(String value) {
		set(1, value);
	}

	/**
	 * Getter for <code>kills.mobname</code>.
	 */
	public String getMobname() {
		return (String) get(1);
	}

	/**
	 * Setter for <code>kills.kills</code>.
	 */
	public void setKills(Integer value) {
		set(2, value);
	}

	/**
	 * Getter for <code>kills.kills</code>.
	 */
	public Integer getKills() {
		return (Integer) get(2);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	@Override
	public Record2<String, String> key() {
		return (Record2) super.key();
	}

	// -------------------------------------------------------------------------
	// Record3 type implementation
	// -------------------------------------------------------------------------

	@Override
	public Row3<String, String, Integer> fieldsRow() {
		return (Row3) super.fieldsRow();
	}

	@Override
	public Row3<String, String, Integer> valuesRow() {
		return (Row3) super.valuesRow();
	}

	@Override
	public Field<String> field1() {
		return Kills.KILLS.PLAYERNAME;
	}

	@Override
	public Field<String> field2() {
		return Kills.KILLS.MOBNAME;
	}

	@Override
	public Field<Integer> field3() {
		return Kills.KILLS.KILLS_;
	}

	@Override
	public String component1() {
		return getPlayername();
	}

	@Override
	public String component2() {
		return getMobname();
	}

	@Override
	public Integer component3() {
		return getKills();
	}

	@Override
	public String value1() {
		return getPlayername();
	}

	@Override
	public String value2() {
		return getMobname();
	}

	@Override
	public Integer value3() {
		return getKills();
	}

	@Override
	public KillsRecord value1(String value) {
		setPlayername(value);
		return this;
	}

	@Override
	public KillsRecord value2(String value) {
		setMobname(value);
		return this;
	}

	@Override
	public KillsRecord value3(Integer value) {
		setKills(value);
		return this;
	}

	@Override
	public KillsRecord values(String value1, String value2, Integer value3) {
		value1(value1);
		value2(value2);
		value3(value3);
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached KillsRecord
	 */
	public KillsRecord() {
		super(Kills.KILLS);
	}

	/**
	 * Create a detached, initialised KillsRecord
	 */
	public KillsRecord(String playername, String mobname, Integer kills) {
		super(Kills.KILLS);

		set(0, playername);
		set(1, mobname);
		set(2, kills);
	}
}
