/*
 * This file is generated by jOOQ.
 */
package com.hm.achievement.db.tables.records;

import com.hm.achievement.db.tables.Lavabuckets;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record2;
import org.jooq.Row2;
import org.jooq.impl.UpdatableRecordImpl;

/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class LavabucketsRecord extends UpdatableRecordImpl<LavabucketsRecord> implements Record2<String, Long> {

	private static final long serialVersionUID = -2062954936;

	/**
	 * Setter for <code>lavabuckets.playername</code>.
	 */
	public void setPlayername(String value) {
		set(0, value);
	}

	/**
	 * Getter for <code>lavabuckets.playername</code>.
	 */
	public String getPlayername() {
		return (String) get(0);
	}

	/**
	 * Setter for <code>lavabuckets.lavabuckets</code>.
	 */
	public void setLavabuckets(Long value) {
		set(1, value);
	}

	/**
	 * Getter for <code>lavabuckets.lavabuckets</code>.
	 */
	public Long getLavabuckets() {
		return (Long) get(1);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	@Override
	public Record1<String> key() {
		return (Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record2 type implementation
	// -------------------------------------------------------------------------

	@Override
	public Row2<String, Long> fieldsRow() {
		return (Row2) super.fieldsRow();
	}

	@Override
	public Row2<String, Long> valuesRow() {
		return (Row2) super.valuesRow();
	}

	@Override
	public Field<String> field1() {
		return Lavabuckets.LAVABUCKETS.PLAYERNAME;
	}

	@Override
	public Field<Long> field2() {
		return Lavabuckets.LAVABUCKETS.LAVABUCKETS_;
	}

	@Override
	public String component1() {
		return getPlayername();
	}

	@Override
	public Long component2() {
		return getLavabuckets();
	}

	@Override
	public String value1() {
		return getPlayername();
	}

	@Override
	public Long value2() {
		return getLavabuckets();
	}

	@Override
	public LavabucketsRecord value1(String value) {
		setPlayername(value);
		return this;
	}

	@Override
	public LavabucketsRecord value2(Long value) {
		setLavabuckets(value);
		return this;
	}

	@Override
	public LavabucketsRecord values(String value1, Long value2) {
		value1(value1);
		value2(value2);
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached LavabucketsRecord
	 */
	public LavabucketsRecord() {
		super(Lavabuckets.LAVABUCKETS);
	}

	/**
	 * Create a detached, initialised LavabucketsRecord
	 */
	public LavabucketsRecord(String playername, Long lavabuckets) {
		super(Lavabuckets.LAVABUCKETS);

		set(0, playername);
		set(1, lavabuckets);
	}
}
