/*
 * This file is generated by jOOQ.
 */
package com.hm.achievement.db.tables.records;

import com.hm.achievement.db.tables.Levels;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record2;
import org.jooq.Row2;
import org.jooq.impl.UpdatableRecordImpl;

/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class LevelsRecord extends UpdatableRecordImpl<LevelsRecord> implements Record2<String, Long> {

	private static final long serialVersionUID = -1784078286;

	/**
	 * Setter for <code>levels.playername</code>.
	 */
	public void setPlayername(String value) {
		set(0, value);
	}

	/**
	 * Getter for <code>levels.playername</code>.
	 */
	public String getPlayername() {
		return (String) get(0);
	}

	/**
	 * Setter for <code>levels.levels</code>.
	 */
	public void setLevels(Long value) {
		set(1, value);
	}

	/**
	 * Getter for <code>levels.levels</code>.
	 */
	public Long getLevels() {
		return (Long) get(1);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	@Override
	public Record1<String> key() {
		return (Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record2 type implementation
	// -------------------------------------------------------------------------

	@Override
	public Row2<String, Long> fieldsRow() {
		return (Row2) super.fieldsRow();
	}

	@Override
	public Row2<String, Long> valuesRow() {
		return (Row2) super.valuesRow();
	}

	@Override
	public Field<String> field1() {
		return Levels.LEVELS.PLAYERNAME;
	}

	@Override
	public Field<Long> field2() {
		return Levels.LEVELS.LEVELS_;
	}

	@Override
	public String component1() {
		return getPlayername();
	}

	@Override
	public Long component2() {
		return getLevels();
	}

	@Override
	public String value1() {
		return getPlayername();
	}

	@Override
	public Long value2() {
		return getLevels();
	}

	@Override
	public LevelsRecord value1(String value) {
		setPlayername(value);
		return this;
	}

	@Override
	public LevelsRecord value2(Long value) {
		setLevels(value);
		return this;
	}

	@Override
	public LevelsRecord values(String value1, Long value2) {
		value1(value1);
		value2(value2);
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached LevelsRecord
	 */
	public LevelsRecord() {
		super(Levels.LEVELS);
	}

	/**
	 * Create a detached, initialised LevelsRecord
	 */
	public LevelsRecord(String playername, Long levels) {
		super(Levels.LEVELS);

		set(0, playername);
		set(1, levels);
	}
}
