/*
 * This file is generated by jOOQ.
 */
package com.hm.achievement.db.tables.records;

import com.hm.achievement.db.tables.Milks;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record2;
import org.jooq.Row2;
import org.jooq.impl.UpdatableRecordImpl;

/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class MilksRecord extends UpdatableRecordImpl<MilksRecord> implements Record2<String, Long> {

	private static final long serialVersionUID = -244467438;

	/**
	 * Setter for <code>milks.playername</code>.
	 */
	public void setPlayername(String value) {
		set(0, value);
	}

	/**
	 * Getter for <code>milks.playername</code>.
	 */
	public String getPlayername() {
		return (String) get(0);
	}

	/**
	 * Setter for <code>milks.milks</code>.
	 */
	public void setMilks(Long value) {
		set(1, value);
	}

	/**
	 * Getter for <code>milks.milks</code>.
	 */
	public Long getMilks() {
		return (Long) get(1);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	@Override
	public Record1<String> key() {
		return (Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record2 type implementation
	// -------------------------------------------------------------------------

	@Override
	public Row2<String, Long> fieldsRow() {
		return (Row2) super.fieldsRow();
	}

	@Override
	public Row2<String, Long> valuesRow() {
		return (Row2) super.valuesRow();
	}

	@Override
	public Field<String> field1() {
		return Milks.MILKS.PLAYERNAME;
	}

	@Override
	public Field<Long> field2() {
		return Milks.MILKS.MILKS_;
	}

	@Override
	public String component1() {
		return getPlayername();
	}

	@Override
	public Long component2() {
		return getMilks();
	}

	@Override
	public String value1() {
		return getPlayername();
	}

	@Override
	public Long value2() {
		return getMilks();
	}

	@Override
	public MilksRecord value1(String value) {
		setPlayername(value);
		return this;
	}

	@Override
	public MilksRecord value2(Long value) {
		setMilks(value);
		return this;
	}

	@Override
	public MilksRecord values(String value1, Long value2) {
		value1(value1);
		value2(value2);
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached MilksRecord
	 */
	public MilksRecord() {
		super(Milks.MILKS);
	}

	/**
	 * Create a detached, initialised MilksRecord
	 */
	public MilksRecord(String playername, Long milks) {
		super(Milks.MILKS);

		set(0, playername);
		set(1, milks);
	}
}
