/*
 * This file is generated by jOOQ.
 */
package com.hm.achievement.db.tables.records;

import com.hm.achievement.db.tables.Musicdiscs;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record2;
import org.jooq.Row2;
import org.jooq.impl.UpdatableRecordImpl;

/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class MusicdiscsRecord extends UpdatableRecordImpl<MusicdiscsRecord> implements Record2<String, Long> {

	private static final long serialVersionUID = 134838998;

	/**
	 * Setter for <code>musicdiscs.playername</code>.
	 */
	public void setPlayername(String value) {
		set(0, value);
	}

	/**
	 * Getter for <code>musicdiscs.playername</code>.
	 */
	public String getPlayername() {
		return (String) get(0);
	}

	/**
	 * Setter for <code>musicdiscs.musicdiscs</code>.
	 */
	public void setMusicdiscs(Long value) {
		set(1, value);
	}

	/**
	 * Getter for <code>musicdiscs.musicdiscs</code>.
	 */
	public Long getMusicdiscs() {
		return (Long) get(1);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	@Override
	public Record1<String> key() {
		return (Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record2 type implementation
	// -------------------------------------------------------------------------

	@Override
	public Row2<String, Long> fieldsRow() {
		return (Row2) super.fieldsRow();
	}

	@Override
	public Row2<String, Long> valuesRow() {
		return (Row2) super.valuesRow();
	}

	@Override
	public Field<String> field1() {
		return Musicdiscs.MUSICDISCS.PLAYERNAME;
	}

	@Override
	public Field<Long> field2() {
		return Musicdiscs.MUSICDISCS.MUSICDISCS_;
	}

	@Override
	public String component1() {
		return getPlayername();
	}

	@Override
	public Long component2() {
		return getMusicdiscs();
	}

	@Override
	public String value1() {
		return getPlayername();
	}

	@Override
	public Long value2() {
		return getMusicdiscs();
	}

	@Override
	public MusicdiscsRecord value1(String value) {
		setPlayername(value);
		return this;
	}

	@Override
	public MusicdiscsRecord value2(Long value) {
		setMusicdiscs(value);
		return this;
	}

	@Override
	public MusicdiscsRecord values(String value1, Long value2) {
		value1(value1);
		value2(value2);
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached MusicdiscsRecord
	 */
	public MusicdiscsRecord() {
		super(Musicdiscs.MUSICDISCS);
	}

	/**
	 * Create a detached, initialised MusicdiscsRecord
	 */
	public MusicdiscsRecord(String playername, Long musicdiscs) {
		super(Musicdiscs.MUSICDISCS);

		set(0, playername);
		set(1, musicdiscs);
	}
}
