/*
 * This file is generated by jOOQ.
 */
package com.hm.achievement.db.tables.records;

import com.hm.achievement.db.tables.NormalAchievement;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record3;
import org.jooq.Row3;
import org.jooq.impl.UpdatableRecordImpl;

/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class NormalAchievementRecord extends UpdatableRecordImpl<NormalAchievementRecord> implements Record3<String, Integer, String> {

	private static final long serialVersionUID = 1;

	/**
	 * Setter for <code>normalachievement.playername</code>.
	 */
	public void setPlayername(String value) {
		set(0, value);
	}

	/**
	 * Getter for <code>normalachievement.playername</code>.
	 */
	public String getPlayername() {
		return (String) get(0);
	}

	/**
	 * Setter for <code>normalachievement.normalachievement</code>.
	 */
	public void setNormalAchievement(Integer value) {
		set(1, value);
	}

	/**
	 * Getter for <code>normalachievement.normalachievement</code>.
	 */
	public Integer getNormalAchievement() {
		return (Integer) get(1);
	}

	/**
	 * Setter for <code>normalachievement.date</code>.
	 */
	public void setDate(String value) {
		set(2, value);
	}

	/**
	 * Getter for <code>normalachievement.date</code>.
	 */
	public String getDate() {
		return (String) get(2);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	@Override
	public Record1<String> key() {
		return (Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record3 type implementation
	// -------------------------------------------------------------------------

	@Override
	public Row3<String, Integer, String> fieldsRow() {
		return (Row3) super.fieldsRow();
	}

	@Override
	public Row3<String, Integer, String> valuesRow() {
		return (Row3) super.valuesRow();
	}

	@Override
	public Field<String> field1() {
		return NormalAchievement.NORMALACHIEVEMENT.PLAYERNAME;
	}

	@Override
	public Field<Integer> field2() {
		return NormalAchievement.NORMALACHIEVEMENT.NORMALACHIEVEMENT_;
	}

	@Override
	public Field<String> field3() {
		return NormalAchievement.NORMALACHIEVEMENT.DATE;
	}

	@Override
	public String component1() {
		return getPlayername();
	}

	@Override
	public Integer component2() {
		return getNormalAchievement();
	}

	@Override
	public String component3() {
		return getDate();
	}

	@Override
	public String value1() {
		return getPlayername();
	}

	@Override
	public Integer value2() {
		return getNormalAchievement();
	}

	@Override
	public String value3() {
		return getDate();
	}

	@Override
	public NormalAchievementRecord value1(String value) {
		setPlayername(value);
		return this;
	}

	@Override
	public NormalAchievementRecord value2(Integer value) {
		setNormalAchievement(value);
		return this;
	}

	@Override
	public NormalAchievementRecord value3(String value) {
		setDate(value);
		return this;
	}

	@Override
	public NormalAchievementRecord values(String value1, Integer value2, String value3) {
		value1(value1);
		value2(value2);
		value3(value3);
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached NormalAchievementRecord
	 */
	public NormalAchievementRecord() {
		super(NormalAchievement.NORMALACHIEVEMENT);
	}

	/**
	 * Create a detached, initialised NormalAchievementRecord
	 */
	public NormalAchievementRecord(String playername, Integer normalachievement, String date) {
		super(NormalAchievement.NORMALACHIEVEMENT);

		set(0, playername);
		set(1, normalachievement);
		set(2, date);
	}
}
