/*
 * This file is generated by jOOQ.
 */
package com.hm.achievement.db.tables.records;

import com.hm.achievement.db.tables.Shears;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record2;
import org.jooq.Row2;
import org.jooq.impl.UpdatableRecordImpl;

/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ShearsRecord extends UpdatableRecordImpl<ShearsRecord> implements Record2<String, Long> {

	private static final long serialVersionUID = 1870413040;

	/**
	 * Setter for <code>shears.playername</code>.
	 */
	public void setPlayername(String value) {
		set(0, value);
	}

	/**
	 * Getter for <code>shears.playername</code>.
	 */
	public String getPlayername() {
		return (String) get(0);
	}

	/**
	 * Setter for <code>shears.shears</code>.
	 */
	public void setShears(Long value) {
		set(1, value);
	}

	/**
	 * Getter for <code>shears.shears</code>.
	 */
	public Long getShears() {
		return (Long) get(1);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	@Override
	public Record1<String> key() {
		return (Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record2 type implementation
	// -------------------------------------------------------------------------

	@Override
	public Row2<String, Long> fieldsRow() {
		return (Row2) super.fieldsRow();
	}

	@Override
	public Row2<String, Long> valuesRow() {
		return (Row2) super.valuesRow();
	}

	@Override
	public Field<String> field1() {
		return Shears.SHEARS.PLAYERNAME;
	}

	@Override
	public Field<Long> field2() {
		return Shears.SHEARS.SHEARS_;
	}

	@Override
	public String component1() {
		return getPlayername();
	}

	@Override
	public Long component2() {
		return getShears();
	}

	@Override
	public String value1() {
		return getPlayername();
	}

	@Override
	public Long value2() {
		return getShears();
	}

	@Override
	public ShearsRecord value1(String value) {
		setPlayername(value);
		return this;
	}

	@Override
	public ShearsRecord value2(Long value) {
		setShears(value);
		return this;
	}

	@Override
	public ShearsRecord values(String value1, Long value2) {
		value1(value1);
		value2(value2);
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached ShearsRecord
	 */
	public ShearsRecord() {
		super(Shears.SHEARS);
	}

	/**
	 * Create a detached, initialised ShearsRecord
	 */
	public ShearsRecord(String playername, Long shears) {
		super(Shears.SHEARS);

		set(0, playername);
		set(1, shears);
	}
}
