/*
 * This file is generated by jOOQ.
 */
package com.hm.achievement.db.tables.records;

import com.hm.achievement.db.tables.Smelting;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record2;
import org.jooq.Row2;
import org.jooq.impl.UpdatableRecordImpl;

/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SmeltingRecord extends UpdatableRecordImpl<SmeltingRecord> implements Record2<String, Long> {

	private static final long serialVersionUID = -247400078;

	/**
	 * Setter for <code>smelting.playername</code>.
	 */
	public void setPlayername(String value) {
		set(0, value);
	}

	/**
	 * Getter for <code>smelting.playername</code>.
	 */
	public String getPlayername() {
		return (String) get(0);
	}

	/**
	 * Setter for <code>smelting.smelting</code>.
	 */
	public void setSmelting(Long value) {
		set(1, value);
	}

	/**
	 * Getter for <code>smelting.smelting</code>.
	 */
	public Long getSmelting() {
		return (Long) get(1);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	@Override
	public Record1<String> key() {
		return (Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record2 type implementation
	// -------------------------------------------------------------------------

	@Override
	public Row2<String, Long> fieldsRow() {
		return (Row2) super.fieldsRow();
	}

	@Override
	public Row2<String, Long> valuesRow() {
		return (Row2) super.valuesRow();
	}

	@Override
	public Field<String> field1() {
		return Smelting.SMELTING.PLAYERNAME;
	}

	@Override
	public Field<Long> field2() {
		return Smelting.SMELTING.SMELTING_;
	}

	@Override
	public String component1() {
		return getPlayername();
	}

	@Override
	public Long component2() {
		return getSmelting();
	}

	@Override
	public String value1() {
		return getPlayername();
	}

	@Override
	public Long value2() {
		return getSmelting();
	}

	@Override
	public SmeltingRecord value1(String value) {
		setPlayername(value);
		return this;
	}

	@Override
	public SmeltingRecord value2(Long value) {
		setSmelting(value);
		return this;
	}

	@Override
	public SmeltingRecord values(String value1, Long value2) {
		value1(value1);
		value2(value2);
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached SmeltingRecord
	 */
	public SmeltingRecord() {
		super(Smelting.SMELTING);
	}

	/**
	 * Create a detached, initialised SmeltingRecord
	 */
	public SmeltingRecord(String playername, Long smelting) {
		super(Smelting.SMELTING);

		set(0, playername);
		set(1, smelting);
	}
}
