/*
 * This file is generated by jOOQ.
 */
package com.hm.achievement.db.tables.records;

import com.hm.achievement.db.tables.Tames;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record2;
import org.jooq.Row2;
import org.jooq.impl.UpdatableRecordImpl;

/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TamesRecord extends UpdatableRecordImpl<TamesRecord> implements Record2<String, Long> {

	private static final long serialVersionUID = -1329613706;

	/**
	 * Setter for <code>tames.playername</code>.
	 */
	public void setPlayername(String value) {
		set(0, value);
	}

	/**
	 * Getter for <code>tames.playername</code>.
	 */
	public String getPlayername() {
		return (String) get(0);
	}

	/**
	 * Setter for <code>tames.tames</code>.
	 */
	public void setTames(Long value) {
		set(1, value);
	}

	/**
	 * Getter for <code>tames.tames</code>.
	 */
	public Long getTames() {
		return (Long) get(1);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	@Override
	public Record1<String> key() {
		return (Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record2 type implementation
	// -------------------------------------------------------------------------

	@Override
	public Row2<String, Long> fieldsRow() {
		return (Row2) super.fieldsRow();
	}

	@Override
	public Row2<String, Long> valuesRow() {
		return (Row2) super.valuesRow();
	}

	@Override
	public Field<String> field1() {
		return Tames.TAMES.PLAYERNAME;
	}

	@Override
	public Field<Long> field2() {
		return Tames.TAMES.TAMES_;
	}

	@Override
	public String component1() {
		return getPlayername();
	}

	@Override
	public Long component2() {
		return getTames();
	}

	@Override
	public String value1() {
		return getPlayername();
	}

	@Override
	public Long value2() {
		return getTames();
	}

	@Override
	public TamesRecord value1(String value) {
		setPlayername(value);
		return this;
	}

	@Override
	public TamesRecord value2(Long value) {
		setTames(value);
		return this;
	}

	@Override
	public TamesRecord values(String value1, Long value2) {
		value1(value1);
		value2(value2);
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached TamesRecord
	 */
	public TamesRecord() {
		super(Tames.TAMES);
	}

	/**
	 * Create a detached, initialised TamesRecord
	 */
	public TamesRecord(String playername, Long tames) {
		super(Tames.TAMES);

		set(0, playername);
		set(1, tames);
	}
}
