/*
 * This file is generated by jOOQ.
 */
package com.hm.achievement.db.tables.records;

import com.hm.achievement.db.tables.Targetsshot;

import org.jooq.Field;
import org.jooq.Record2;
import org.jooq.Record3;
import org.jooq.Row3;
import org.jooq.impl.UpdatableRecordImpl;

/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TargetsshotRecord extends UpdatableRecordImpl<TargetsshotRecord> implements Record3<String, String, Integer> {

	private static final long serialVersionUID = -1459630279;

	/**
	 * Setter for <code>targetsshot.playername</code>.
	 */
	public void setPlayername(String value) {
		set(0, value);
	}

	/**
	 * Getter for <code>targetsshot.playername</code>.
	 */
	public String getPlayername() {
		return (String) get(0);
	}

	/**
	 * Setter for <code>targetsshot.targetname</code>.
	 */
	public void setTargetname(String value) {
		set(1, value);
	}

	/**
	 * Getter for <code>targetsshot.targetname</code>.
	 */
	public String getTargetname() {
		return (String) get(1);
	}

	/**
	 * Setter for <code>targetsshot.targetsshot</code>.
	 */
	public void setTargetsshot(Integer value) {
		set(2, value);
	}

	/**
	 * Getter for <code>targetsshot.targetsshot</code>.
	 */
	public Integer getTargetsshot() {
		return (Integer) get(2);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	@Override
	public Record2<String, String> key() {
		return (Record2) super.key();
	}

	// -------------------------------------------------------------------------
	// Record3 type implementation
	// -------------------------------------------------------------------------

	@Override
	public Row3<String, String, Integer> fieldsRow() {
		return (Row3) super.fieldsRow();
	}

	@Override
	public Row3<String, String, Integer> valuesRow() {
		return (Row3) super.valuesRow();
	}

	@Override
	public Field<String> field1() {
		return Targetsshot.TARGETSSHOT.PLAYERNAME;
	}

	@Override
	public Field<String> field2() {
		return Targetsshot.TARGETSSHOT.TARGETNAME;
	}

	@Override
	public Field<Integer> field3() {
		return Targetsshot.TARGETSSHOT.TARGETSSHOT_;
	}

	@Override
	public String component1() {
		return getPlayername();
	}

	@Override
	public String component2() {
		return getTargetname();
	}

	@Override
	public Integer component3() {
		return getTargetsshot();
	}

	@Override
	public String value1() {
		return getPlayername();
	}

	@Override
	public String value2() {
		return getTargetname();
	}

	@Override
	public Integer value3() {
		return getTargetsshot();
	}

	@Override
	public TargetsshotRecord value1(String value) {
		setPlayername(value);
		return this;
	}

	@Override
	public TargetsshotRecord value2(String value) {
		setTargetname(value);
		return this;
	}

	@Override
	public TargetsshotRecord value3(Integer value) {
		setTargetsshot(value);
		return this;
	}

	@Override
	public TargetsshotRecord values(String value1, String value2, Integer value3) {
		value1(value1);
		value2(value2);
		value3(value3);
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached TargetsshotRecord
	 */
	public TargetsshotRecord() {
		super(Targetsshot.TARGETSSHOT);
	}

	/**
	 * Create a detached, initialised TargetsshotRecord
	 */
	public TargetsshotRecord(String playername, String targetname, Integer targetsshot) {
		super(Targetsshot.TARGETSSHOT);

		set(0, playername);
		set(1, targetname);
		set(2, targetsshot);
	}
}
