/*
 * This file is generated by jOOQ.
 */
package com.hm.achievement.db.tables.records;

import com.hm.achievement.db.tables.Trades;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record2;
import org.jooq.Row2;
import org.jooq.impl.UpdatableRecordImpl;

/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TradesRecord extends UpdatableRecordImpl<TradesRecord> implements Record2<String, Long> {

	private static final long serialVersionUID = 1549355378;

	/**
	 * Setter for <code>trades.playername</code>.
	 */
	public void setPlayername(String value) {
		set(0, value);
	}

	/**
	 * Getter for <code>trades.playername</code>.
	 */
	public String getPlayername() {
		return (String) get(0);
	}

	/**
	 * Setter for <code>trades.trades</code>.
	 */
	public void setTrades(Long value) {
		set(1, value);
	}

	/**
	 * Getter for <code>trades.trades</code>.
	 */
	public Long getTrades() {
		return (Long) get(1);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	@Override
	public Record1<String> key() {
		return (Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record2 type implementation
	// -------------------------------------------------------------------------

	@Override
	public Row2<String, Long> fieldsRow() {
		return (Row2) super.fieldsRow();
	}

	@Override
	public Row2<String, Long> valuesRow() {
		return (Row2) super.valuesRow();
	}

	@Override
	public Field<String> field1() {
		return Trades.TRADES.PLAYERNAME;
	}

	@Override
	public Field<Long> field2() {
		return Trades.TRADES.TRADES_;
	}

	@Override
	public String component1() {
		return getPlayername();
	}

	@Override
	public Long component2() {
		return getTrades();
	}

	@Override
	public String value1() {
		return getPlayername();
	}

	@Override
	public Long value2() {
		return getTrades();
	}

	@Override
	public TradesRecord value1(String value) {
		setPlayername(value);
		return this;
	}

	@Override
	public TradesRecord value2(Long value) {
		setTrades(value);
		return this;
	}

	@Override
	public TradesRecord values(String value1, Long value2) {
		value1(value1);
		value2(value2);
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached TradesRecord
	 */
	public TradesRecord() {
		super(Trades.TRADES);
	}

	/**
	 * Create a detached, initialised TradesRecord
	 */
	public TradesRecord(String playername, Long trades) {
		super(Trades.TRADES);

		set(0, playername);
		set(1, trades);
	}
}
