/*
 * This file is generated by jOOQ.
 */
package com.hm.achievement.db.tables.records;

import com.hm.achievement.db.tables.Treasures;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record2;
import org.jooq.Row2;
import org.jooq.impl.UpdatableRecordImpl;

/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TreasuresRecord extends UpdatableRecordImpl<TreasuresRecord> implements Record2<String, Long> {

	private static final long serialVersionUID = -986877734;

	/**
	 * Setter for <code>treasures.playername</code>.
	 */
	public void setPlayername(String value) {
		set(0, value);
	}

	/**
	 * Getter for <code>treasures.playername</code>.
	 */
	public String getPlayername() {
		return (String) get(0);
	}

	/**
	 * Setter for <code>treasures.treasures</code>.
	 */
	public void setTreasures(Long value) {
		set(1, value);
	}

	/**
	 * Getter for <code>treasures.treasures</code>.
	 */
	public Long getTreasures() {
		return (Long) get(1);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	@Override
	public Record1<String> key() {
		return (Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record2 type implementation
	// -------------------------------------------------------------------------

	@Override
	public Row2<String, Long> fieldsRow() {
		return (Row2) super.fieldsRow();
	}

	@Override
	public Row2<String, Long> valuesRow() {
		return (Row2) super.valuesRow();
	}

	@Override
	public Field<String> field1() {
		return Treasures.TREASURES.PLAYERNAME;
	}

	@Override
	public Field<Long> field2() {
		return Treasures.TREASURES.TREASURES_;
	}

	@Override
	public String component1() {
		return getPlayername();
	}

	@Override
	public Long component2() {
		return getTreasures();
	}

	@Override
	public String value1() {
		return getPlayername();
	}

	@Override
	public Long value2() {
		return getTreasures();
	}

	@Override
	public TreasuresRecord value1(String value) {
		setPlayername(value);
		return this;
	}

	@Override
	public TreasuresRecord value2(Long value) {
		setTreasures(value);
		return this;
	}

	@Override
	public TreasuresRecord values(String value1, Long value2) {
		value1(value1);
		value2(value2);
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached TreasuresRecord
	 */
	public TreasuresRecord() {
		super(Treasures.TREASURES);
	}

	/**
	 * Create a detached, initialised TreasuresRecord
	 */
	public TreasuresRecord(String playername, Long treasures) {
		super(Treasures.TREASURES);

		set(0, playername);
		set(1, treasures);
	}
}
